
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `GuideStep` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model GuideStep
 * 
 */
export type GuideStepModel = runtime.Types.Result.DefaultSelection<Prisma.$GuideStepPayload>

export type AggregateGuideStep = {
  _count: GuideStepCountAggregateOutputType | null
  _avg: GuideStepAvgAggregateOutputType | null
  _sum: GuideStepSumAggregateOutputType | null
  _min: GuideStepMinAggregateOutputType | null
  _max: GuideStepMaxAggregateOutputType | null
}

export type GuideStepAvgAggregateOutputType = {
  id: number | null
  guideId: number | null
  index: number | null
}

export type GuideStepSumAggregateOutputType = {
  id: number | null
  guideId: number | null
  index: number | null
}

export type GuideStepMinAggregateOutputType = {
  id: number | null
  guideId: number | null
  index: number | null
  name: string | null
  instructions: string | null
  example: string | null
  amtOfResourcePerStep: string | null
}

export type GuideStepMaxAggregateOutputType = {
  id: number | null
  guideId: number | null
  index: number | null
  name: string | null
  instructions: string | null
  example: string | null
  amtOfResourcePerStep: string | null
}

export type GuideStepCountAggregateOutputType = {
  id: number
  guideId: number
  index: number
  name: number
  instructions: number
  example: number
  amtOfResourcePerStep: number
  _all: number
}


export type GuideStepAvgAggregateInputType = {
  id?: true
  guideId?: true
  index?: true
}

export type GuideStepSumAggregateInputType = {
  id?: true
  guideId?: true
  index?: true
}

export type GuideStepMinAggregateInputType = {
  id?: true
  guideId?: true
  index?: true
  name?: true
  instructions?: true
  example?: true
  amtOfResourcePerStep?: true
}

export type GuideStepMaxAggregateInputType = {
  id?: true
  guideId?: true
  index?: true
  name?: true
  instructions?: true
  example?: true
  amtOfResourcePerStep?: true
}

export type GuideStepCountAggregateInputType = {
  id?: true
  guideId?: true
  index?: true
  name?: true
  instructions?: true
  example?: true
  amtOfResourcePerStep?: true
  _all?: true
}

export type GuideStepAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GuideStep to aggregate.
   */
  where?: Prisma.GuideStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuideSteps to fetch.
   */
  orderBy?: Prisma.GuideStepOrderByWithRelationInput | Prisma.GuideStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GuideStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuideSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuideSteps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GuideSteps
  **/
  _count?: true | GuideStepCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: GuideStepAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: GuideStepSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GuideStepMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GuideStepMaxAggregateInputType
}

export type GetGuideStepAggregateType<T extends GuideStepAggregateArgs> = {
      [P in keyof T & keyof AggregateGuideStep]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGuideStep[P]>
    : Prisma.GetScalarType<T[P], AggregateGuideStep[P]>
}




export type GuideStepGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GuideStepWhereInput
  orderBy?: Prisma.GuideStepOrderByWithAggregationInput | Prisma.GuideStepOrderByWithAggregationInput[]
  by: Prisma.GuideStepScalarFieldEnum[] | Prisma.GuideStepScalarFieldEnum
  having?: Prisma.GuideStepScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GuideStepCountAggregateInputType | true
  _avg?: GuideStepAvgAggregateInputType
  _sum?: GuideStepSumAggregateInputType
  _min?: GuideStepMinAggregateInputType
  _max?: GuideStepMaxAggregateInputType
}

export type GuideStepGroupByOutputType = {
  id: number
  guideId: number
  index: number
  name: string
  instructions: string | null
  example: string | null
  amtOfResourcePerStep: string | null
  _count: GuideStepCountAggregateOutputType | null
  _avg: GuideStepAvgAggregateOutputType | null
  _sum: GuideStepSumAggregateOutputType | null
  _min: GuideStepMinAggregateOutputType | null
  _max: GuideStepMaxAggregateOutputType | null
}

type GetGuideStepGroupByPayload<T extends GuideStepGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GuideStepGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GuideStepGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GuideStepGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GuideStepGroupByOutputType[P]>
      }
    >
  >



export type GuideStepWhereInput = {
  AND?: Prisma.GuideStepWhereInput | Prisma.GuideStepWhereInput[]
  OR?: Prisma.GuideStepWhereInput[]
  NOT?: Prisma.GuideStepWhereInput | Prisma.GuideStepWhereInput[]
  id?: Prisma.IntFilter<"GuideStep"> | number
  guideId?: Prisma.IntFilter<"GuideStep"> | number
  index?: Prisma.IntFilter<"GuideStep"> | number
  name?: Prisma.StringFilter<"GuideStep"> | string
  instructions?: Prisma.StringNullableFilter<"GuideStep"> | string | null
  example?: Prisma.StringNullableFilter<"GuideStep"> | string | null
  amtOfResourcePerStep?: Prisma.StringNullableFilter<"GuideStep"> | string | null
  guide?: Prisma.XOR<Prisma.GuideScalarRelationFilter, Prisma.GuideWhereInput>
  sessions?: Prisma.SessionListRelationFilter
  sessionSteps?: Prisma.SessionStepListRelationFilter
}

export type GuideStepOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  guideId?: Prisma.SortOrder
  index?: Prisma.SortOrder
  name?: Prisma.SortOrder
  instructions?: Prisma.SortOrderInput | Prisma.SortOrder
  example?: Prisma.SortOrderInput | Prisma.SortOrder
  amtOfResourcePerStep?: Prisma.SortOrderInput | Prisma.SortOrder
  guide?: Prisma.GuideOrderByWithRelationInput
  sessions?: Prisma.SessionOrderByRelationAggregateInput
  sessionSteps?: Prisma.SessionStepOrderByRelationAggregateInput
}

export type GuideStepWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.GuideStepWhereInput | Prisma.GuideStepWhereInput[]
  OR?: Prisma.GuideStepWhereInput[]
  NOT?: Prisma.GuideStepWhereInput | Prisma.GuideStepWhereInput[]
  guideId?: Prisma.IntFilter<"GuideStep"> | number
  index?: Prisma.IntFilter<"GuideStep"> | number
  name?: Prisma.StringFilter<"GuideStep"> | string
  instructions?: Prisma.StringNullableFilter<"GuideStep"> | string | null
  example?: Prisma.StringNullableFilter<"GuideStep"> | string | null
  amtOfResourcePerStep?: Prisma.StringNullableFilter<"GuideStep"> | string | null
  guide?: Prisma.XOR<Prisma.GuideScalarRelationFilter, Prisma.GuideWhereInput>
  sessions?: Prisma.SessionListRelationFilter
  sessionSteps?: Prisma.SessionStepListRelationFilter
}, "id">

export type GuideStepOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  guideId?: Prisma.SortOrder
  index?: Prisma.SortOrder
  name?: Prisma.SortOrder
  instructions?: Prisma.SortOrderInput | Prisma.SortOrder
  example?: Prisma.SortOrderInput | Prisma.SortOrder
  amtOfResourcePerStep?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.GuideStepCountOrderByAggregateInput
  _avg?: Prisma.GuideStepAvgOrderByAggregateInput
  _max?: Prisma.GuideStepMaxOrderByAggregateInput
  _min?: Prisma.GuideStepMinOrderByAggregateInput
  _sum?: Prisma.GuideStepSumOrderByAggregateInput
}

export type GuideStepScalarWhereWithAggregatesInput = {
  AND?: Prisma.GuideStepScalarWhereWithAggregatesInput | Prisma.GuideStepScalarWhereWithAggregatesInput[]
  OR?: Prisma.GuideStepScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GuideStepScalarWhereWithAggregatesInput | Prisma.GuideStepScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"GuideStep"> | number
  guideId?: Prisma.IntWithAggregatesFilter<"GuideStep"> | number
  index?: Prisma.IntWithAggregatesFilter<"GuideStep"> | number
  name?: Prisma.StringWithAggregatesFilter<"GuideStep"> | string
  instructions?: Prisma.StringNullableWithAggregatesFilter<"GuideStep"> | string | null
  example?: Prisma.StringNullableWithAggregatesFilter<"GuideStep"> | string | null
  amtOfResourcePerStep?: Prisma.StringNullableWithAggregatesFilter<"GuideStep"> | string | null
}

export type GuideStepCreateInput = {
  index: number
  name: string
  instructions?: string | null
  example?: string | null
  amtOfResourcePerStep?: string | null
  guide: Prisma.GuideCreateNestedOneWithoutGuideStepsInput
  sessions?: Prisma.SessionCreateNestedManyWithoutGuideStepInput
  sessionSteps?: Prisma.SessionStepCreateNestedManyWithoutGuideStepInput
}

export type GuideStepUncheckedCreateInput = {
  id?: number
  guideId: number
  index: number
  name: string
  instructions?: string | null
  example?: string | null
  amtOfResourcePerStep?: string | null
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutGuideStepInput
  sessionSteps?: Prisma.SessionStepUncheckedCreateNestedManyWithoutGuideStepInput
}

export type GuideStepUpdateInput = {
  index?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  instructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  example?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amtOfResourcePerStep?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guide?: Prisma.GuideUpdateOneRequiredWithoutGuideStepsNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutGuideStepNestedInput
  sessionSteps?: Prisma.SessionStepUpdateManyWithoutGuideStepNestedInput
}

export type GuideStepUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guideId?: Prisma.IntFieldUpdateOperationsInput | number
  index?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  instructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  example?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amtOfResourcePerStep?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutGuideStepNestedInput
  sessionSteps?: Prisma.SessionStepUncheckedUpdateManyWithoutGuideStepNestedInput
}

export type GuideStepCreateManyInput = {
  id?: number
  guideId: number
  index: number
  name: string
  instructions?: string | null
  example?: string | null
  amtOfResourcePerStep?: string | null
}

export type GuideStepUpdateManyMutationInput = {
  index?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  instructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  example?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amtOfResourcePerStep?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type GuideStepUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guideId?: Prisma.IntFieldUpdateOperationsInput | number
  index?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  instructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  example?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amtOfResourcePerStep?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type GuideStepListRelationFilter = {
  every?: Prisma.GuideStepWhereInput
  some?: Prisma.GuideStepWhereInput
  none?: Prisma.GuideStepWhereInput
}

export type GuideStepOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type GuideStepCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guideId?: Prisma.SortOrder
  index?: Prisma.SortOrder
  name?: Prisma.SortOrder
  instructions?: Prisma.SortOrder
  example?: Prisma.SortOrder
  amtOfResourcePerStep?: Prisma.SortOrder
}

export type GuideStepAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guideId?: Prisma.SortOrder
  index?: Prisma.SortOrder
}

export type GuideStepMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guideId?: Prisma.SortOrder
  index?: Prisma.SortOrder
  name?: Prisma.SortOrder
  instructions?: Prisma.SortOrder
  example?: Prisma.SortOrder
  amtOfResourcePerStep?: Prisma.SortOrder
}

export type GuideStepMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guideId?: Prisma.SortOrder
  index?: Prisma.SortOrder
  name?: Prisma.SortOrder
  instructions?: Prisma.SortOrder
  example?: Prisma.SortOrder
  amtOfResourcePerStep?: Prisma.SortOrder
}

export type GuideStepSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  guideId?: Prisma.SortOrder
  index?: Prisma.SortOrder
}

export type GuideStepNullableScalarRelationFilter = {
  is?: Prisma.GuideStepWhereInput | null
  isNot?: Prisma.GuideStepWhereInput | null
}

export type GuideStepScalarRelationFilter = {
  is?: Prisma.GuideStepWhereInput
  isNot?: Prisma.GuideStepWhereInput
}

export type GuideStepCreateNestedManyWithoutGuideInput = {
  create?: Prisma.XOR<Prisma.GuideStepCreateWithoutGuideInput, Prisma.GuideStepUncheckedCreateWithoutGuideInput> | Prisma.GuideStepCreateWithoutGuideInput[] | Prisma.GuideStepUncheckedCreateWithoutGuideInput[]
  connectOrCreate?: Prisma.GuideStepCreateOrConnectWithoutGuideInput | Prisma.GuideStepCreateOrConnectWithoutGuideInput[]
  createMany?: Prisma.GuideStepCreateManyGuideInputEnvelope
  connect?: Prisma.GuideStepWhereUniqueInput | Prisma.GuideStepWhereUniqueInput[]
}

export type GuideStepUncheckedCreateNestedManyWithoutGuideInput = {
  create?: Prisma.XOR<Prisma.GuideStepCreateWithoutGuideInput, Prisma.GuideStepUncheckedCreateWithoutGuideInput> | Prisma.GuideStepCreateWithoutGuideInput[] | Prisma.GuideStepUncheckedCreateWithoutGuideInput[]
  connectOrCreate?: Prisma.GuideStepCreateOrConnectWithoutGuideInput | Prisma.GuideStepCreateOrConnectWithoutGuideInput[]
  createMany?: Prisma.GuideStepCreateManyGuideInputEnvelope
  connect?: Prisma.GuideStepWhereUniqueInput | Prisma.GuideStepWhereUniqueInput[]
}

export type GuideStepUpdateManyWithoutGuideNestedInput = {
  create?: Prisma.XOR<Prisma.GuideStepCreateWithoutGuideInput, Prisma.GuideStepUncheckedCreateWithoutGuideInput> | Prisma.GuideStepCreateWithoutGuideInput[] | Prisma.GuideStepUncheckedCreateWithoutGuideInput[]
  connectOrCreate?: Prisma.GuideStepCreateOrConnectWithoutGuideInput | Prisma.GuideStepCreateOrConnectWithoutGuideInput[]
  upsert?: Prisma.GuideStepUpsertWithWhereUniqueWithoutGuideInput | Prisma.GuideStepUpsertWithWhereUniqueWithoutGuideInput[]
  createMany?: Prisma.GuideStepCreateManyGuideInputEnvelope
  set?: Prisma.GuideStepWhereUniqueInput | Prisma.GuideStepWhereUniqueInput[]
  disconnect?: Prisma.GuideStepWhereUniqueInput | Prisma.GuideStepWhereUniqueInput[]
  delete?: Prisma.GuideStepWhereUniqueInput | Prisma.GuideStepWhereUniqueInput[]
  connect?: Prisma.GuideStepWhereUniqueInput | Prisma.GuideStepWhereUniqueInput[]
  update?: Prisma.GuideStepUpdateWithWhereUniqueWithoutGuideInput | Prisma.GuideStepUpdateWithWhereUniqueWithoutGuideInput[]
  updateMany?: Prisma.GuideStepUpdateManyWithWhereWithoutGuideInput | Prisma.GuideStepUpdateManyWithWhereWithoutGuideInput[]
  deleteMany?: Prisma.GuideStepScalarWhereInput | Prisma.GuideStepScalarWhereInput[]
}

export type GuideStepUncheckedUpdateManyWithoutGuideNestedInput = {
  create?: Prisma.XOR<Prisma.GuideStepCreateWithoutGuideInput, Prisma.GuideStepUncheckedCreateWithoutGuideInput> | Prisma.GuideStepCreateWithoutGuideInput[] | Prisma.GuideStepUncheckedCreateWithoutGuideInput[]
  connectOrCreate?: Prisma.GuideStepCreateOrConnectWithoutGuideInput | Prisma.GuideStepCreateOrConnectWithoutGuideInput[]
  upsert?: Prisma.GuideStepUpsertWithWhereUniqueWithoutGuideInput | Prisma.GuideStepUpsertWithWhereUniqueWithoutGuideInput[]
  createMany?: Prisma.GuideStepCreateManyGuideInputEnvelope
  set?: Prisma.GuideStepWhereUniqueInput | Prisma.GuideStepWhereUniqueInput[]
  disconnect?: Prisma.GuideStepWhereUniqueInput | Prisma.GuideStepWhereUniqueInput[]
  delete?: Prisma.GuideStepWhereUniqueInput | Prisma.GuideStepWhereUniqueInput[]
  connect?: Prisma.GuideStepWhereUniqueInput | Prisma.GuideStepWhereUniqueInput[]
  update?: Prisma.GuideStepUpdateWithWhereUniqueWithoutGuideInput | Prisma.GuideStepUpdateWithWhereUniqueWithoutGuideInput[]
  updateMany?: Prisma.GuideStepUpdateManyWithWhereWithoutGuideInput | Prisma.GuideStepUpdateManyWithWhereWithoutGuideInput[]
  deleteMany?: Prisma.GuideStepScalarWhereInput | Prisma.GuideStepScalarWhereInput[]
}

export type GuideStepCreateNestedOneWithoutSessionsInput = {
  create?: Prisma.XOR<Prisma.GuideStepCreateWithoutSessionsInput, Prisma.GuideStepUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.GuideStepCreateOrConnectWithoutSessionsInput
  connect?: Prisma.GuideStepWhereUniqueInput
}

export type GuideStepUpdateOneWithoutSessionsNestedInput = {
  create?: Prisma.XOR<Prisma.GuideStepCreateWithoutSessionsInput, Prisma.GuideStepUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.GuideStepCreateOrConnectWithoutSessionsInput
  upsert?: Prisma.GuideStepUpsertWithoutSessionsInput
  disconnect?: Prisma.GuideStepWhereInput | boolean
  delete?: Prisma.GuideStepWhereInput | boolean
  connect?: Prisma.GuideStepWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.GuideStepUpdateToOneWithWhereWithoutSessionsInput, Prisma.GuideStepUpdateWithoutSessionsInput>, Prisma.GuideStepUncheckedUpdateWithoutSessionsInput>
}

export type GuideStepCreateNestedOneWithoutSessionStepsInput = {
  create?: Prisma.XOR<Prisma.GuideStepCreateWithoutSessionStepsInput, Prisma.GuideStepUncheckedCreateWithoutSessionStepsInput>
  connectOrCreate?: Prisma.GuideStepCreateOrConnectWithoutSessionStepsInput
  connect?: Prisma.GuideStepWhereUniqueInput
}

export type GuideStepUpdateOneRequiredWithoutSessionStepsNestedInput = {
  create?: Prisma.XOR<Prisma.GuideStepCreateWithoutSessionStepsInput, Prisma.GuideStepUncheckedCreateWithoutSessionStepsInput>
  connectOrCreate?: Prisma.GuideStepCreateOrConnectWithoutSessionStepsInput
  upsert?: Prisma.GuideStepUpsertWithoutSessionStepsInput
  connect?: Prisma.GuideStepWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.GuideStepUpdateToOneWithWhereWithoutSessionStepsInput, Prisma.GuideStepUpdateWithoutSessionStepsInput>, Prisma.GuideStepUncheckedUpdateWithoutSessionStepsInput>
}

export type GuideStepCreateWithoutGuideInput = {
  index: number
  name: string
  instructions?: string | null
  example?: string | null
  amtOfResourcePerStep?: string | null
  sessions?: Prisma.SessionCreateNestedManyWithoutGuideStepInput
  sessionSteps?: Prisma.SessionStepCreateNestedManyWithoutGuideStepInput
}

export type GuideStepUncheckedCreateWithoutGuideInput = {
  id?: number
  index: number
  name: string
  instructions?: string | null
  example?: string | null
  amtOfResourcePerStep?: string | null
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutGuideStepInput
  sessionSteps?: Prisma.SessionStepUncheckedCreateNestedManyWithoutGuideStepInput
}

export type GuideStepCreateOrConnectWithoutGuideInput = {
  where: Prisma.GuideStepWhereUniqueInput
  create: Prisma.XOR<Prisma.GuideStepCreateWithoutGuideInput, Prisma.GuideStepUncheckedCreateWithoutGuideInput>
}

export type GuideStepCreateManyGuideInputEnvelope = {
  data: Prisma.GuideStepCreateManyGuideInput | Prisma.GuideStepCreateManyGuideInput[]
  skipDuplicates?: boolean
}

export type GuideStepUpsertWithWhereUniqueWithoutGuideInput = {
  where: Prisma.GuideStepWhereUniqueInput
  update: Prisma.XOR<Prisma.GuideStepUpdateWithoutGuideInput, Prisma.GuideStepUncheckedUpdateWithoutGuideInput>
  create: Prisma.XOR<Prisma.GuideStepCreateWithoutGuideInput, Prisma.GuideStepUncheckedCreateWithoutGuideInput>
}

export type GuideStepUpdateWithWhereUniqueWithoutGuideInput = {
  where: Prisma.GuideStepWhereUniqueInput
  data: Prisma.XOR<Prisma.GuideStepUpdateWithoutGuideInput, Prisma.GuideStepUncheckedUpdateWithoutGuideInput>
}

export type GuideStepUpdateManyWithWhereWithoutGuideInput = {
  where: Prisma.GuideStepScalarWhereInput
  data: Prisma.XOR<Prisma.GuideStepUpdateManyMutationInput, Prisma.GuideStepUncheckedUpdateManyWithoutGuideInput>
}

export type GuideStepScalarWhereInput = {
  AND?: Prisma.GuideStepScalarWhereInput | Prisma.GuideStepScalarWhereInput[]
  OR?: Prisma.GuideStepScalarWhereInput[]
  NOT?: Prisma.GuideStepScalarWhereInput | Prisma.GuideStepScalarWhereInput[]
  id?: Prisma.IntFilter<"GuideStep"> | number
  guideId?: Prisma.IntFilter<"GuideStep"> | number
  index?: Prisma.IntFilter<"GuideStep"> | number
  name?: Prisma.StringFilter<"GuideStep"> | string
  instructions?: Prisma.StringNullableFilter<"GuideStep"> | string | null
  example?: Prisma.StringNullableFilter<"GuideStep"> | string | null
  amtOfResourcePerStep?: Prisma.StringNullableFilter<"GuideStep"> | string | null
}

export type GuideStepCreateWithoutSessionsInput = {
  index: number
  name: string
  instructions?: string | null
  example?: string | null
  amtOfResourcePerStep?: string | null
  guide: Prisma.GuideCreateNestedOneWithoutGuideStepsInput
  sessionSteps?: Prisma.SessionStepCreateNestedManyWithoutGuideStepInput
}

export type GuideStepUncheckedCreateWithoutSessionsInput = {
  id?: number
  guideId: number
  index: number
  name: string
  instructions?: string | null
  example?: string | null
  amtOfResourcePerStep?: string | null
  sessionSteps?: Prisma.SessionStepUncheckedCreateNestedManyWithoutGuideStepInput
}

export type GuideStepCreateOrConnectWithoutSessionsInput = {
  where: Prisma.GuideStepWhereUniqueInput
  create: Prisma.XOR<Prisma.GuideStepCreateWithoutSessionsInput, Prisma.GuideStepUncheckedCreateWithoutSessionsInput>
}

export type GuideStepUpsertWithoutSessionsInput = {
  update: Prisma.XOR<Prisma.GuideStepUpdateWithoutSessionsInput, Prisma.GuideStepUncheckedUpdateWithoutSessionsInput>
  create: Prisma.XOR<Prisma.GuideStepCreateWithoutSessionsInput, Prisma.GuideStepUncheckedCreateWithoutSessionsInput>
  where?: Prisma.GuideStepWhereInput
}

export type GuideStepUpdateToOneWithWhereWithoutSessionsInput = {
  where?: Prisma.GuideStepWhereInput
  data: Prisma.XOR<Prisma.GuideStepUpdateWithoutSessionsInput, Prisma.GuideStepUncheckedUpdateWithoutSessionsInput>
}

export type GuideStepUpdateWithoutSessionsInput = {
  index?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  instructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  example?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amtOfResourcePerStep?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guide?: Prisma.GuideUpdateOneRequiredWithoutGuideStepsNestedInput
  sessionSteps?: Prisma.SessionStepUpdateManyWithoutGuideStepNestedInput
}

export type GuideStepUncheckedUpdateWithoutSessionsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guideId?: Prisma.IntFieldUpdateOperationsInput | number
  index?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  instructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  example?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amtOfResourcePerStep?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sessionSteps?: Prisma.SessionStepUncheckedUpdateManyWithoutGuideStepNestedInput
}

export type GuideStepCreateWithoutSessionStepsInput = {
  index: number
  name: string
  instructions?: string | null
  example?: string | null
  amtOfResourcePerStep?: string | null
  guide: Prisma.GuideCreateNestedOneWithoutGuideStepsInput
  sessions?: Prisma.SessionCreateNestedManyWithoutGuideStepInput
}

export type GuideStepUncheckedCreateWithoutSessionStepsInput = {
  id?: number
  guideId: number
  index: number
  name: string
  instructions?: string | null
  example?: string | null
  amtOfResourcePerStep?: string | null
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutGuideStepInput
}

export type GuideStepCreateOrConnectWithoutSessionStepsInput = {
  where: Prisma.GuideStepWhereUniqueInput
  create: Prisma.XOR<Prisma.GuideStepCreateWithoutSessionStepsInput, Prisma.GuideStepUncheckedCreateWithoutSessionStepsInput>
}

export type GuideStepUpsertWithoutSessionStepsInput = {
  update: Prisma.XOR<Prisma.GuideStepUpdateWithoutSessionStepsInput, Prisma.GuideStepUncheckedUpdateWithoutSessionStepsInput>
  create: Prisma.XOR<Prisma.GuideStepCreateWithoutSessionStepsInput, Prisma.GuideStepUncheckedCreateWithoutSessionStepsInput>
  where?: Prisma.GuideStepWhereInput
}

export type GuideStepUpdateToOneWithWhereWithoutSessionStepsInput = {
  where?: Prisma.GuideStepWhereInput
  data: Prisma.XOR<Prisma.GuideStepUpdateWithoutSessionStepsInput, Prisma.GuideStepUncheckedUpdateWithoutSessionStepsInput>
}

export type GuideStepUpdateWithoutSessionStepsInput = {
  index?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  instructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  example?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amtOfResourcePerStep?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guide?: Prisma.GuideUpdateOneRequiredWithoutGuideStepsNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutGuideStepNestedInput
}

export type GuideStepUncheckedUpdateWithoutSessionStepsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guideId?: Prisma.IntFieldUpdateOperationsInput | number
  index?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  instructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  example?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amtOfResourcePerStep?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutGuideStepNestedInput
}

export type GuideStepCreateManyGuideInput = {
  id?: number
  index: number
  name: string
  instructions?: string | null
  example?: string | null
  amtOfResourcePerStep?: string | null
}

export type GuideStepUpdateWithoutGuideInput = {
  index?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  instructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  example?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amtOfResourcePerStep?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sessions?: Prisma.SessionUpdateManyWithoutGuideStepNestedInput
  sessionSteps?: Prisma.SessionStepUpdateManyWithoutGuideStepNestedInput
}

export type GuideStepUncheckedUpdateWithoutGuideInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  index?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  instructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  example?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amtOfResourcePerStep?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutGuideStepNestedInput
  sessionSteps?: Prisma.SessionStepUncheckedUpdateManyWithoutGuideStepNestedInput
}

export type GuideStepUncheckedUpdateManyWithoutGuideInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  index?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  instructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  example?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amtOfResourcePerStep?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type GuideStepCountOutputType
 */

export type GuideStepCountOutputType = {
  sessions: number
  sessionSteps: number
}

export type GuideStepCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sessions?: boolean | GuideStepCountOutputTypeCountSessionsArgs
  sessionSteps?: boolean | GuideStepCountOutputTypeCountSessionStepsArgs
}

/**
 * GuideStepCountOutputType without action
 */
export type GuideStepCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideStepCountOutputType
   */
  select?: Prisma.GuideStepCountOutputTypeSelect<ExtArgs> | null
}

/**
 * GuideStepCountOutputType without action
 */
export type GuideStepCountOutputTypeCountSessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionWhereInput
}

/**
 * GuideStepCountOutputType without action
 */
export type GuideStepCountOutputTypeCountSessionStepsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionStepWhereInput
}


export type GuideStepSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guideId?: boolean
  index?: boolean
  name?: boolean
  instructions?: boolean
  example?: boolean
  amtOfResourcePerStep?: boolean
  guide?: boolean | Prisma.GuideDefaultArgs<ExtArgs>
  sessions?: boolean | Prisma.GuideStep$sessionsArgs<ExtArgs>
  sessionSteps?: boolean | Prisma.GuideStep$sessionStepsArgs<ExtArgs>
  _count?: boolean | Prisma.GuideStepCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["guideStep"]>

export type GuideStepSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guideId?: boolean
  index?: boolean
  name?: boolean
  instructions?: boolean
  example?: boolean
  amtOfResourcePerStep?: boolean
  guide?: boolean | Prisma.GuideDefaultArgs<ExtArgs>
}, ExtArgs["result"]["guideStep"]>

export type GuideStepSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  guideId?: boolean
  index?: boolean
  name?: boolean
  instructions?: boolean
  example?: boolean
  amtOfResourcePerStep?: boolean
  guide?: boolean | Prisma.GuideDefaultArgs<ExtArgs>
}, ExtArgs["result"]["guideStep"]>

export type GuideStepSelectScalar = {
  id?: boolean
  guideId?: boolean
  index?: boolean
  name?: boolean
  instructions?: boolean
  example?: boolean
  amtOfResourcePerStep?: boolean
}

export type GuideStepOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "guideId" | "index" | "name" | "instructions" | "example" | "amtOfResourcePerStep", ExtArgs["result"]["guideStep"]>
export type GuideStepInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  guide?: boolean | Prisma.GuideDefaultArgs<ExtArgs>
  sessions?: boolean | Prisma.GuideStep$sessionsArgs<ExtArgs>
  sessionSteps?: boolean | Prisma.GuideStep$sessionStepsArgs<ExtArgs>
  _count?: boolean | Prisma.GuideStepCountOutputTypeDefaultArgs<ExtArgs>
}
export type GuideStepIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  guide?: boolean | Prisma.GuideDefaultArgs<ExtArgs>
}
export type GuideStepIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  guide?: boolean | Prisma.GuideDefaultArgs<ExtArgs>
}

export type $GuideStepPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GuideStep"
  objects: {
    guide: Prisma.$GuidePayload<ExtArgs>
    sessions: Prisma.$SessionPayload<ExtArgs>[]
    sessionSteps: Prisma.$SessionStepPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    guideId: number
    index: number
    name: string
    instructions: string | null
    example: string | null
    amtOfResourcePerStep: string | null
  }, ExtArgs["result"]["guideStep"]>
  composites: {}
}

export type GuideStepGetPayload<S extends boolean | null | undefined | GuideStepDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GuideStepPayload, S>

export type GuideStepCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GuideStepFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GuideStepCountAggregateInputType | true
  }

export interface GuideStepDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GuideStep'], meta: { name: 'GuideStep' } }
  /**
   * Find zero or one GuideStep that matches the filter.
   * @param {GuideStepFindUniqueArgs} args - Arguments to find a GuideStep
   * @example
   * // Get one GuideStep
   * const guideStep = await prisma.guideStep.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GuideStepFindUniqueArgs>(args: Prisma.SelectSubset<T, GuideStepFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GuideStepClient<runtime.Types.Result.GetResult<Prisma.$GuideStepPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GuideStep that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GuideStepFindUniqueOrThrowArgs} args - Arguments to find a GuideStep
   * @example
   * // Get one GuideStep
   * const guideStep = await prisma.guideStep.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GuideStepFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GuideStepFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GuideStepClient<runtime.Types.Result.GetResult<Prisma.$GuideStepPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GuideStep that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuideStepFindFirstArgs} args - Arguments to find a GuideStep
   * @example
   * // Get one GuideStep
   * const guideStep = await prisma.guideStep.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GuideStepFindFirstArgs>(args?: Prisma.SelectSubset<T, GuideStepFindFirstArgs<ExtArgs>>): Prisma.Prisma__GuideStepClient<runtime.Types.Result.GetResult<Prisma.$GuideStepPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GuideStep that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuideStepFindFirstOrThrowArgs} args - Arguments to find a GuideStep
   * @example
   * // Get one GuideStep
   * const guideStep = await prisma.guideStep.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GuideStepFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GuideStepFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GuideStepClient<runtime.Types.Result.GetResult<Prisma.$GuideStepPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GuideSteps that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuideStepFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GuideSteps
   * const guideSteps = await prisma.guideStep.findMany()
   * 
   * // Get first 10 GuideSteps
   * const guideSteps = await prisma.guideStep.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const guideStepWithIdOnly = await prisma.guideStep.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GuideStepFindManyArgs>(args?: Prisma.SelectSubset<T, GuideStepFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuideStepPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GuideStep.
   * @param {GuideStepCreateArgs} args - Arguments to create a GuideStep.
   * @example
   * // Create one GuideStep
   * const GuideStep = await prisma.guideStep.create({
   *   data: {
   *     // ... data to create a GuideStep
   *   }
   * })
   * 
   */
  create<T extends GuideStepCreateArgs>(args: Prisma.SelectSubset<T, GuideStepCreateArgs<ExtArgs>>): Prisma.Prisma__GuideStepClient<runtime.Types.Result.GetResult<Prisma.$GuideStepPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GuideSteps.
   * @param {GuideStepCreateManyArgs} args - Arguments to create many GuideSteps.
   * @example
   * // Create many GuideSteps
   * const guideStep = await prisma.guideStep.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GuideStepCreateManyArgs>(args?: Prisma.SelectSubset<T, GuideStepCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many GuideSteps and returns the data saved in the database.
   * @param {GuideStepCreateManyAndReturnArgs} args - Arguments to create many GuideSteps.
   * @example
   * // Create many GuideSteps
   * const guideStep = await prisma.guideStep.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many GuideSteps and only return the `id`
   * const guideStepWithIdOnly = await prisma.guideStep.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GuideStepCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GuideStepCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuideStepPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a GuideStep.
   * @param {GuideStepDeleteArgs} args - Arguments to delete one GuideStep.
   * @example
   * // Delete one GuideStep
   * const GuideStep = await prisma.guideStep.delete({
   *   where: {
   *     // ... filter to delete one GuideStep
   *   }
   * })
   * 
   */
  delete<T extends GuideStepDeleteArgs>(args: Prisma.SelectSubset<T, GuideStepDeleteArgs<ExtArgs>>): Prisma.Prisma__GuideStepClient<runtime.Types.Result.GetResult<Prisma.$GuideStepPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GuideStep.
   * @param {GuideStepUpdateArgs} args - Arguments to update one GuideStep.
   * @example
   * // Update one GuideStep
   * const guideStep = await prisma.guideStep.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GuideStepUpdateArgs>(args: Prisma.SelectSubset<T, GuideStepUpdateArgs<ExtArgs>>): Prisma.Prisma__GuideStepClient<runtime.Types.Result.GetResult<Prisma.$GuideStepPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GuideSteps.
   * @param {GuideStepDeleteManyArgs} args - Arguments to filter GuideSteps to delete.
   * @example
   * // Delete a few GuideSteps
   * const { count } = await prisma.guideStep.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GuideStepDeleteManyArgs>(args?: Prisma.SelectSubset<T, GuideStepDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GuideSteps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuideStepUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GuideSteps
   * const guideStep = await prisma.guideStep.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GuideStepUpdateManyArgs>(args: Prisma.SelectSubset<T, GuideStepUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GuideSteps and returns the data updated in the database.
   * @param {GuideStepUpdateManyAndReturnArgs} args - Arguments to update many GuideSteps.
   * @example
   * // Update many GuideSteps
   * const guideStep = await prisma.guideStep.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more GuideSteps and only return the `id`
   * const guideStepWithIdOnly = await prisma.guideStep.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GuideStepUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GuideStepUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuideStepPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one GuideStep.
   * @param {GuideStepUpsertArgs} args - Arguments to update or create a GuideStep.
   * @example
   * // Update or create a GuideStep
   * const guideStep = await prisma.guideStep.upsert({
   *   create: {
   *     // ... data to create a GuideStep
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GuideStep we want to update
   *   }
   * })
   */
  upsert<T extends GuideStepUpsertArgs>(args: Prisma.SelectSubset<T, GuideStepUpsertArgs<ExtArgs>>): Prisma.Prisma__GuideStepClient<runtime.Types.Result.GetResult<Prisma.$GuideStepPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GuideSteps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuideStepCountArgs} args - Arguments to filter GuideSteps to count.
   * @example
   * // Count the number of GuideSteps
   * const count = await prisma.guideStep.count({
   *   where: {
   *     // ... the filter for the GuideSteps we want to count
   *   }
   * })
  **/
  count<T extends GuideStepCountArgs>(
    args?: Prisma.Subset<T, GuideStepCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GuideStepCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GuideStep.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuideStepAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GuideStepAggregateArgs>(args: Prisma.Subset<T, GuideStepAggregateArgs>): Prisma.PrismaPromise<GetGuideStepAggregateType<T>>

  /**
   * Group by GuideStep.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuideStepGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GuideStepGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GuideStepGroupByArgs['orderBy'] }
      : { orderBy?: GuideStepGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GuideStepGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGuideStepGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GuideStep model
 */
readonly fields: GuideStepFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GuideStep.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GuideStepClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  guide<T extends Prisma.GuideDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GuideDefaultArgs<ExtArgs>>): Prisma.Prisma__GuideClient<runtime.Types.Result.GetResult<Prisma.$GuidePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  sessions<T extends Prisma.GuideStep$sessionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GuideStep$sessionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  sessionSteps<T extends Prisma.GuideStep$sessionStepsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GuideStep$sessionStepsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionStepPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GuideStep model
 */
export interface GuideStepFieldRefs {
  readonly id: Prisma.FieldRef<"GuideStep", 'Int'>
  readonly guideId: Prisma.FieldRef<"GuideStep", 'Int'>
  readonly index: Prisma.FieldRef<"GuideStep", 'Int'>
  readonly name: Prisma.FieldRef<"GuideStep", 'String'>
  readonly instructions: Prisma.FieldRef<"GuideStep", 'String'>
  readonly example: Prisma.FieldRef<"GuideStep", 'String'>
  readonly amtOfResourcePerStep: Prisma.FieldRef<"GuideStep", 'String'>
}
    

// Custom InputTypes
/**
 * GuideStep findUnique
 */
export type GuideStepFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideStep
   */
  select?: Prisma.GuideStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideStep
   */
  omit?: Prisma.GuideStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideStepInclude<ExtArgs> | null
  /**
   * Filter, which GuideStep to fetch.
   */
  where: Prisma.GuideStepWhereUniqueInput
}

/**
 * GuideStep findUniqueOrThrow
 */
export type GuideStepFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideStep
   */
  select?: Prisma.GuideStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideStep
   */
  omit?: Prisma.GuideStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideStepInclude<ExtArgs> | null
  /**
   * Filter, which GuideStep to fetch.
   */
  where: Prisma.GuideStepWhereUniqueInput
}

/**
 * GuideStep findFirst
 */
export type GuideStepFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideStep
   */
  select?: Prisma.GuideStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideStep
   */
  omit?: Prisma.GuideStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideStepInclude<ExtArgs> | null
  /**
   * Filter, which GuideStep to fetch.
   */
  where?: Prisma.GuideStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuideSteps to fetch.
   */
  orderBy?: Prisma.GuideStepOrderByWithRelationInput | Prisma.GuideStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GuideSteps.
   */
  cursor?: Prisma.GuideStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuideSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuideSteps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GuideSteps.
   */
  distinct?: Prisma.GuideStepScalarFieldEnum | Prisma.GuideStepScalarFieldEnum[]
}

/**
 * GuideStep findFirstOrThrow
 */
export type GuideStepFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideStep
   */
  select?: Prisma.GuideStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideStep
   */
  omit?: Prisma.GuideStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideStepInclude<ExtArgs> | null
  /**
   * Filter, which GuideStep to fetch.
   */
  where?: Prisma.GuideStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuideSteps to fetch.
   */
  orderBy?: Prisma.GuideStepOrderByWithRelationInput | Prisma.GuideStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GuideSteps.
   */
  cursor?: Prisma.GuideStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuideSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuideSteps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GuideSteps.
   */
  distinct?: Prisma.GuideStepScalarFieldEnum | Prisma.GuideStepScalarFieldEnum[]
}

/**
 * GuideStep findMany
 */
export type GuideStepFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideStep
   */
  select?: Prisma.GuideStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideStep
   */
  omit?: Prisma.GuideStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideStepInclude<ExtArgs> | null
  /**
   * Filter, which GuideSteps to fetch.
   */
  where?: Prisma.GuideStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuideSteps to fetch.
   */
  orderBy?: Prisma.GuideStepOrderByWithRelationInput | Prisma.GuideStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GuideSteps.
   */
  cursor?: Prisma.GuideStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuideSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuideSteps.
   */
  skip?: number
  distinct?: Prisma.GuideStepScalarFieldEnum | Prisma.GuideStepScalarFieldEnum[]
}

/**
 * GuideStep create
 */
export type GuideStepCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideStep
   */
  select?: Prisma.GuideStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideStep
   */
  omit?: Prisma.GuideStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideStepInclude<ExtArgs> | null
  /**
   * The data needed to create a GuideStep.
   */
  data: Prisma.XOR<Prisma.GuideStepCreateInput, Prisma.GuideStepUncheckedCreateInput>
}

/**
 * GuideStep createMany
 */
export type GuideStepCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GuideSteps.
   */
  data: Prisma.GuideStepCreateManyInput | Prisma.GuideStepCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * GuideStep createManyAndReturn
 */
export type GuideStepCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideStep
   */
  select?: Prisma.GuideStepSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GuideStep
   */
  omit?: Prisma.GuideStepOmit<ExtArgs> | null
  /**
   * The data used to create many GuideSteps.
   */
  data: Prisma.GuideStepCreateManyInput | Prisma.GuideStepCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideStepIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * GuideStep update
 */
export type GuideStepUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideStep
   */
  select?: Prisma.GuideStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideStep
   */
  omit?: Prisma.GuideStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideStepInclude<ExtArgs> | null
  /**
   * The data needed to update a GuideStep.
   */
  data: Prisma.XOR<Prisma.GuideStepUpdateInput, Prisma.GuideStepUncheckedUpdateInput>
  /**
   * Choose, which GuideStep to update.
   */
  where: Prisma.GuideStepWhereUniqueInput
}

/**
 * GuideStep updateMany
 */
export type GuideStepUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GuideSteps.
   */
  data: Prisma.XOR<Prisma.GuideStepUpdateManyMutationInput, Prisma.GuideStepUncheckedUpdateManyInput>
  /**
   * Filter which GuideSteps to update
   */
  where?: Prisma.GuideStepWhereInput
  /**
   * Limit how many GuideSteps to update.
   */
  limit?: number
}

/**
 * GuideStep updateManyAndReturn
 */
export type GuideStepUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideStep
   */
  select?: Prisma.GuideStepSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GuideStep
   */
  omit?: Prisma.GuideStepOmit<ExtArgs> | null
  /**
   * The data used to update GuideSteps.
   */
  data: Prisma.XOR<Prisma.GuideStepUpdateManyMutationInput, Prisma.GuideStepUncheckedUpdateManyInput>
  /**
   * Filter which GuideSteps to update
   */
  where?: Prisma.GuideStepWhereInput
  /**
   * Limit how many GuideSteps to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideStepIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * GuideStep upsert
 */
export type GuideStepUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideStep
   */
  select?: Prisma.GuideStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideStep
   */
  omit?: Prisma.GuideStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideStepInclude<ExtArgs> | null
  /**
   * The filter to search for the GuideStep to update in case it exists.
   */
  where: Prisma.GuideStepWhereUniqueInput
  /**
   * In case the GuideStep found by the `where` argument doesn't exist, create a new GuideStep with this data.
   */
  create: Prisma.XOR<Prisma.GuideStepCreateInput, Prisma.GuideStepUncheckedCreateInput>
  /**
   * In case the GuideStep was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GuideStepUpdateInput, Prisma.GuideStepUncheckedUpdateInput>
}

/**
 * GuideStep delete
 */
export type GuideStepDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideStep
   */
  select?: Prisma.GuideStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideStep
   */
  omit?: Prisma.GuideStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideStepInclude<ExtArgs> | null
  /**
   * Filter which GuideStep to delete.
   */
  where: Prisma.GuideStepWhereUniqueInput
}

/**
 * GuideStep deleteMany
 */
export type GuideStepDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GuideSteps to delete
   */
  where?: Prisma.GuideStepWhereInput
  /**
   * Limit how many GuideSteps to delete.
   */
  limit?: number
}

/**
 * GuideStep.sessions
 */
export type GuideStep$sessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  where?: Prisma.SessionWhereInput
  orderBy?: Prisma.SessionOrderByWithRelationInput | Prisma.SessionOrderByWithRelationInput[]
  cursor?: Prisma.SessionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SessionScalarFieldEnum | Prisma.SessionScalarFieldEnum[]
}

/**
 * GuideStep.sessionSteps
 */
export type GuideStep$sessionStepsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionStep
   */
  select?: Prisma.SessionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionStep
   */
  omit?: Prisma.SessionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionStepInclude<ExtArgs> | null
  where?: Prisma.SessionStepWhereInput
  orderBy?: Prisma.SessionStepOrderByWithRelationInput | Prisma.SessionStepOrderByWithRelationInput[]
  cursor?: Prisma.SessionStepWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SessionStepScalarFieldEnum | Prisma.SessionStepScalarFieldEnum[]
}

/**
 * GuideStep without action
 */
export type GuideStepDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideStep
   */
  select?: Prisma.GuideStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideStep
   */
  omit?: Prisma.GuideStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideStepInclude<ExtArgs> | null
}
