
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Selection` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Selection
 * 
 */
export type SelectionModel = runtime.Types.Result.DefaultSelection<Prisma.$SelectionPayload>

export type AggregateSelection = {
  _count: SelectionCountAggregateOutputType | null
  _avg: SelectionAvgAggregateOutputType | null
  _sum: SelectionSumAggregateOutputType | null
  _min: SelectionMinAggregateOutputType | null
  _max: SelectionMaxAggregateOutputType | null
}

export type SelectionAvgAggregateOutputType = {
  id: number | null
  resourceId: number | null
  startChapterId: number | null
  endChapterId: number | null
  startVerseId: number | null
  endVerseId: number | null
}

export type SelectionSumAggregateOutputType = {
  id: number | null
  resourceId: number | null
  startChapterId: number | null
  endChapterId: number | null
  startVerseId: number | null
  endVerseId: number | null
}

export type SelectionMinAggregateOutputType = {
  id: number | null
  resourceId: number | null
  startChapterId: number | null
  endChapterId: number | null
  startVerseId: number | null
  endVerseId: number | null
}

export type SelectionMaxAggregateOutputType = {
  id: number | null
  resourceId: number | null
  startChapterId: number | null
  endChapterId: number | null
  startVerseId: number | null
  endVerseId: number | null
}

export type SelectionCountAggregateOutputType = {
  id: number
  resourceId: number
  startChapterId: number
  endChapterId: number
  startVerseId: number
  endVerseId: number
  _all: number
}


export type SelectionAvgAggregateInputType = {
  id?: true
  resourceId?: true
  startChapterId?: true
  endChapterId?: true
  startVerseId?: true
  endVerseId?: true
}

export type SelectionSumAggregateInputType = {
  id?: true
  resourceId?: true
  startChapterId?: true
  endChapterId?: true
  startVerseId?: true
  endVerseId?: true
}

export type SelectionMinAggregateInputType = {
  id?: true
  resourceId?: true
  startChapterId?: true
  endChapterId?: true
  startVerseId?: true
  endVerseId?: true
}

export type SelectionMaxAggregateInputType = {
  id?: true
  resourceId?: true
  startChapterId?: true
  endChapterId?: true
  startVerseId?: true
  endVerseId?: true
}

export type SelectionCountAggregateInputType = {
  id?: true
  resourceId?: true
  startChapterId?: true
  endChapterId?: true
  startVerseId?: true
  endVerseId?: true
  _all?: true
}

export type SelectionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Selection to aggregate.
   */
  where?: Prisma.SelectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Selections to fetch.
   */
  orderBy?: Prisma.SelectionOrderByWithRelationInput | Prisma.SelectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SelectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Selections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Selections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Selections
  **/
  _count?: true | SelectionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SelectionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SelectionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SelectionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SelectionMaxAggregateInputType
}

export type GetSelectionAggregateType<T extends SelectionAggregateArgs> = {
      [P in keyof T & keyof AggregateSelection]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSelection[P]>
    : Prisma.GetScalarType<T[P], AggregateSelection[P]>
}




export type SelectionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SelectionWhereInput
  orderBy?: Prisma.SelectionOrderByWithAggregationInput | Prisma.SelectionOrderByWithAggregationInput[]
  by: Prisma.SelectionScalarFieldEnum[] | Prisma.SelectionScalarFieldEnum
  having?: Prisma.SelectionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SelectionCountAggregateInputType | true
  _avg?: SelectionAvgAggregateInputType
  _sum?: SelectionSumAggregateInputType
  _min?: SelectionMinAggregateInputType
  _max?: SelectionMaxAggregateInputType
}

export type SelectionGroupByOutputType = {
  id: number
  resourceId: number
  startChapterId: number | null
  endChapterId: number | null
  startVerseId: number | null
  endVerseId: number | null
  _count: SelectionCountAggregateOutputType | null
  _avg: SelectionAvgAggregateOutputType | null
  _sum: SelectionSumAggregateOutputType | null
  _min: SelectionMinAggregateOutputType | null
  _max: SelectionMaxAggregateOutputType | null
}

type GetSelectionGroupByPayload<T extends SelectionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SelectionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SelectionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SelectionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SelectionGroupByOutputType[P]>
      }
    >
  >



export type SelectionWhereInput = {
  AND?: Prisma.SelectionWhereInput | Prisma.SelectionWhereInput[]
  OR?: Prisma.SelectionWhereInput[]
  NOT?: Prisma.SelectionWhereInput | Prisma.SelectionWhereInput[]
  id?: Prisma.IntFilter<"Selection"> | number
  resourceId?: Prisma.IntFilter<"Selection"> | number
  startChapterId?: Prisma.IntNullableFilter<"Selection"> | number | null
  endChapterId?: Prisma.IntNullableFilter<"Selection"> | number | null
  startVerseId?: Prisma.IntNullableFilter<"Selection"> | number | null
  endVerseId?: Prisma.IntNullableFilter<"Selection"> | number | null
  resource?: Prisma.XOR<Prisma.ResourceScalarRelationFilter, Prisma.ResourceWhereInput>
  startChapter?: Prisma.XOR<Prisma.ChapterNullableScalarRelationFilter, Prisma.ChapterWhereInput> | null
  endChapter?: Prisma.XOR<Prisma.ChapterNullableScalarRelationFilter, Prisma.ChapterWhereInput> | null
  startVerse?: Prisma.XOR<Prisma.VerseNullableScalarRelationFilter, Prisma.VerseWhereInput> | null
  endVerse?: Prisma.XOR<Prisma.VerseNullableScalarRelationFilter, Prisma.VerseWhereInput> | null
  sessions?: Prisma.SessionListRelationFilter
}

export type SelectionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  startChapterId?: Prisma.SortOrderInput | Prisma.SortOrder
  endChapterId?: Prisma.SortOrderInput | Prisma.SortOrder
  startVerseId?: Prisma.SortOrderInput | Prisma.SortOrder
  endVerseId?: Prisma.SortOrderInput | Prisma.SortOrder
  resource?: Prisma.ResourceOrderByWithRelationInput
  startChapter?: Prisma.ChapterOrderByWithRelationInput
  endChapter?: Prisma.ChapterOrderByWithRelationInput
  startVerse?: Prisma.VerseOrderByWithRelationInput
  endVerse?: Prisma.VerseOrderByWithRelationInput
  sessions?: Prisma.SessionOrderByRelationAggregateInput
}

export type SelectionWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.SelectionWhereInput | Prisma.SelectionWhereInput[]
  OR?: Prisma.SelectionWhereInput[]
  NOT?: Prisma.SelectionWhereInput | Prisma.SelectionWhereInput[]
  resourceId?: Prisma.IntFilter<"Selection"> | number
  startChapterId?: Prisma.IntNullableFilter<"Selection"> | number | null
  endChapterId?: Prisma.IntNullableFilter<"Selection"> | number | null
  startVerseId?: Prisma.IntNullableFilter<"Selection"> | number | null
  endVerseId?: Prisma.IntNullableFilter<"Selection"> | number | null
  resource?: Prisma.XOR<Prisma.ResourceScalarRelationFilter, Prisma.ResourceWhereInput>
  startChapter?: Prisma.XOR<Prisma.ChapterNullableScalarRelationFilter, Prisma.ChapterWhereInput> | null
  endChapter?: Prisma.XOR<Prisma.ChapterNullableScalarRelationFilter, Prisma.ChapterWhereInput> | null
  startVerse?: Prisma.XOR<Prisma.VerseNullableScalarRelationFilter, Prisma.VerseWhereInput> | null
  endVerse?: Prisma.XOR<Prisma.VerseNullableScalarRelationFilter, Prisma.VerseWhereInput> | null
  sessions?: Prisma.SessionListRelationFilter
}, "id">

export type SelectionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  startChapterId?: Prisma.SortOrderInput | Prisma.SortOrder
  endChapterId?: Prisma.SortOrderInput | Prisma.SortOrder
  startVerseId?: Prisma.SortOrderInput | Prisma.SortOrder
  endVerseId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.SelectionCountOrderByAggregateInput
  _avg?: Prisma.SelectionAvgOrderByAggregateInput
  _max?: Prisma.SelectionMaxOrderByAggregateInput
  _min?: Prisma.SelectionMinOrderByAggregateInput
  _sum?: Prisma.SelectionSumOrderByAggregateInput
}

export type SelectionScalarWhereWithAggregatesInput = {
  AND?: Prisma.SelectionScalarWhereWithAggregatesInput | Prisma.SelectionScalarWhereWithAggregatesInput[]
  OR?: Prisma.SelectionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SelectionScalarWhereWithAggregatesInput | Prisma.SelectionScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Selection"> | number
  resourceId?: Prisma.IntWithAggregatesFilter<"Selection"> | number
  startChapterId?: Prisma.IntNullableWithAggregatesFilter<"Selection"> | number | null
  endChapterId?: Prisma.IntNullableWithAggregatesFilter<"Selection"> | number | null
  startVerseId?: Prisma.IntNullableWithAggregatesFilter<"Selection"> | number | null
  endVerseId?: Prisma.IntNullableWithAggregatesFilter<"Selection"> | number | null
}

export type SelectionCreateInput = {
  resource: Prisma.ResourceCreateNestedOneWithoutSelectionsInput
  startChapter?: Prisma.ChapterCreateNestedOneWithoutStartSelectionsInput
  endChapter?: Prisma.ChapterCreateNestedOneWithoutEndSelectionsInput
  startVerse?: Prisma.VerseCreateNestedOneWithoutStartSelectionsInput
  endVerse?: Prisma.VerseCreateNestedOneWithoutEndSelectionsInput
  sessions?: Prisma.SessionCreateNestedManyWithoutSelectionInput
}

export type SelectionUncheckedCreateInput = {
  id?: number
  resourceId: number
  startChapterId?: number | null
  endChapterId?: number | null
  startVerseId?: number | null
  endVerseId?: number | null
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutSelectionInput
}

export type SelectionUpdateInput = {
  resource?: Prisma.ResourceUpdateOneRequiredWithoutSelectionsNestedInput
  startChapter?: Prisma.ChapterUpdateOneWithoutStartSelectionsNestedInput
  endChapter?: Prisma.ChapterUpdateOneWithoutEndSelectionsNestedInput
  startVerse?: Prisma.VerseUpdateOneWithoutStartSelectionsNestedInput
  endVerse?: Prisma.VerseUpdateOneWithoutEndSelectionsNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutSelectionNestedInput
}

export type SelectionUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resourceId?: Prisma.IntFieldUpdateOperationsInput | number
  startChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  startVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutSelectionNestedInput
}

export type SelectionCreateManyInput = {
  id?: number
  resourceId: number
  startChapterId?: number | null
  endChapterId?: number | null
  startVerseId?: number | null
  endVerseId?: number | null
}

export type SelectionUpdateManyMutationInput = {

}

export type SelectionUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resourceId?: Prisma.IntFieldUpdateOperationsInput | number
  startChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  startVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type SelectionListRelationFilter = {
  every?: Prisma.SelectionWhereInput
  some?: Prisma.SelectionWhereInput
  none?: Prisma.SelectionWhereInput
}

export type SelectionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SelectionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  startChapterId?: Prisma.SortOrder
  endChapterId?: Prisma.SortOrder
  startVerseId?: Prisma.SortOrder
  endVerseId?: Prisma.SortOrder
}

export type SelectionAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  startChapterId?: Prisma.SortOrder
  endChapterId?: Prisma.SortOrder
  startVerseId?: Prisma.SortOrder
  endVerseId?: Prisma.SortOrder
}

export type SelectionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  startChapterId?: Prisma.SortOrder
  endChapterId?: Prisma.SortOrder
  startVerseId?: Prisma.SortOrder
  endVerseId?: Prisma.SortOrder
}

export type SelectionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  startChapterId?: Prisma.SortOrder
  endChapterId?: Prisma.SortOrder
  startVerseId?: Prisma.SortOrder
  endVerseId?: Prisma.SortOrder
}

export type SelectionSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resourceId?: Prisma.SortOrder
  startChapterId?: Prisma.SortOrder
  endChapterId?: Prisma.SortOrder
  startVerseId?: Prisma.SortOrder
  endVerseId?: Prisma.SortOrder
}

export type SelectionNullableScalarRelationFilter = {
  is?: Prisma.SelectionWhereInput | null
  isNot?: Prisma.SelectionWhereInput | null
}

export type SelectionCreateNestedManyWithoutResourceInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutResourceInput, Prisma.SelectionUncheckedCreateWithoutResourceInput> | Prisma.SelectionCreateWithoutResourceInput[] | Prisma.SelectionUncheckedCreateWithoutResourceInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutResourceInput | Prisma.SelectionCreateOrConnectWithoutResourceInput[]
  createMany?: Prisma.SelectionCreateManyResourceInputEnvelope
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
}

export type SelectionUncheckedCreateNestedManyWithoutResourceInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutResourceInput, Prisma.SelectionUncheckedCreateWithoutResourceInput> | Prisma.SelectionCreateWithoutResourceInput[] | Prisma.SelectionUncheckedCreateWithoutResourceInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutResourceInput | Prisma.SelectionCreateOrConnectWithoutResourceInput[]
  createMany?: Prisma.SelectionCreateManyResourceInputEnvelope
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
}

export type SelectionUpdateManyWithoutResourceNestedInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutResourceInput, Prisma.SelectionUncheckedCreateWithoutResourceInput> | Prisma.SelectionCreateWithoutResourceInput[] | Prisma.SelectionUncheckedCreateWithoutResourceInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutResourceInput | Prisma.SelectionCreateOrConnectWithoutResourceInput[]
  upsert?: Prisma.SelectionUpsertWithWhereUniqueWithoutResourceInput | Prisma.SelectionUpsertWithWhereUniqueWithoutResourceInput[]
  createMany?: Prisma.SelectionCreateManyResourceInputEnvelope
  set?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  disconnect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  delete?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  update?: Prisma.SelectionUpdateWithWhereUniqueWithoutResourceInput | Prisma.SelectionUpdateWithWhereUniqueWithoutResourceInput[]
  updateMany?: Prisma.SelectionUpdateManyWithWhereWithoutResourceInput | Prisma.SelectionUpdateManyWithWhereWithoutResourceInput[]
  deleteMany?: Prisma.SelectionScalarWhereInput | Prisma.SelectionScalarWhereInput[]
}

export type SelectionUncheckedUpdateManyWithoutResourceNestedInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutResourceInput, Prisma.SelectionUncheckedCreateWithoutResourceInput> | Prisma.SelectionCreateWithoutResourceInput[] | Prisma.SelectionUncheckedCreateWithoutResourceInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutResourceInput | Prisma.SelectionCreateOrConnectWithoutResourceInput[]
  upsert?: Prisma.SelectionUpsertWithWhereUniqueWithoutResourceInput | Prisma.SelectionUpsertWithWhereUniqueWithoutResourceInput[]
  createMany?: Prisma.SelectionCreateManyResourceInputEnvelope
  set?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  disconnect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  delete?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  update?: Prisma.SelectionUpdateWithWhereUniqueWithoutResourceInput | Prisma.SelectionUpdateWithWhereUniqueWithoutResourceInput[]
  updateMany?: Prisma.SelectionUpdateManyWithWhereWithoutResourceInput | Prisma.SelectionUpdateManyWithWhereWithoutResourceInput[]
  deleteMany?: Prisma.SelectionScalarWhereInput | Prisma.SelectionScalarWhereInput[]
}

export type SelectionCreateNestedManyWithoutStartChapterInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutStartChapterInput, Prisma.SelectionUncheckedCreateWithoutStartChapterInput> | Prisma.SelectionCreateWithoutStartChapterInput[] | Prisma.SelectionUncheckedCreateWithoutStartChapterInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutStartChapterInput | Prisma.SelectionCreateOrConnectWithoutStartChapterInput[]
  createMany?: Prisma.SelectionCreateManyStartChapterInputEnvelope
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
}

export type SelectionCreateNestedManyWithoutEndChapterInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutEndChapterInput, Prisma.SelectionUncheckedCreateWithoutEndChapterInput> | Prisma.SelectionCreateWithoutEndChapterInput[] | Prisma.SelectionUncheckedCreateWithoutEndChapterInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutEndChapterInput | Prisma.SelectionCreateOrConnectWithoutEndChapterInput[]
  createMany?: Prisma.SelectionCreateManyEndChapterInputEnvelope
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
}

export type SelectionUncheckedCreateNestedManyWithoutStartChapterInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutStartChapterInput, Prisma.SelectionUncheckedCreateWithoutStartChapterInput> | Prisma.SelectionCreateWithoutStartChapterInput[] | Prisma.SelectionUncheckedCreateWithoutStartChapterInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutStartChapterInput | Prisma.SelectionCreateOrConnectWithoutStartChapterInput[]
  createMany?: Prisma.SelectionCreateManyStartChapterInputEnvelope
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
}

export type SelectionUncheckedCreateNestedManyWithoutEndChapterInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutEndChapterInput, Prisma.SelectionUncheckedCreateWithoutEndChapterInput> | Prisma.SelectionCreateWithoutEndChapterInput[] | Prisma.SelectionUncheckedCreateWithoutEndChapterInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutEndChapterInput | Prisma.SelectionCreateOrConnectWithoutEndChapterInput[]
  createMany?: Prisma.SelectionCreateManyEndChapterInputEnvelope
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
}

export type SelectionUpdateManyWithoutStartChapterNestedInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutStartChapterInput, Prisma.SelectionUncheckedCreateWithoutStartChapterInput> | Prisma.SelectionCreateWithoutStartChapterInput[] | Prisma.SelectionUncheckedCreateWithoutStartChapterInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutStartChapterInput | Prisma.SelectionCreateOrConnectWithoutStartChapterInput[]
  upsert?: Prisma.SelectionUpsertWithWhereUniqueWithoutStartChapterInput | Prisma.SelectionUpsertWithWhereUniqueWithoutStartChapterInput[]
  createMany?: Prisma.SelectionCreateManyStartChapterInputEnvelope
  set?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  disconnect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  delete?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  update?: Prisma.SelectionUpdateWithWhereUniqueWithoutStartChapterInput | Prisma.SelectionUpdateWithWhereUniqueWithoutStartChapterInput[]
  updateMany?: Prisma.SelectionUpdateManyWithWhereWithoutStartChapterInput | Prisma.SelectionUpdateManyWithWhereWithoutStartChapterInput[]
  deleteMany?: Prisma.SelectionScalarWhereInput | Prisma.SelectionScalarWhereInput[]
}

export type SelectionUpdateManyWithoutEndChapterNestedInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutEndChapterInput, Prisma.SelectionUncheckedCreateWithoutEndChapterInput> | Prisma.SelectionCreateWithoutEndChapterInput[] | Prisma.SelectionUncheckedCreateWithoutEndChapterInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutEndChapterInput | Prisma.SelectionCreateOrConnectWithoutEndChapterInput[]
  upsert?: Prisma.SelectionUpsertWithWhereUniqueWithoutEndChapterInput | Prisma.SelectionUpsertWithWhereUniqueWithoutEndChapterInput[]
  createMany?: Prisma.SelectionCreateManyEndChapterInputEnvelope
  set?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  disconnect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  delete?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  update?: Prisma.SelectionUpdateWithWhereUniqueWithoutEndChapterInput | Prisma.SelectionUpdateWithWhereUniqueWithoutEndChapterInput[]
  updateMany?: Prisma.SelectionUpdateManyWithWhereWithoutEndChapterInput | Prisma.SelectionUpdateManyWithWhereWithoutEndChapterInput[]
  deleteMany?: Prisma.SelectionScalarWhereInput | Prisma.SelectionScalarWhereInput[]
}

export type SelectionUncheckedUpdateManyWithoutStartChapterNestedInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutStartChapterInput, Prisma.SelectionUncheckedCreateWithoutStartChapterInput> | Prisma.SelectionCreateWithoutStartChapterInput[] | Prisma.SelectionUncheckedCreateWithoutStartChapterInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutStartChapterInput | Prisma.SelectionCreateOrConnectWithoutStartChapterInput[]
  upsert?: Prisma.SelectionUpsertWithWhereUniqueWithoutStartChapterInput | Prisma.SelectionUpsertWithWhereUniqueWithoutStartChapterInput[]
  createMany?: Prisma.SelectionCreateManyStartChapterInputEnvelope
  set?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  disconnect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  delete?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  update?: Prisma.SelectionUpdateWithWhereUniqueWithoutStartChapterInput | Prisma.SelectionUpdateWithWhereUniqueWithoutStartChapterInput[]
  updateMany?: Prisma.SelectionUpdateManyWithWhereWithoutStartChapterInput | Prisma.SelectionUpdateManyWithWhereWithoutStartChapterInput[]
  deleteMany?: Prisma.SelectionScalarWhereInput | Prisma.SelectionScalarWhereInput[]
}

export type SelectionUncheckedUpdateManyWithoutEndChapterNestedInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutEndChapterInput, Prisma.SelectionUncheckedCreateWithoutEndChapterInput> | Prisma.SelectionCreateWithoutEndChapterInput[] | Prisma.SelectionUncheckedCreateWithoutEndChapterInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutEndChapterInput | Prisma.SelectionCreateOrConnectWithoutEndChapterInput[]
  upsert?: Prisma.SelectionUpsertWithWhereUniqueWithoutEndChapterInput | Prisma.SelectionUpsertWithWhereUniqueWithoutEndChapterInput[]
  createMany?: Prisma.SelectionCreateManyEndChapterInputEnvelope
  set?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  disconnect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  delete?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  update?: Prisma.SelectionUpdateWithWhereUniqueWithoutEndChapterInput | Prisma.SelectionUpdateWithWhereUniqueWithoutEndChapterInput[]
  updateMany?: Prisma.SelectionUpdateManyWithWhereWithoutEndChapterInput | Prisma.SelectionUpdateManyWithWhereWithoutEndChapterInput[]
  deleteMany?: Prisma.SelectionScalarWhereInput | Prisma.SelectionScalarWhereInput[]
}

export type SelectionCreateNestedManyWithoutStartVerseInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutStartVerseInput, Prisma.SelectionUncheckedCreateWithoutStartVerseInput> | Prisma.SelectionCreateWithoutStartVerseInput[] | Prisma.SelectionUncheckedCreateWithoutStartVerseInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutStartVerseInput | Prisma.SelectionCreateOrConnectWithoutStartVerseInput[]
  createMany?: Prisma.SelectionCreateManyStartVerseInputEnvelope
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
}

export type SelectionCreateNestedManyWithoutEndVerseInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutEndVerseInput, Prisma.SelectionUncheckedCreateWithoutEndVerseInput> | Prisma.SelectionCreateWithoutEndVerseInput[] | Prisma.SelectionUncheckedCreateWithoutEndVerseInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutEndVerseInput | Prisma.SelectionCreateOrConnectWithoutEndVerseInput[]
  createMany?: Prisma.SelectionCreateManyEndVerseInputEnvelope
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
}

export type SelectionUncheckedCreateNestedManyWithoutStartVerseInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutStartVerseInput, Prisma.SelectionUncheckedCreateWithoutStartVerseInput> | Prisma.SelectionCreateWithoutStartVerseInput[] | Prisma.SelectionUncheckedCreateWithoutStartVerseInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutStartVerseInput | Prisma.SelectionCreateOrConnectWithoutStartVerseInput[]
  createMany?: Prisma.SelectionCreateManyStartVerseInputEnvelope
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
}

export type SelectionUncheckedCreateNestedManyWithoutEndVerseInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutEndVerseInput, Prisma.SelectionUncheckedCreateWithoutEndVerseInput> | Prisma.SelectionCreateWithoutEndVerseInput[] | Prisma.SelectionUncheckedCreateWithoutEndVerseInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutEndVerseInput | Prisma.SelectionCreateOrConnectWithoutEndVerseInput[]
  createMany?: Prisma.SelectionCreateManyEndVerseInputEnvelope
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
}

export type SelectionUpdateManyWithoutStartVerseNestedInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutStartVerseInput, Prisma.SelectionUncheckedCreateWithoutStartVerseInput> | Prisma.SelectionCreateWithoutStartVerseInput[] | Prisma.SelectionUncheckedCreateWithoutStartVerseInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutStartVerseInput | Prisma.SelectionCreateOrConnectWithoutStartVerseInput[]
  upsert?: Prisma.SelectionUpsertWithWhereUniqueWithoutStartVerseInput | Prisma.SelectionUpsertWithWhereUniqueWithoutStartVerseInput[]
  createMany?: Prisma.SelectionCreateManyStartVerseInputEnvelope
  set?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  disconnect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  delete?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  update?: Prisma.SelectionUpdateWithWhereUniqueWithoutStartVerseInput | Prisma.SelectionUpdateWithWhereUniqueWithoutStartVerseInput[]
  updateMany?: Prisma.SelectionUpdateManyWithWhereWithoutStartVerseInput | Prisma.SelectionUpdateManyWithWhereWithoutStartVerseInput[]
  deleteMany?: Prisma.SelectionScalarWhereInput | Prisma.SelectionScalarWhereInput[]
}

export type SelectionUpdateManyWithoutEndVerseNestedInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutEndVerseInput, Prisma.SelectionUncheckedCreateWithoutEndVerseInput> | Prisma.SelectionCreateWithoutEndVerseInput[] | Prisma.SelectionUncheckedCreateWithoutEndVerseInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutEndVerseInput | Prisma.SelectionCreateOrConnectWithoutEndVerseInput[]
  upsert?: Prisma.SelectionUpsertWithWhereUniqueWithoutEndVerseInput | Prisma.SelectionUpsertWithWhereUniqueWithoutEndVerseInput[]
  createMany?: Prisma.SelectionCreateManyEndVerseInputEnvelope
  set?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  disconnect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  delete?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  update?: Prisma.SelectionUpdateWithWhereUniqueWithoutEndVerseInput | Prisma.SelectionUpdateWithWhereUniqueWithoutEndVerseInput[]
  updateMany?: Prisma.SelectionUpdateManyWithWhereWithoutEndVerseInput | Prisma.SelectionUpdateManyWithWhereWithoutEndVerseInput[]
  deleteMany?: Prisma.SelectionScalarWhereInput | Prisma.SelectionScalarWhereInput[]
}

export type SelectionUncheckedUpdateManyWithoutStartVerseNestedInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutStartVerseInput, Prisma.SelectionUncheckedCreateWithoutStartVerseInput> | Prisma.SelectionCreateWithoutStartVerseInput[] | Prisma.SelectionUncheckedCreateWithoutStartVerseInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutStartVerseInput | Prisma.SelectionCreateOrConnectWithoutStartVerseInput[]
  upsert?: Prisma.SelectionUpsertWithWhereUniqueWithoutStartVerseInput | Prisma.SelectionUpsertWithWhereUniqueWithoutStartVerseInput[]
  createMany?: Prisma.SelectionCreateManyStartVerseInputEnvelope
  set?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  disconnect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  delete?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  update?: Prisma.SelectionUpdateWithWhereUniqueWithoutStartVerseInput | Prisma.SelectionUpdateWithWhereUniqueWithoutStartVerseInput[]
  updateMany?: Prisma.SelectionUpdateManyWithWhereWithoutStartVerseInput | Prisma.SelectionUpdateManyWithWhereWithoutStartVerseInput[]
  deleteMany?: Prisma.SelectionScalarWhereInput | Prisma.SelectionScalarWhereInput[]
}

export type SelectionUncheckedUpdateManyWithoutEndVerseNestedInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutEndVerseInput, Prisma.SelectionUncheckedCreateWithoutEndVerseInput> | Prisma.SelectionCreateWithoutEndVerseInput[] | Prisma.SelectionUncheckedCreateWithoutEndVerseInput[]
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutEndVerseInput | Prisma.SelectionCreateOrConnectWithoutEndVerseInput[]
  upsert?: Prisma.SelectionUpsertWithWhereUniqueWithoutEndVerseInput | Prisma.SelectionUpsertWithWhereUniqueWithoutEndVerseInput[]
  createMany?: Prisma.SelectionCreateManyEndVerseInputEnvelope
  set?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  disconnect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  delete?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  connect?: Prisma.SelectionWhereUniqueInput | Prisma.SelectionWhereUniqueInput[]
  update?: Prisma.SelectionUpdateWithWhereUniqueWithoutEndVerseInput | Prisma.SelectionUpdateWithWhereUniqueWithoutEndVerseInput[]
  updateMany?: Prisma.SelectionUpdateManyWithWhereWithoutEndVerseInput | Prisma.SelectionUpdateManyWithWhereWithoutEndVerseInput[]
  deleteMany?: Prisma.SelectionScalarWhereInput | Prisma.SelectionScalarWhereInput[]
}

export type SelectionCreateNestedOneWithoutSessionsInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutSessionsInput, Prisma.SelectionUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutSessionsInput
  connect?: Prisma.SelectionWhereUniqueInput
}

export type SelectionUpdateOneWithoutSessionsNestedInput = {
  create?: Prisma.XOR<Prisma.SelectionCreateWithoutSessionsInput, Prisma.SelectionUncheckedCreateWithoutSessionsInput>
  connectOrCreate?: Prisma.SelectionCreateOrConnectWithoutSessionsInput
  upsert?: Prisma.SelectionUpsertWithoutSessionsInput
  disconnect?: Prisma.SelectionWhereInput | boolean
  delete?: Prisma.SelectionWhereInput | boolean
  connect?: Prisma.SelectionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SelectionUpdateToOneWithWhereWithoutSessionsInput, Prisma.SelectionUpdateWithoutSessionsInput>, Prisma.SelectionUncheckedUpdateWithoutSessionsInput>
}

export type SelectionCreateWithoutResourceInput = {
  startChapter?: Prisma.ChapterCreateNestedOneWithoutStartSelectionsInput
  endChapter?: Prisma.ChapterCreateNestedOneWithoutEndSelectionsInput
  startVerse?: Prisma.VerseCreateNestedOneWithoutStartSelectionsInput
  endVerse?: Prisma.VerseCreateNestedOneWithoutEndSelectionsInput
  sessions?: Prisma.SessionCreateNestedManyWithoutSelectionInput
}

export type SelectionUncheckedCreateWithoutResourceInput = {
  id?: number
  startChapterId?: number | null
  endChapterId?: number | null
  startVerseId?: number | null
  endVerseId?: number | null
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutSelectionInput
}

export type SelectionCreateOrConnectWithoutResourceInput = {
  where: Prisma.SelectionWhereUniqueInput
  create: Prisma.XOR<Prisma.SelectionCreateWithoutResourceInput, Prisma.SelectionUncheckedCreateWithoutResourceInput>
}

export type SelectionCreateManyResourceInputEnvelope = {
  data: Prisma.SelectionCreateManyResourceInput | Prisma.SelectionCreateManyResourceInput[]
  skipDuplicates?: boolean
}

export type SelectionUpsertWithWhereUniqueWithoutResourceInput = {
  where: Prisma.SelectionWhereUniqueInput
  update: Prisma.XOR<Prisma.SelectionUpdateWithoutResourceInput, Prisma.SelectionUncheckedUpdateWithoutResourceInput>
  create: Prisma.XOR<Prisma.SelectionCreateWithoutResourceInput, Prisma.SelectionUncheckedCreateWithoutResourceInput>
}

export type SelectionUpdateWithWhereUniqueWithoutResourceInput = {
  where: Prisma.SelectionWhereUniqueInput
  data: Prisma.XOR<Prisma.SelectionUpdateWithoutResourceInput, Prisma.SelectionUncheckedUpdateWithoutResourceInput>
}

export type SelectionUpdateManyWithWhereWithoutResourceInput = {
  where: Prisma.SelectionScalarWhereInput
  data: Prisma.XOR<Prisma.SelectionUpdateManyMutationInput, Prisma.SelectionUncheckedUpdateManyWithoutResourceInput>
}

export type SelectionScalarWhereInput = {
  AND?: Prisma.SelectionScalarWhereInput | Prisma.SelectionScalarWhereInput[]
  OR?: Prisma.SelectionScalarWhereInput[]
  NOT?: Prisma.SelectionScalarWhereInput | Prisma.SelectionScalarWhereInput[]
  id?: Prisma.IntFilter<"Selection"> | number
  resourceId?: Prisma.IntFilter<"Selection"> | number
  startChapterId?: Prisma.IntNullableFilter<"Selection"> | number | null
  endChapterId?: Prisma.IntNullableFilter<"Selection"> | number | null
  startVerseId?: Prisma.IntNullableFilter<"Selection"> | number | null
  endVerseId?: Prisma.IntNullableFilter<"Selection"> | number | null
}

export type SelectionCreateWithoutStartChapterInput = {
  resource: Prisma.ResourceCreateNestedOneWithoutSelectionsInput
  endChapter?: Prisma.ChapterCreateNestedOneWithoutEndSelectionsInput
  startVerse?: Prisma.VerseCreateNestedOneWithoutStartSelectionsInput
  endVerse?: Prisma.VerseCreateNestedOneWithoutEndSelectionsInput
  sessions?: Prisma.SessionCreateNestedManyWithoutSelectionInput
}

export type SelectionUncheckedCreateWithoutStartChapterInput = {
  id?: number
  resourceId: number
  endChapterId?: number | null
  startVerseId?: number | null
  endVerseId?: number | null
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutSelectionInput
}

export type SelectionCreateOrConnectWithoutStartChapterInput = {
  where: Prisma.SelectionWhereUniqueInput
  create: Prisma.XOR<Prisma.SelectionCreateWithoutStartChapterInput, Prisma.SelectionUncheckedCreateWithoutStartChapterInput>
}

export type SelectionCreateManyStartChapterInputEnvelope = {
  data: Prisma.SelectionCreateManyStartChapterInput | Prisma.SelectionCreateManyStartChapterInput[]
  skipDuplicates?: boolean
}

export type SelectionCreateWithoutEndChapterInput = {
  resource: Prisma.ResourceCreateNestedOneWithoutSelectionsInput
  startChapter?: Prisma.ChapterCreateNestedOneWithoutStartSelectionsInput
  startVerse?: Prisma.VerseCreateNestedOneWithoutStartSelectionsInput
  endVerse?: Prisma.VerseCreateNestedOneWithoutEndSelectionsInput
  sessions?: Prisma.SessionCreateNestedManyWithoutSelectionInput
}

export type SelectionUncheckedCreateWithoutEndChapterInput = {
  id?: number
  resourceId: number
  startChapterId?: number | null
  startVerseId?: number | null
  endVerseId?: number | null
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutSelectionInput
}

export type SelectionCreateOrConnectWithoutEndChapterInput = {
  where: Prisma.SelectionWhereUniqueInput
  create: Prisma.XOR<Prisma.SelectionCreateWithoutEndChapterInput, Prisma.SelectionUncheckedCreateWithoutEndChapterInput>
}

export type SelectionCreateManyEndChapterInputEnvelope = {
  data: Prisma.SelectionCreateManyEndChapterInput | Prisma.SelectionCreateManyEndChapterInput[]
  skipDuplicates?: boolean
}

export type SelectionUpsertWithWhereUniqueWithoutStartChapterInput = {
  where: Prisma.SelectionWhereUniqueInput
  update: Prisma.XOR<Prisma.SelectionUpdateWithoutStartChapterInput, Prisma.SelectionUncheckedUpdateWithoutStartChapterInput>
  create: Prisma.XOR<Prisma.SelectionCreateWithoutStartChapterInput, Prisma.SelectionUncheckedCreateWithoutStartChapterInput>
}

export type SelectionUpdateWithWhereUniqueWithoutStartChapterInput = {
  where: Prisma.SelectionWhereUniqueInput
  data: Prisma.XOR<Prisma.SelectionUpdateWithoutStartChapterInput, Prisma.SelectionUncheckedUpdateWithoutStartChapterInput>
}

export type SelectionUpdateManyWithWhereWithoutStartChapterInput = {
  where: Prisma.SelectionScalarWhereInput
  data: Prisma.XOR<Prisma.SelectionUpdateManyMutationInput, Prisma.SelectionUncheckedUpdateManyWithoutStartChapterInput>
}

export type SelectionUpsertWithWhereUniqueWithoutEndChapterInput = {
  where: Prisma.SelectionWhereUniqueInput
  update: Prisma.XOR<Prisma.SelectionUpdateWithoutEndChapterInput, Prisma.SelectionUncheckedUpdateWithoutEndChapterInput>
  create: Prisma.XOR<Prisma.SelectionCreateWithoutEndChapterInput, Prisma.SelectionUncheckedCreateWithoutEndChapterInput>
}

export type SelectionUpdateWithWhereUniqueWithoutEndChapterInput = {
  where: Prisma.SelectionWhereUniqueInput
  data: Prisma.XOR<Prisma.SelectionUpdateWithoutEndChapterInput, Prisma.SelectionUncheckedUpdateWithoutEndChapterInput>
}

export type SelectionUpdateManyWithWhereWithoutEndChapterInput = {
  where: Prisma.SelectionScalarWhereInput
  data: Prisma.XOR<Prisma.SelectionUpdateManyMutationInput, Prisma.SelectionUncheckedUpdateManyWithoutEndChapterInput>
}

export type SelectionCreateWithoutStartVerseInput = {
  resource: Prisma.ResourceCreateNestedOneWithoutSelectionsInput
  startChapter?: Prisma.ChapterCreateNestedOneWithoutStartSelectionsInput
  endChapter?: Prisma.ChapterCreateNestedOneWithoutEndSelectionsInput
  endVerse?: Prisma.VerseCreateNestedOneWithoutEndSelectionsInput
  sessions?: Prisma.SessionCreateNestedManyWithoutSelectionInput
}

export type SelectionUncheckedCreateWithoutStartVerseInput = {
  id?: number
  resourceId: number
  startChapterId?: number | null
  endChapterId?: number | null
  endVerseId?: number | null
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutSelectionInput
}

export type SelectionCreateOrConnectWithoutStartVerseInput = {
  where: Prisma.SelectionWhereUniqueInput
  create: Prisma.XOR<Prisma.SelectionCreateWithoutStartVerseInput, Prisma.SelectionUncheckedCreateWithoutStartVerseInput>
}

export type SelectionCreateManyStartVerseInputEnvelope = {
  data: Prisma.SelectionCreateManyStartVerseInput | Prisma.SelectionCreateManyStartVerseInput[]
  skipDuplicates?: boolean
}

export type SelectionCreateWithoutEndVerseInput = {
  resource: Prisma.ResourceCreateNestedOneWithoutSelectionsInput
  startChapter?: Prisma.ChapterCreateNestedOneWithoutStartSelectionsInput
  endChapter?: Prisma.ChapterCreateNestedOneWithoutEndSelectionsInput
  startVerse?: Prisma.VerseCreateNestedOneWithoutStartSelectionsInput
  sessions?: Prisma.SessionCreateNestedManyWithoutSelectionInput
}

export type SelectionUncheckedCreateWithoutEndVerseInput = {
  id?: number
  resourceId: number
  startChapterId?: number | null
  endChapterId?: number | null
  startVerseId?: number | null
  sessions?: Prisma.SessionUncheckedCreateNestedManyWithoutSelectionInput
}

export type SelectionCreateOrConnectWithoutEndVerseInput = {
  where: Prisma.SelectionWhereUniqueInput
  create: Prisma.XOR<Prisma.SelectionCreateWithoutEndVerseInput, Prisma.SelectionUncheckedCreateWithoutEndVerseInput>
}

export type SelectionCreateManyEndVerseInputEnvelope = {
  data: Prisma.SelectionCreateManyEndVerseInput | Prisma.SelectionCreateManyEndVerseInput[]
  skipDuplicates?: boolean
}

export type SelectionUpsertWithWhereUniqueWithoutStartVerseInput = {
  where: Prisma.SelectionWhereUniqueInput
  update: Prisma.XOR<Prisma.SelectionUpdateWithoutStartVerseInput, Prisma.SelectionUncheckedUpdateWithoutStartVerseInput>
  create: Prisma.XOR<Prisma.SelectionCreateWithoutStartVerseInput, Prisma.SelectionUncheckedCreateWithoutStartVerseInput>
}

export type SelectionUpdateWithWhereUniqueWithoutStartVerseInput = {
  where: Prisma.SelectionWhereUniqueInput
  data: Prisma.XOR<Prisma.SelectionUpdateWithoutStartVerseInput, Prisma.SelectionUncheckedUpdateWithoutStartVerseInput>
}

export type SelectionUpdateManyWithWhereWithoutStartVerseInput = {
  where: Prisma.SelectionScalarWhereInput
  data: Prisma.XOR<Prisma.SelectionUpdateManyMutationInput, Prisma.SelectionUncheckedUpdateManyWithoutStartVerseInput>
}

export type SelectionUpsertWithWhereUniqueWithoutEndVerseInput = {
  where: Prisma.SelectionWhereUniqueInput
  update: Prisma.XOR<Prisma.SelectionUpdateWithoutEndVerseInput, Prisma.SelectionUncheckedUpdateWithoutEndVerseInput>
  create: Prisma.XOR<Prisma.SelectionCreateWithoutEndVerseInput, Prisma.SelectionUncheckedCreateWithoutEndVerseInput>
}

export type SelectionUpdateWithWhereUniqueWithoutEndVerseInput = {
  where: Prisma.SelectionWhereUniqueInput
  data: Prisma.XOR<Prisma.SelectionUpdateWithoutEndVerseInput, Prisma.SelectionUncheckedUpdateWithoutEndVerseInput>
}

export type SelectionUpdateManyWithWhereWithoutEndVerseInput = {
  where: Prisma.SelectionScalarWhereInput
  data: Prisma.XOR<Prisma.SelectionUpdateManyMutationInput, Prisma.SelectionUncheckedUpdateManyWithoutEndVerseInput>
}

export type SelectionCreateWithoutSessionsInput = {
  resource: Prisma.ResourceCreateNestedOneWithoutSelectionsInput
  startChapter?: Prisma.ChapterCreateNestedOneWithoutStartSelectionsInput
  endChapter?: Prisma.ChapterCreateNestedOneWithoutEndSelectionsInput
  startVerse?: Prisma.VerseCreateNestedOneWithoutStartSelectionsInput
  endVerse?: Prisma.VerseCreateNestedOneWithoutEndSelectionsInput
}

export type SelectionUncheckedCreateWithoutSessionsInput = {
  id?: number
  resourceId: number
  startChapterId?: number | null
  endChapterId?: number | null
  startVerseId?: number | null
  endVerseId?: number | null
}

export type SelectionCreateOrConnectWithoutSessionsInput = {
  where: Prisma.SelectionWhereUniqueInput
  create: Prisma.XOR<Prisma.SelectionCreateWithoutSessionsInput, Prisma.SelectionUncheckedCreateWithoutSessionsInput>
}

export type SelectionUpsertWithoutSessionsInput = {
  update: Prisma.XOR<Prisma.SelectionUpdateWithoutSessionsInput, Prisma.SelectionUncheckedUpdateWithoutSessionsInput>
  create: Prisma.XOR<Prisma.SelectionCreateWithoutSessionsInput, Prisma.SelectionUncheckedCreateWithoutSessionsInput>
  where?: Prisma.SelectionWhereInput
}

export type SelectionUpdateToOneWithWhereWithoutSessionsInput = {
  where?: Prisma.SelectionWhereInput
  data: Prisma.XOR<Prisma.SelectionUpdateWithoutSessionsInput, Prisma.SelectionUncheckedUpdateWithoutSessionsInput>
}

export type SelectionUpdateWithoutSessionsInput = {
  resource?: Prisma.ResourceUpdateOneRequiredWithoutSelectionsNestedInput
  startChapter?: Prisma.ChapterUpdateOneWithoutStartSelectionsNestedInput
  endChapter?: Prisma.ChapterUpdateOneWithoutEndSelectionsNestedInput
  startVerse?: Prisma.VerseUpdateOneWithoutStartSelectionsNestedInput
  endVerse?: Prisma.VerseUpdateOneWithoutEndSelectionsNestedInput
}

export type SelectionUncheckedUpdateWithoutSessionsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resourceId?: Prisma.IntFieldUpdateOperationsInput | number
  startChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  startVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type SelectionCreateManyResourceInput = {
  id?: number
  startChapterId?: number | null
  endChapterId?: number | null
  startVerseId?: number | null
  endVerseId?: number | null
}

export type SelectionUpdateWithoutResourceInput = {
  startChapter?: Prisma.ChapterUpdateOneWithoutStartSelectionsNestedInput
  endChapter?: Prisma.ChapterUpdateOneWithoutEndSelectionsNestedInput
  startVerse?: Prisma.VerseUpdateOneWithoutStartSelectionsNestedInput
  endVerse?: Prisma.VerseUpdateOneWithoutEndSelectionsNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutSelectionNestedInput
}

export type SelectionUncheckedUpdateWithoutResourceInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  startChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  startVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutSelectionNestedInput
}

export type SelectionUncheckedUpdateManyWithoutResourceInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  startChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  startVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type SelectionCreateManyStartChapterInput = {
  id?: number
  resourceId: number
  endChapterId?: number | null
  startVerseId?: number | null
  endVerseId?: number | null
}

export type SelectionCreateManyEndChapterInput = {
  id?: number
  resourceId: number
  startChapterId?: number | null
  startVerseId?: number | null
  endVerseId?: number | null
}

export type SelectionUpdateWithoutStartChapterInput = {
  resource?: Prisma.ResourceUpdateOneRequiredWithoutSelectionsNestedInput
  endChapter?: Prisma.ChapterUpdateOneWithoutEndSelectionsNestedInput
  startVerse?: Prisma.VerseUpdateOneWithoutStartSelectionsNestedInput
  endVerse?: Prisma.VerseUpdateOneWithoutEndSelectionsNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutSelectionNestedInput
}

export type SelectionUncheckedUpdateWithoutStartChapterInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resourceId?: Prisma.IntFieldUpdateOperationsInput | number
  endChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  startVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutSelectionNestedInput
}

export type SelectionUncheckedUpdateManyWithoutStartChapterInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resourceId?: Prisma.IntFieldUpdateOperationsInput | number
  endChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  startVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type SelectionUpdateWithoutEndChapterInput = {
  resource?: Prisma.ResourceUpdateOneRequiredWithoutSelectionsNestedInput
  startChapter?: Prisma.ChapterUpdateOneWithoutStartSelectionsNestedInput
  startVerse?: Prisma.VerseUpdateOneWithoutStartSelectionsNestedInput
  endVerse?: Prisma.VerseUpdateOneWithoutEndSelectionsNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutSelectionNestedInput
}

export type SelectionUncheckedUpdateWithoutEndChapterInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resourceId?: Prisma.IntFieldUpdateOperationsInput | number
  startChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  startVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutSelectionNestedInput
}

export type SelectionUncheckedUpdateManyWithoutEndChapterInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resourceId?: Prisma.IntFieldUpdateOperationsInput | number
  startChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  startVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type SelectionCreateManyStartVerseInput = {
  id?: number
  resourceId: number
  startChapterId?: number | null
  endChapterId?: number | null
  endVerseId?: number | null
}

export type SelectionCreateManyEndVerseInput = {
  id?: number
  resourceId: number
  startChapterId?: number | null
  endChapterId?: number | null
  startVerseId?: number | null
}

export type SelectionUpdateWithoutStartVerseInput = {
  resource?: Prisma.ResourceUpdateOneRequiredWithoutSelectionsNestedInput
  startChapter?: Prisma.ChapterUpdateOneWithoutStartSelectionsNestedInput
  endChapter?: Prisma.ChapterUpdateOneWithoutEndSelectionsNestedInput
  endVerse?: Prisma.VerseUpdateOneWithoutEndSelectionsNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutSelectionNestedInput
}

export type SelectionUncheckedUpdateWithoutStartVerseInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resourceId?: Prisma.IntFieldUpdateOperationsInput | number
  startChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutSelectionNestedInput
}

export type SelectionUncheckedUpdateManyWithoutStartVerseInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resourceId?: Prisma.IntFieldUpdateOperationsInput | number
  startChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type SelectionUpdateWithoutEndVerseInput = {
  resource?: Prisma.ResourceUpdateOneRequiredWithoutSelectionsNestedInput
  startChapter?: Prisma.ChapterUpdateOneWithoutStartSelectionsNestedInput
  endChapter?: Prisma.ChapterUpdateOneWithoutEndSelectionsNestedInput
  startVerse?: Prisma.VerseUpdateOneWithoutStartSelectionsNestedInput
  sessions?: Prisma.SessionUpdateManyWithoutSelectionNestedInput
}

export type SelectionUncheckedUpdateWithoutEndVerseInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resourceId?: Prisma.IntFieldUpdateOperationsInput | number
  startChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  startVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  sessions?: Prisma.SessionUncheckedUpdateManyWithoutSelectionNestedInput
}

export type SelectionUncheckedUpdateManyWithoutEndVerseInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resourceId?: Prisma.IntFieldUpdateOperationsInput | number
  startChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  endChapterId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  startVerseId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}


/**
 * Count Type SelectionCountOutputType
 */

export type SelectionCountOutputType = {
  sessions: number
}

export type SelectionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sessions?: boolean | SelectionCountOutputTypeCountSessionsArgs
}

/**
 * SelectionCountOutputType without action
 */
export type SelectionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SelectionCountOutputType
   */
  select?: Prisma.SelectionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SelectionCountOutputType without action
 */
export type SelectionCountOutputTypeCountSessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionWhereInput
}


export type SelectionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  resourceId?: boolean
  startChapterId?: boolean
  endChapterId?: boolean
  startVerseId?: boolean
  endVerseId?: boolean
  resource?: boolean | Prisma.ResourceDefaultArgs<ExtArgs>
  startChapter?: boolean | Prisma.Selection$startChapterArgs<ExtArgs>
  endChapter?: boolean | Prisma.Selection$endChapterArgs<ExtArgs>
  startVerse?: boolean | Prisma.Selection$startVerseArgs<ExtArgs>
  endVerse?: boolean | Prisma.Selection$endVerseArgs<ExtArgs>
  sessions?: boolean | Prisma.Selection$sessionsArgs<ExtArgs>
  _count?: boolean | Prisma.SelectionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["selection"]>

export type SelectionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  resourceId?: boolean
  startChapterId?: boolean
  endChapterId?: boolean
  startVerseId?: boolean
  endVerseId?: boolean
  resource?: boolean | Prisma.ResourceDefaultArgs<ExtArgs>
  startChapter?: boolean | Prisma.Selection$startChapterArgs<ExtArgs>
  endChapter?: boolean | Prisma.Selection$endChapterArgs<ExtArgs>
  startVerse?: boolean | Prisma.Selection$startVerseArgs<ExtArgs>
  endVerse?: boolean | Prisma.Selection$endVerseArgs<ExtArgs>
}, ExtArgs["result"]["selection"]>

export type SelectionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  resourceId?: boolean
  startChapterId?: boolean
  endChapterId?: boolean
  startVerseId?: boolean
  endVerseId?: boolean
  resource?: boolean | Prisma.ResourceDefaultArgs<ExtArgs>
  startChapter?: boolean | Prisma.Selection$startChapterArgs<ExtArgs>
  endChapter?: boolean | Prisma.Selection$endChapterArgs<ExtArgs>
  startVerse?: boolean | Prisma.Selection$startVerseArgs<ExtArgs>
  endVerse?: boolean | Prisma.Selection$endVerseArgs<ExtArgs>
}, ExtArgs["result"]["selection"]>

export type SelectionSelectScalar = {
  id?: boolean
  resourceId?: boolean
  startChapterId?: boolean
  endChapterId?: boolean
  startVerseId?: boolean
  endVerseId?: boolean
}

export type SelectionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "resourceId" | "startChapterId" | "endChapterId" | "startVerseId" | "endVerseId", ExtArgs["result"]["selection"]>
export type SelectionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  resource?: boolean | Prisma.ResourceDefaultArgs<ExtArgs>
  startChapter?: boolean | Prisma.Selection$startChapterArgs<ExtArgs>
  endChapter?: boolean | Prisma.Selection$endChapterArgs<ExtArgs>
  startVerse?: boolean | Prisma.Selection$startVerseArgs<ExtArgs>
  endVerse?: boolean | Prisma.Selection$endVerseArgs<ExtArgs>
  sessions?: boolean | Prisma.Selection$sessionsArgs<ExtArgs>
  _count?: boolean | Prisma.SelectionCountOutputTypeDefaultArgs<ExtArgs>
}
export type SelectionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  resource?: boolean | Prisma.ResourceDefaultArgs<ExtArgs>
  startChapter?: boolean | Prisma.Selection$startChapterArgs<ExtArgs>
  endChapter?: boolean | Prisma.Selection$endChapterArgs<ExtArgs>
  startVerse?: boolean | Prisma.Selection$startVerseArgs<ExtArgs>
  endVerse?: boolean | Prisma.Selection$endVerseArgs<ExtArgs>
}
export type SelectionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  resource?: boolean | Prisma.ResourceDefaultArgs<ExtArgs>
  startChapter?: boolean | Prisma.Selection$startChapterArgs<ExtArgs>
  endChapter?: boolean | Prisma.Selection$endChapterArgs<ExtArgs>
  startVerse?: boolean | Prisma.Selection$startVerseArgs<ExtArgs>
  endVerse?: boolean | Prisma.Selection$endVerseArgs<ExtArgs>
}

export type $SelectionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Selection"
  objects: {
    resource: Prisma.$ResourcePayload<ExtArgs>
    startChapter: Prisma.$ChapterPayload<ExtArgs> | null
    endChapter: Prisma.$ChapterPayload<ExtArgs> | null
    startVerse: Prisma.$VersePayload<ExtArgs> | null
    endVerse: Prisma.$VersePayload<ExtArgs> | null
    sessions: Prisma.$SessionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    resourceId: number
    startChapterId: number | null
    endChapterId: number | null
    startVerseId: number | null
    endVerseId: number | null
  }, ExtArgs["result"]["selection"]>
  composites: {}
}

export type SelectionGetPayload<S extends boolean | null | undefined | SelectionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SelectionPayload, S>

export type SelectionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SelectionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SelectionCountAggregateInputType | true
  }

export interface SelectionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Selection'], meta: { name: 'Selection' } }
  /**
   * Find zero or one Selection that matches the filter.
   * @param {SelectionFindUniqueArgs} args - Arguments to find a Selection
   * @example
   * // Get one Selection
   * const selection = await prisma.selection.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SelectionFindUniqueArgs>(args: Prisma.SelectSubset<T, SelectionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SelectionClient<runtime.Types.Result.GetResult<Prisma.$SelectionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Selection that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SelectionFindUniqueOrThrowArgs} args - Arguments to find a Selection
   * @example
   * // Get one Selection
   * const selection = await prisma.selection.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SelectionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SelectionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SelectionClient<runtime.Types.Result.GetResult<Prisma.$SelectionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Selection that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SelectionFindFirstArgs} args - Arguments to find a Selection
   * @example
   * // Get one Selection
   * const selection = await prisma.selection.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SelectionFindFirstArgs>(args?: Prisma.SelectSubset<T, SelectionFindFirstArgs<ExtArgs>>): Prisma.Prisma__SelectionClient<runtime.Types.Result.GetResult<Prisma.$SelectionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Selection that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SelectionFindFirstOrThrowArgs} args - Arguments to find a Selection
   * @example
   * // Get one Selection
   * const selection = await prisma.selection.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SelectionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SelectionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SelectionClient<runtime.Types.Result.GetResult<Prisma.$SelectionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Selections that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SelectionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Selections
   * const selections = await prisma.selection.findMany()
   * 
   * // Get first 10 Selections
   * const selections = await prisma.selection.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const selectionWithIdOnly = await prisma.selection.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SelectionFindManyArgs>(args?: Prisma.SelectSubset<T, SelectionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SelectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Selection.
   * @param {SelectionCreateArgs} args - Arguments to create a Selection.
   * @example
   * // Create one Selection
   * const Selection = await prisma.selection.create({
   *   data: {
   *     // ... data to create a Selection
   *   }
   * })
   * 
   */
  create<T extends SelectionCreateArgs>(args: Prisma.SelectSubset<T, SelectionCreateArgs<ExtArgs>>): Prisma.Prisma__SelectionClient<runtime.Types.Result.GetResult<Prisma.$SelectionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Selections.
   * @param {SelectionCreateManyArgs} args - Arguments to create many Selections.
   * @example
   * // Create many Selections
   * const selection = await prisma.selection.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SelectionCreateManyArgs>(args?: Prisma.SelectSubset<T, SelectionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Selections and returns the data saved in the database.
   * @param {SelectionCreateManyAndReturnArgs} args - Arguments to create many Selections.
   * @example
   * // Create many Selections
   * const selection = await prisma.selection.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Selections and only return the `id`
   * const selectionWithIdOnly = await prisma.selection.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SelectionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SelectionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SelectionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Selection.
   * @param {SelectionDeleteArgs} args - Arguments to delete one Selection.
   * @example
   * // Delete one Selection
   * const Selection = await prisma.selection.delete({
   *   where: {
   *     // ... filter to delete one Selection
   *   }
   * })
   * 
   */
  delete<T extends SelectionDeleteArgs>(args: Prisma.SelectSubset<T, SelectionDeleteArgs<ExtArgs>>): Prisma.Prisma__SelectionClient<runtime.Types.Result.GetResult<Prisma.$SelectionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Selection.
   * @param {SelectionUpdateArgs} args - Arguments to update one Selection.
   * @example
   * // Update one Selection
   * const selection = await prisma.selection.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SelectionUpdateArgs>(args: Prisma.SelectSubset<T, SelectionUpdateArgs<ExtArgs>>): Prisma.Prisma__SelectionClient<runtime.Types.Result.GetResult<Prisma.$SelectionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Selections.
   * @param {SelectionDeleteManyArgs} args - Arguments to filter Selections to delete.
   * @example
   * // Delete a few Selections
   * const { count } = await prisma.selection.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SelectionDeleteManyArgs>(args?: Prisma.SelectSubset<T, SelectionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Selections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SelectionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Selections
   * const selection = await prisma.selection.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SelectionUpdateManyArgs>(args: Prisma.SelectSubset<T, SelectionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Selections and returns the data updated in the database.
   * @param {SelectionUpdateManyAndReturnArgs} args - Arguments to update many Selections.
   * @example
   * // Update many Selections
   * const selection = await prisma.selection.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Selections and only return the `id`
   * const selectionWithIdOnly = await prisma.selection.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SelectionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SelectionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SelectionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Selection.
   * @param {SelectionUpsertArgs} args - Arguments to update or create a Selection.
   * @example
   * // Update or create a Selection
   * const selection = await prisma.selection.upsert({
   *   create: {
   *     // ... data to create a Selection
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Selection we want to update
   *   }
   * })
   */
  upsert<T extends SelectionUpsertArgs>(args: Prisma.SelectSubset<T, SelectionUpsertArgs<ExtArgs>>): Prisma.Prisma__SelectionClient<runtime.Types.Result.GetResult<Prisma.$SelectionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Selections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SelectionCountArgs} args - Arguments to filter Selections to count.
   * @example
   * // Count the number of Selections
   * const count = await prisma.selection.count({
   *   where: {
   *     // ... the filter for the Selections we want to count
   *   }
   * })
  **/
  count<T extends SelectionCountArgs>(
    args?: Prisma.Subset<T, SelectionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SelectionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Selection.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SelectionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SelectionAggregateArgs>(args: Prisma.Subset<T, SelectionAggregateArgs>): Prisma.PrismaPromise<GetSelectionAggregateType<T>>

  /**
   * Group by Selection.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SelectionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SelectionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SelectionGroupByArgs['orderBy'] }
      : { orderBy?: SelectionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SelectionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSelectionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Selection model
 */
readonly fields: SelectionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Selection.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SelectionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  resource<T extends Prisma.ResourceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ResourceDefaultArgs<ExtArgs>>): Prisma.Prisma__ResourceClient<runtime.Types.Result.GetResult<Prisma.$ResourcePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  startChapter<T extends Prisma.Selection$startChapterArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Selection$startChapterArgs<ExtArgs>>): Prisma.Prisma__ChapterClient<runtime.Types.Result.GetResult<Prisma.$ChapterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  endChapter<T extends Prisma.Selection$endChapterArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Selection$endChapterArgs<ExtArgs>>): Prisma.Prisma__ChapterClient<runtime.Types.Result.GetResult<Prisma.$ChapterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  startVerse<T extends Prisma.Selection$startVerseArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Selection$startVerseArgs<ExtArgs>>): Prisma.Prisma__VerseClient<runtime.Types.Result.GetResult<Prisma.$VersePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  endVerse<T extends Prisma.Selection$endVerseArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Selection$endVerseArgs<ExtArgs>>): Prisma.Prisma__VerseClient<runtime.Types.Result.GetResult<Prisma.$VersePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  sessions<T extends Prisma.Selection$sessionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Selection$sessionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Selection model
 */
export interface SelectionFieldRefs {
  readonly id: Prisma.FieldRef<"Selection", 'Int'>
  readonly resourceId: Prisma.FieldRef<"Selection", 'Int'>
  readonly startChapterId: Prisma.FieldRef<"Selection", 'Int'>
  readonly endChapterId: Prisma.FieldRef<"Selection", 'Int'>
  readonly startVerseId: Prisma.FieldRef<"Selection", 'Int'>
  readonly endVerseId: Prisma.FieldRef<"Selection", 'Int'>
}
    

// Custom InputTypes
/**
 * Selection findUnique
 */
export type SelectionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Selection
   */
  select?: Prisma.SelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Selection
   */
  omit?: Prisma.SelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectionInclude<ExtArgs> | null
  /**
   * Filter, which Selection to fetch.
   */
  where: Prisma.SelectionWhereUniqueInput
}

/**
 * Selection findUniqueOrThrow
 */
export type SelectionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Selection
   */
  select?: Prisma.SelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Selection
   */
  omit?: Prisma.SelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectionInclude<ExtArgs> | null
  /**
   * Filter, which Selection to fetch.
   */
  where: Prisma.SelectionWhereUniqueInput
}

/**
 * Selection findFirst
 */
export type SelectionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Selection
   */
  select?: Prisma.SelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Selection
   */
  omit?: Prisma.SelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectionInclude<ExtArgs> | null
  /**
   * Filter, which Selection to fetch.
   */
  where?: Prisma.SelectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Selections to fetch.
   */
  orderBy?: Prisma.SelectionOrderByWithRelationInput | Prisma.SelectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Selections.
   */
  cursor?: Prisma.SelectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Selections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Selections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Selections.
   */
  distinct?: Prisma.SelectionScalarFieldEnum | Prisma.SelectionScalarFieldEnum[]
}

/**
 * Selection findFirstOrThrow
 */
export type SelectionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Selection
   */
  select?: Prisma.SelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Selection
   */
  omit?: Prisma.SelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectionInclude<ExtArgs> | null
  /**
   * Filter, which Selection to fetch.
   */
  where?: Prisma.SelectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Selections to fetch.
   */
  orderBy?: Prisma.SelectionOrderByWithRelationInput | Prisma.SelectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Selections.
   */
  cursor?: Prisma.SelectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Selections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Selections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Selections.
   */
  distinct?: Prisma.SelectionScalarFieldEnum | Prisma.SelectionScalarFieldEnum[]
}

/**
 * Selection findMany
 */
export type SelectionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Selection
   */
  select?: Prisma.SelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Selection
   */
  omit?: Prisma.SelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectionInclude<ExtArgs> | null
  /**
   * Filter, which Selections to fetch.
   */
  where?: Prisma.SelectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Selections to fetch.
   */
  orderBy?: Prisma.SelectionOrderByWithRelationInput | Prisma.SelectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Selections.
   */
  cursor?: Prisma.SelectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Selections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Selections.
   */
  skip?: number
  distinct?: Prisma.SelectionScalarFieldEnum | Prisma.SelectionScalarFieldEnum[]
}

/**
 * Selection create
 */
export type SelectionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Selection
   */
  select?: Prisma.SelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Selection
   */
  omit?: Prisma.SelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectionInclude<ExtArgs> | null
  /**
   * The data needed to create a Selection.
   */
  data: Prisma.XOR<Prisma.SelectionCreateInput, Prisma.SelectionUncheckedCreateInput>
}

/**
 * Selection createMany
 */
export type SelectionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Selections.
   */
  data: Prisma.SelectionCreateManyInput | Prisma.SelectionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Selection createManyAndReturn
 */
export type SelectionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Selection
   */
  select?: Prisma.SelectionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Selection
   */
  omit?: Prisma.SelectionOmit<ExtArgs> | null
  /**
   * The data used to create many Selections.
   */
  data: Prisma.SelectionCreateManyInput | Prisma.SelectionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Selection update
 */
export type SelectionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Selection
   */
  select?: Prisma.SelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Selection
   */
  omit?: Prisma.SelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectionInclude<ExtArgs> | null
  /**
   * The data needed to update a Selection.
   */
  data: Prisma.XOR<Prisma.SelectionUpdateInput, Prisma.SelectionUncheckedUpdateInput>
  /**
   * Choose, which Selection to update.
   */
  where: Prisma.SelectionWhereUniqueInput
}

/**
 * Selection updateMany
 */
export type SelectionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Selections.
   */
  data: Prisma.XOR<Prisma.SelectionUpdateManyMutationInput, Prisma.SelectionUncheckedUpdateManyInput>
  /**
   * Filter which Selections to update
   */
  where?: Prisma.SelectionWhereInput
  /**
   * Limit how many Selections to update.
   */
  limit?: number
}

/**
 * Selection updateManyAndReturn
 */
export type SelectionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Selection
   */
  select?: Prisma.SelectionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Selection
   */
  omit?: Prisma.SelectionOmit<ExtArgs> | null
  /**
   * The data used to update Selections.
   */
  data: Prisma.XOR<Prisma.SelectionUpdateManyMutationInput, Prisma.SelectionUncheckedUpdateManyInput>
  /**
   * Filter which Selections to update
   */
  where?: Prisma.SelectionWhereInput
  /**
   * Limit how many Selections to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Selection upsert
 */
export type SelectionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Selection
   */
  select?: Prisma.SelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Selection
   */
  omit?: Prisma.SelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectionInclude<ExtArgs> | null
  /**
   * The filter to search for the Selection to update in case it exists.
   */
  where: Prisma.SelectionWhereUniqueInput
  /**
   * In case the Selection found by the `where` argument doesn't exist, create a new Selection with this data.
   */
  create: Prisma.XOR<Prisma.SelectionCreateInput, Prisma.SelectionUncheckedCreateInput>
  /**
   * In case the Selection was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SelectionUpdateInput, Prisma.SelectionUncheckedUpdateInput>
}

/**
 * Selection delete
 */
export type SelectionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Selection
   */
  select?: Prisma.SelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Selection
   */
  omit?: Prisma.SelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectionInclude<ExtArgs> | null
  /**
   * Filter which Selection to delete.
   */
  where: Prisma.SelectionWhereUniqueInput
}

/**
 * Selection deleteMany
 */
export type SelectionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Selections to delete
   */
  where?: Prisma.SelectionWhereInput
  /**
   * Limit how many Selections to delete.
   */
  limit?: number
}

/**
 * Selection.startChapter
 */
export type Selection$startChapterArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chapter
   */
  select?: Prisma.ChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chapter
   */
  omit?: Prisma.ChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChapterInclude<ExtArgs> | null
  where?: Prisma.ChapterWhereInput
}

/**
 * Selection.endChapter
 */
export type Selection$endChapterArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chapter
   */
  select?: Prisma.ChapterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chapter
   */
  omit?: Prisma.ChapterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChapterInclude<ExtArgs> | null
  where?: Prisma.ChapterWhereInput
}

/**
 * Selection.startVerse
 */
export type Selection$startVerseArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verse
   */
  select?: Prisma.VerseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verse
   */
  omit?: Prisma.VerseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VerseInclude<ExtArgs> | null
  where?: Prisma.VerseWhereInput
}

/**
 * Selection.endVerse
 */
export type Selection$endVerseArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verse
   */
  select?: Prisma.VerseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verse
   */
  omit?: Prisma.VerseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VerseInclude<ExtArgs> | null
  where?: Prisma.VerseWhereInput
}

/**
 * Selection.sessions
 */
export type Selection$sessionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  where?: Prisma.SessionWhereInput
  orderBy?: Prisma.SessionOrderByWithRelationInput | Prisma.SessionOrderByWithRelationInput[]
  cursor?: Prisma.SessionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SessionScalarFieldEnum | Prisma.SessionScalarFieldEnum[]
}

/**
 * Selection without action
 */
export type SelectionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Selection
   */
  select?: Prisma.SelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Selection
   */
  omit?: Prisma.SelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectionInclude<ExtArgs> | null
}
