
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `SessionStep` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SessionStep
 * 
 */
export type SessionStepModel = runtime.Types.Result.DefaultSelection<Prisma.$SessionStepPayload>

export type AggregateSessionStep = {
  _count: SessionStepCountAggregateOutputType | null
  _avg: SessionStepAvgAggregateOutputType | null
  _sum: SessionStepSumAggregateOutputType | null
  _min: SessionStepMinAggregateOutputType | null
  _max: SessionStepMaxAggregateOutputType | null
}

export type SessionStepAvgAggregateOutputType = {
  id: number | null
  sessionId: number | null
  guideStepId: number | null
}

export type SessionStepSumAggregateOutputType = {
  id: number | null
  sessionId: number | null
  guideStepId: number | null
}

export type SessionStepMinAggregateOutputType = {
  id: number | null
  sessionId: number | null
  guideStepId: number | null
  insights: string | null
}

export type SessionStepMaxAggregateOutputType = {
  id: number | null
  sessionId: number | null
  guideStepId: number | null
  insights: string | null
}

export type SessionStepCountAggregateOutputType = {
  id: number
  sessionId: number
  guideStepId: number
  insights: number
  _all: number
}


export type SessionStepAvgAggregateInputType = {
  id?: true
  sessionId?: true
  guideStepId?: true
}

export type SessionStepSumAggregateInputType = {
  id?: true
  sessionId?: true
  guideStepId?: true
}

export type SessionStepMinAggregateInputType = {
  id?: true
  sessionId?: true
  guideStepId?: true
  insights?: true
}

export type SessionStepMaxAggregateInputType = {
  id?: true
  sessionId?: true
  guideStepId?: true
  insights?: true
}

export type SessionStepCountAggregateInputType = {
  id?: true
  sessionId?: true
  guideStepId?: true
  insights?: true
  _all?: true
}

export type SessionStepAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SessionStep to aggregate.
   */
  where?: Prisma.SessionStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionSteps to fetch.
   */
  orderBy?: Prisma.SessionStepOrderByWithRelationInput | Prisma.SessionStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SessionStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionSteps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SessionSteps
  **/
  _count?: true | SessionStepCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SessionStepAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SessionStepSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SessionStepMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SessionStepMaxAggregateInputType
}

export type GetSessionStepAggregateType<T extends SessionStepAggregateArgs> = {
      [P in keyof T & keyof AggregateSessionStep]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSessionStep[P]>
    : Prisma.GetScalarType<T[P], AggregateSessionStep[P]>
}




export type SessionStepGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionStepWhereInput
  orderBy?: Prisma.SessionStepOrderByWithAggregationInput | Prisma.SessionStepOrderByWithAggregationInput[]
  by: Prisma.SessionStepScalarFieldEnum[] | Prisma.SessionStepScalarFieldEnum
  having?: Prisma.SessionStepScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SessionStepCountAggregateInputType | true
  _avg?: SessionStepAvgAggregateInputType
  _sum?: SessionStepSumAggregateInputType
  _min?: SessionStepMinAggregateInputType
  _max?: SessionStepMaxAggregateInputType
}

export type SessionStepGroupByOutputType = {
  id: number
  sessionId: number
  guideStepId: number
  insights: string | null
  _count: SessionStepCountAggregateOutputType | null
  _avg: SessionStepAvgAggregateOutputType | null
  _sum: SessionStepSumAggregateOutputType | null
  _min: SessionStepMinAggregateOutputType | null
  _max: SessionStepMaxAggregateOutputType | null
}

type GetSessionStepGroupByPayload<T extends SessionStepGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SessionStepGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SessionStepGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SessionStepGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SessionStepGroupByOutputType[P]>
      }
    >
  >



export type SessionStepWhereInput = {
  AND?: Prisma.SessionStepWhereInput | Prisma.SessionStepWhereInput[]
  OR?: Prisma.SessionStepWhereInput[]
  NOT?: Prisma.SessionStepWhereInput | Prisma.SessionStepWhereInput[]
  id?: Prisma.IntFilter<"SessionStep"> | number
  sessionId?: Prisma.IntFilter<"SessionStep"> | number
  guideStepId?: Prisma.IntFilter<"SessionStep"> | number
  insights?: Prisma.StringNullableFilter<"SessionStep"> | string | null
  session?: Prisma.XOR<Prisma.SessionScalarRelationFilter, Prisma.SessionWhereInput>
  guideStep?: Prisma.XOR<Prisma.GuideStepScalarRelationFilter, Prisma.GuideStepWhereInput>
}

export type SessionStepOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  guideStepId?: Prisma.SortOrder
  insights?: Prisma.SortOrderInput | Prisma.SortOrder
  session?: Prisma.SessionOrderByWithRelationInput
  guideStep?: Prisma.GuideStepOrderByWithRelationInput
}

export type SessionStepWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.SessionStepWhereInput | Prisma.SessionStepWhereInput[]
  OR?: Prisma.SessionStepWhereInput[]
  NOT?: Prisma.SessionStepWhereInput | Prisma.SessionStepWhereInput[]
  sessionId?: Prisma.IntFilter<"SessionStep"> | number
  guideStepId?: Prisma.IntFilter<"SessionStep"> | number
  insights?: Prisma.StringNullableFilter<"SessionStep"> | string | null
  session?: Prisma.XOR<Prisma.SessionScalarRelationFilter, Prisma.SessionWhereInput>
  guideStep?: Prisma.XOR<Prisma.GuideStepScalarRelationFilter, Prisma.GuideStepWhereInput>
}, "id">

export type SessionStepOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  guideStepId?: Prisma.SortOrder
  insights?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.SessionStepCountOrderByAggregateInput
  _avg?: Prisma.SessionStepAvgOrderByAggregateInput
  _max?: Prisma.SessionStepMaxOrderByAggregateInput
  _min?: Prisma.SessionStepMinOrderByAggregateInput
  _sum?: Prisma.SessionStepSumOrderByAggregateInput
}

export type SessionStepScalarWhereWithAggregatesInput = {
  AND?: Prisma.SessionStepScalarWhereWithAggregatesInput | Prisma.SessionStepScalarWhereWithAggregatesInput[]
  OR?: Prisma.SessionStepScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SessionStepScalarWhereWithAggregatesInput | Prisma.SessionStepScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"SessionStep"> | number
  sessionId?: Prisma.IntWithAggregatesFilter<"SessionStep"> | number
  guideStepId?: Prisma.IntWithAggregatesFilter<"SessionStep"> | number
  insights?: Prisma.StringNullableWithAggregatesFilter<"SessionStep"> | string | null
}

export type SessionStepCreateInput = {
  insights?: string | null
  session: Prisma.SessionCreateNestedOneWithoutSessionStepsInput
  guideStep: Prisma.GuideStepCreateNestedOneWithoutSessionStepsInput
}

export type SessionStepUncheckedCreateInput = {
  id?: number
  sessionId: number
  guideStepId: number
  insights?: string | null
}

export type SessionStepUpdateInput = {
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  session?: Prisma.SessionUpdateOneRequiredWithoutSessionStepsNestedInput
  guideStep?: Prisma.GuideStepUpdateOneRequiredWithoutSessionStepsNestedInput
}

export type SessionStepUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sessionId?: Prisma.IntFieldUpdateOperationsInput | number
  guideStepId?: Prisma.IntFieldUpdateOperationsInput | number
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SessionStepCreateManyInput = {
  id?: number
  sessionId: number
  guideStepId: number
  insights?: string | null
}

export type SessionStepUpdateManyMutationInput = {
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SessionStepUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sessionId?: Prisma.IntFieldUpdateOperationsInput | number
  guideStepId?: Prisma.IntFieldUpdateOperationsInput | number
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SessionStepListRelationFilter = {
  every?: Prisma.SessionStepWhereInput
  some?: Prisma.SessionStepWhereInput
  none?: Prisma.SessionStepWhereInput
}

export type SessionStepOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SessionStepCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  guideStepId?: Prisma.SortOrder
  insights?: Prisma.SortOrder
}

export type SessionStepAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  guideStepId?: Prisma.SortOrder
}

export type SessionStepMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  guideStepId?: Prisma.SortOrder
  insights?: Prisma.SortOrder
}

export type SessionStepMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  guideStepId?: Prisma.SortOrder
  insights?: Prisma.SortOrder
}

export type SessionStepSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  guideStepId?: Prisma.SortOrder
}

export type SessionStepCreateNestedManyWithoutGuideStepInput = {
  create?: Prisma.XOR<Prisma.SessionStepCreateWithoutGuideStepInput, Prisma.SessionStepUncheckedCreateWithoutGuideStepInput> | Prisma.SessionStepCreateWithoutGuideStepInput[] | Prisma.SessionStepUncheckedCreateWithoutGuideStepInput[]
  connectOrCreate?: Prisma.SessionStepCreateOrConnectWithoutGuideStepInput | Prisma.SessionStepCreateOrConnectWithoutGuideStepInput[]
  createMany?: Prisma.SessionStepCreateManyGuideStepInputEnvelope
  connect?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
}

export type SessionStepUncheckedCreateNestedManyWithoutGuideStepInput = {
  create?: Prisma.XOR<Prisma.SessionStepCreateWithoutGuideStepInput, Prisma.SessionStepUncheckedCreateWithoutGuideStepInput> | Prisma.SessionStepCreateWithoutGuideStepInput[] | Prisma.SessionStepUncheckedCreateWithoutGuideStepInput[]
  connectOrCreate?: Prisma.SessionStepCreateOrConnectWithoutGuideStepInput | Prisma.SessionStepCreateOrConnectWithoutGuideStepInput[]
  createMany?: Prisma.SessionStepCreateManyGuideStepInputEnvelope
  connect?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
}

export type SessionStepUpdateManyWithoutGuideStepNestedInput = {
  create?: Prisma.XOR<Prisma.SessionStepCreateWithoutGuideStepInput, Prisma.SessionStepUncheckedCreateWithoutGuideStepInput> | Prisma.SessionStepCreateWithoutGuideStepInput[] | Prisma.SessionStepUncheckedCreateWithoutGuideStepInput[]
  connectOrCreate?: Prisma.SessionStepCreateOrConnectWithoutGuideStepInput | Prisma.SessionStepCreateOrConnectWithoutGuideStepInput[]
  upsert?: Prisma.SessionStepUpsertWithWhereUniqueWithoutGuideStepInput | Prisma.SessionStepUpsertWithWhereUniqueWithoutGuideStepInput[]
  createMany?: Prisma.SessionStepCreateManyGuideStepInputEnvelope
  set?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
  disconnect?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
  delete?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
  connect?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
  update?: Prisma.SessionStepUpdateWithWhereUniqueWithoutGuideStepInput | Prisma.SessionStepUpdateWithWhereUniqueWithoutGuideStepInput[]
  updateMany?: Prisma.SessionStepUpdateManyWithWhereWithoutGuideStepInput | Prisma.SessionStepUpdateManyWithWhereWithoutGuideStepInput[]
  deleteMany?: Prisma.SessionStepScalarWhereInput | Prisma.SessionStepScalarWhereInput[]
}

export type SessionStepUncheckedUpdateManyWithoutGuideStepNestedInput = {
  create?: Prisma.XOR<Prisma.SessionStepCreateWithoutGuideStepInput, Prisma.SessionStepUncheckedCreateWithoutGuideStepInput> | Prisma.SessionStepCreateWithoutGuideStepInput[] | Prisma.SessionStepUncheckedCreateWithoutGuideStepInput[]
  connectOrCreate?: Prisma.SessionStepCreateOrConnectWithoutGuideStepInput | Prisma.SessionStepCreateOrConnectWithoutGuideStepInput[]
  upsert?: Prisma.SessionStepUpsertWithWhereUniqueWithoutGuideStepInput | Prisma.SessionStepUpsertWithWhereUniqueWithoutGuideStepInput[]
  createMany?: Prisma.SessionStepCreateManyGuideStepInputEnvelope
  set?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
  disconnect?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
  delete?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
  connect?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
  update?: Prisma.SessionStepUpdateWithWhereUniqueWithoutGuideStepInput | Prisma.SessionStepUpdateWithWhereUniqueWithoutGuideStepInput[]
  updateMany?: Prisma.SessionStepUpdateManyWithWhereWithoutGuideStepInput | Prisma.SessionStepUpdateManyWithWhereWithoutGuideStepInput[]
  deleteMany?: Prisma.SessionStepScalarWhereInput | Prisma.SessionStepScalarWhereInput[]
}

export type SessionStepCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.SessionStepCreateWithoutSessionInput, Prisma.SessionStepUncheckedCreateWithoutSessionInput> | Prisma.SessionStepCreateWithoutSessionInput[] | Prisma.SessionStepUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.SessionStepCreateOrConnectWithoutSessionInput | Prisma.SessionStepCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.SessionStepCreateManySessionInputEnvelope
  connect?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
}

export type SessionStepUncheckedCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.SessionStepCreateWithoutSessionInput, Prisma.SessionStepUncheckedCreateWithoutSessionInput> | Prisma.SessionStepCreateWithoutSessionInput[] | Prisma.SessionStepUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.SessionStepCreateOrConnectWithoutSessionInput | Prisma.SessionStepCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.SessionStepCreateManySessionInputEnvelope
  connect?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
}

export type SessionStepUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.SessionStepCreateWithoutSessionInput, Prisma.SessionStepUncheckedCreateWithoutSessionInput> | Prisma.SessionStepCreateWithoutSessionInput[] | Prisma.SessionStepUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.SessionStepCreateOrConnectWithoutSessionInput | Prisma.SessionStepCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.SessionStepUpsertWithWhereUniqueWithoutSessionInput | Prisma.SessionStepUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.SessionStepCreateManySessionInputEnvelope
  set?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
  disconnect?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
  delete?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
  connect?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
  update?: Prisma.SessionStepUpdateWithWhereUniqueWithoutSessionInput | Prisma.SessionStepUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.SessionStepUpdateManyWithWhereWithoutSessionInput | Prisma.SessionStepUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.SessionStepScalarWhereInput | Prisma.SessionStepScalarWhereInput[]
}

export type SessionStepUncheckedUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.SessionStepCreateWithoutSessionInput, Prisma.SessionStepUncheckedCreateWithoutSessionInput> | Prisma.SessionStepCreateWithoutSessionInput[] | Prisma.SessionStepUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.SessionStepCreateOrConnectWithoutSessionInput | Prisma.SessionStepCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.SessionStepUpsertWithWhereUniqueWithoutSessionInput | Prisma.SessionStepUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.SessionStepCreateManySessionInputEnvelope
  set?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
  disconnect?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
  delete?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
  connect?: Prisma.SessionStepWhereUniqueInput | Prisma.SessionStepWhereUniqueInput[]
  update?: Prisma.SessionStepUpdateWithWhereUniqueWithoutSessionInput | Prisma.SessionStepUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.SessionStepUpdateManyWithWhereWithoutSessionInput | Prisma.SessionStepUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.SessionStepScalarWhereInput | Prisma.SessionStepScalarWhereInput[]
}

export type SessionStepCreateWithoutGuideStepInput = {
  insights?: string | null
  session: Prisma.SessionCreateNestedOneWithoutSessionStepsInput
}

export type SessionStepUncheckedCreateWithoutGuideStepInput = {
  id?: number
  sessionId: number
  insights?: string | null
}

export type SessionStepCreateOrConnectWithoutGuideStepInput = {
  where: Prisma.SessionStepWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionStepCreateWithoutGuideStepInput, Prisma.SessionStepUncheckedCreateWithoutGuideStepInput>
}

export type SessionStepCreateManyGuideStepInputEnvelope = {
  data: Prisma.SessionStepCreateManyGuideStepInput | Prisma.SessionStepCreateManyGuideStepInput[]
  skipDuplicates?: boolean
}

export type SessionStepUpsertWithWhereUniqueWithoutGuideStepInput = {
  where: Prisma.SessionStepWhereUniqueInput
  update: Prisma.XOR<Prisma.SessionStepUpdateWithoutGuideStepInput, Prisma.SessionStepUncheckedUpdateWithoutGuideStepInput>
  create: Prisma.XOR<Prisma.SessionStepCreateWithoutGuideStepInput, Prisma.SessionStepUncheckedCreateWithoutGuideStepInput>
}

export type SessionStepUpdateWithWhereUniqueWithoutGuideStepInput = {
  where: Prisma.SessionStepWhereUniqueInput
  data: Prisma.XOR<Prisma.SessionStepUpdateWithoutGuideStepInput, Prisma.SessionStepUncheckedUpdateWithoutGuideStepInput>
}

export type SessionStepUpdateManyWithWhereWithoutGuideStepInput = {
  where: Prisma.SessionStepScalarWhereInput
  data: Prisma.XOR<Prisma.SessionStepUpdateManyMutationInput, Prisma.SessionStepUncheckedUpdateManyWithoutGuideStepInput>
}

export type SessionStepScalarWhereInput = {
  AND?: Prisma.SessionStepScalarWhereInput | Prisma.SessionStepScalarWhereInput[]
  OR?: Prisma.SessionStepScalarWhereInput[]
  NOT?: Prisma.SessionStepScalarWhereInput | Prisma.SessionStepScalarWhereInput[]
  id?: Prisma.IntFilter<"SessionStep"> | number
  sessionId?: Prisma.IntFilter<"SessionStep"> | number
  guideStepId?: Prisma.IntFilter<"SessionStep"> | number
  insights?: Prisma.StringNullableFilter<"SessionStep"> | string | null
}

export type SessionStepCreateWithoutSessionInput = {
  insights?: string | null
  guideStep: Prisma.GuideStepCreateNestedOneWithoutSessionStepsInput
}

export type SessionStepUncheckedCreateWithoutSessionInput = {
  id?: number
  guideStepId: number
  insights?: string | null
}

export type SessionStepCreateOrConnectWithoutSessionInput = {
  where: Prisma.SessionStepWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionStepCreateWithoutSessionInput, Prisma.SessionStepUncheckedCreateWithoutSessionInput>
}

export type SessionStepCreateManySessionInputEnvelope = {
  data: Prisma.SessionStepCreateManySessionInput | Prisma.SessionStepCreateManySessionInput[]
  skipDuplicates?: boolean
}

export type SessionStepUpsertWithWhereUniqueWithoutSessionInput = {
  where: Prisma.SessionStepWhereUniqueInput
  update: Prisma.XOR<Prisma.SessionStepUpdateWithoutSessionInput, Prisma.SessionStepUncheckedUpdateWithoutSessionInput>
  create: Prisma.XOR<Prisma.SessionStepCreateWithoutSessionInput, Prisma.SessionStepUncheckedCreateWithoutSessionInput>
}

export type SessionStepUpdateWithWhereUniqueWithoutSessionInput = {
  where: Prisma.SessionStepWhereUniqueInput
  data: Prisma.XOR<Prisma.SessionStepUpdateWithoutSessionInput, Prisma.SessionStepUncheckedUpdateWithoutSessionInput>
}

export type SessionStepUpdateManyWithWhereWithoutSessionInput = {
  where: Prisma.SessionStepScalarWhereInput
  data: Prisma.XOR<Prisma.SessionStepUpdateManyMutationInput, Prisma.SessionStepUncheckedUpdateManyWithoutSessionInput>
}

export type SessionStepCreateManyGuideStepInput = {
  id?: number
  sessionId: number
  insights?: string | null
}

export type SessionStepUpdateWithoutGuideStepInput = {
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  session?: Prisma.SessionUpdateOneRequiredWithoutSessionStepsNestedInput
}

export type SessionStepUncheckedUpdateWithoutGuideStepInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sessionId?: Prisma.IntFieldUpdateOperationsInput | number
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SessionStepUncheckedUpdateManyWithoutGuideStepInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  sessionId?: Prisma.IntFieldUpdateOperationsInput | number
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SessionStepCreateManySessionInput = {
  id?: number
  guideStepId: number
  insights?: string | null
}

export type SessionStepUpdateWithoutSessionInput = {
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guideStep?: Prisma.GuideStepUpdateOneRequiredWithoutSessionStepsNestedInput
}

export type SessionStepUncheckedUpdateWithoutSessionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guideStepId?: Prisma.IntFieldUpdateOperationsInput | number
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SessionStepUncheckedUpdateManyWithoutSessionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  guideStepId?: Prisma.IntFieldUpdateOperationsInput | number
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type SessionStepSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  guideStepId?: boolean
  insights?: boolean
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  guideStep?: boolean | Prisma.GuideStepDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sessionStep"]>

export type SessionStepSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  guideStepId?: boolean
  insights?: boolean
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  guideStep?: boolean | Prisma.GuideStepDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sessionStep"]>

export type SessionStepSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  guideStepId?: boolean
  insights?: boolean
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  guideStep?: boolean | Prisma.GuideStepDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sessionStep"]>

export type SessionStepSelectScalar = {
  id?: boolean
  sessionId?: boolean
  guideStepId?: boolean
  insights?: boolean
}

export type SessionStepOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "sessionId" | "guideStepId" | "insights", ExtArgs["result"]["sessionStep"]>
export type SessionStepInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  guideStep?: boolean | Prisma.GuideStepDefaultArgs<ExtArgs>
}
export type SessionStepIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  guideStep?: boolean | Prisma.GuideStepDefaultArgs<ExtArgs>
}
export type SessionStepIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SessionDefaultArgs<ExtArgs>
  guideStep?: boolean | Prisma.GuideStepDefaultArgs<ExtArgs>
}

export type $SessionStepPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SessionStep"
  objects: {
    session: Prisma.$SessionPayload<ExtArgs>
    guideStep: Prisma.$GuideStepPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    sessionId: number
    guideStepId: number
    insights: string | null
  }, ExtArgs["result"]["sessionStep"]>
  composites: {}
}

export type SessionStepGetPayload<S extends boolean | null | undefined | SessionStepDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SessionStepPayload, S>

export type SessionStepCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SessionStepFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SessionStepCountAggregateInputType | true
  }

export interface SessionStepDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SessionStep'], meta: { name: 'SessionStep' } }
  /**
   * Find zero or one SessionStep that matches the filter.
   * @param {SessionStepFindUniqueArgs} args - Arguments to find a SessionStep
   * @example
   * // Get one SessionStep
   * const sessionStep = await prisma.sessionStep.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SessionStepFindUniqueArgs>(args: Prisma.SelectSubset<T, SessionStepFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SessionStepClient<runtime.Types.Result.GetResult<Prisma.$SessionStepPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SessionStep that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SessionStepFindUniqueOrThrowArgs} args - Arguments to find a SessionStep
   * @example
   * // Get one SessionStep
   * const sessionStep = await prisma.sessionStep.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SessionStepFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SessionStepFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SessionStepClient<runtime.Types.Result.GetResult<Prisma.$SessionStepPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SessionStep that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionStepFindFirstArgs} args - Arguments to find a SessionStep
   * @example
   * // Get one SessionStep
   * const sessionStep = await prisma.sessionStep.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SessionStepFindFirstArgs>(args?: Prisma.SelectSubset<T, SessionStepFindFirstArgs<ExtArgs>>): Prisma.Prisma__SessionStepClient<runtime.Types.Result.GetResult<Prisma.$SessionStepPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SessionStep that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionStepFindFirstOrThrowArgs} args - Arguments to find a SessionStep
   * @example
   * // Get one SessionStep
   * const sessionStep = await prisma.sessionStep.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SessionStepFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SessionStepFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SessionStepClient<runtime.Types.Result.GetResult<Prisma.$SessionStepPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SessionSteps that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionStepFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SessionSteps
   * const sessionSteps = await prisma.sessionStep.findMany()
   * 
   * // Get first 10 SessionSteps
   * const sessionSteps = await prisma.sessionStep.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sessionStepWithIdOnly = await prisma.sessionStep.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SessionStepFindManyArgs>(args?: Prisma.SelectSubset<T, SessionStepFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionStepPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SessionStep.
   * @param {SessionStepCreateArgs} args - Arguments to create a SessionStep.
   * @example
   * // Create one SessionStep
   * const SessionStep = await prisma.sessionStep.create({
   *   data: {
   *     // ... data to create a SessionStep
   *   }
   * })
   * 
   */
  create<T extends SessionStepCreateArgs>(args: Prisma.SelectSubset<T, SessionStepCreateArgs<ExtArgs>>): Prisma.Prisma__SessionStepClient<runtime.Types.Result.GetResult<Prisma.$SessionStepPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SessionSteps.
   * @param {SessionStepCreateManyArgs} args - Arguments to create many SessionSteps.
   * @example
   * // Create many SessionSteps
   * const sessionStep = await prisma.sessionStep.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SessionStepCreateManyArgs>(args?: Prisma.SelectSubset<T, SessionStepCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SessionSteps and returns the data saved in the database.
   * @param {SessionStepCreateManyAndReturnArgs} args - Arguments to create many SessionSteps.
   * @example
   * // Create many SessionSteps
   * const sessionStep = await prisma.sessionStep.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SessionSteps and only return the `id`
   * const sessionStepWithIdOnly = await prisma.sessionStep.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SessionStepCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SessionStepCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionStepPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SessionStep.
   * @param {SessionStepDeleteArgs} args - Arguments to delete one SessionStep.
   * @example
   * // Delete one SessionStep
   * const SessionStep = await prisma.sessionStep.delete({
   *   where: {
   *     // ... filter to delete one SessionStep
   *   }
   * })
   * 
   */
  delete<T extends SessionStepDeleteArgs>(args: Prisma.SelectSubset<T, SessionStepDeleteArgs<ExtArgs>>): Prisma.Prisma__SessionStepClient<runtime.Types.Result.GetResult<Prisma.$SessionStepPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SessionStep.
   * @param {SessionStepUpdateArgs} args - Arguments to update one SessionStep.
   * @example
   * // Update one SessionStep
   * const sessionStep = await prisma.sessionStep.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SessionStepUpdateArgs>(args: Prisma.SelectSubset<T, SessionStepUpdateArgs<ExtArgs>>): Prisma.Prisma__SessionStepClient<runtime.Types.Result.GetResult<Prisma.$SessionStepPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SessionSteps.
   * @param {SessionStepDeleteManyArgs} args - Arguments to filter SessionSteps to delete.
   * @example
   * // Delete a few SessionSteps
   * const { count } = await prisma.sessionStep.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SessionStepDeleteManyArgs>(args?: Prisma.SelectSubset<T, SessionStepDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SessionSteps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionStepUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SessionSteps
   * const sessionStep = await prisma.sessionStep.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SessionStepUpdateManyArgs>(args: Prisma.SelectSubset<T, SessionStepUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SessionSteps and returns the data updated in the database.
   * @param {SessionStepUpdateManyAndReturnArgs} args - Arguments to update many SessionSteps.
   * @example
   * // Update many SessionSteps
   * const sessionStep = await prisma.sessionStep.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SessionSteps and only return the `id`
   * const sessionStepWithIdOnly = await prisma.sessionStep.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SessionStepUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SessionStepUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionStepPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SessionStep.
   * @param {SessionStepUpsertArgs} args - Arguments to update or create a SessionStep.
   * @example
   * // Update or create a SessionStep
   * const sessionStep = await prisma.sessionStep.upsert({
   *   create: {
   *     // ... data to create a SessionStep
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SessionStep we want to update
   *   }
   * })
   */
  upsert<T extends SessionStepUpsertArgs>(args: Prisma.SelectSubset<T, SessionStepUpsertArgs<ExtArgs>>): Prisma.Prisma__SessionStepClient<runtime.Types.Result.GetResult<Prisma.$SessionStepPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SessionSteps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionStepCountArgs} args - Arguments to filter SessionSteps to count.
   * @example
   * // Count the number of SessionSteps
   * const count = await prisma.sessionStep.count({
   *   where: {
   *     // ... the filter for the SessionSteps we want to count
   *   }
   * })
  **/
  count<T extends SessionStepCountArgs>(
    args?: Prisma.Subset<T, SessionStepCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SessionStepCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SessionStep.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionStepAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SessionStepAggregateArgs>(args: Prisma.Subset<T, SessionStepAggregateArgs>): Prisma.PrismaPromise<GetSessionStepAggregateType<T>>

  /**
   * Group by SessionStep.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionStepGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SessionStepGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SessionStepGroupByArgs['orderBy'] }
      : { orderBy?: SessionStepGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SessionStepGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSessionStepGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SessionStep model
 */
readonly fields: SessionStepFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SessionStep.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SessionStepClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  session<T extends Prisma.SessionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SessionDefaultArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  guideStep<T extends Prisma.GuideStepDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GuideStepDefaultArgs<ExtArgs>>): Prisma.Prisma__GuideStepClient<runtime.Types.Result.GetResult<Prisma.$GuideStepPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SessionStep model
 */
export interface SessionStepFieldRefs {
  readonly id: Prisma.FieldRef<"SessionStep", 'Int'>
  readonly sessionId: Prisma.FieldRef<"SessionStep", 'Int'>
  readonly guideStepId: Prisma.FieldRef<"SessionStep", 'Int'>
  readonly insights: Prisma.FieldRef<"SessionStep", 'String'>
}
    

// Custom InputTypes
/**
 * SessionStep findUnique
 */
export type SessionStepFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionStep
   */
  select?: Prisma.SessionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionStep
   */
  omit?: Prisma.SessionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionStepInclude<ExtArgs> | null
  /**
   * Filter, which SessionStep to fetch.
   */
  where: Prisma.SessionStepWhereUniqueInput
}

/**
 * SessionStep findUniqueOrThrow
 */
export type SessionStepFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionStep
   */
  select?: Prisma.SessionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionStep
   */
  omit?: Prisma.SessionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionStepInclude<ExtArgs> | null
  /**
   * Filter, which SessionStep to fetch.
   */
  where: Prisma.SessionStepWhereUniqueInput
}

/**
 * SessionStep findFirst
 */
export type SessionStepFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionStep
   */
  select?: Prisma.SessionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionStep
   */
  omit?: Prisma.SessionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionStepInclude<ExtArgs> | null
  /**
   * Filter, which SessionStep to fetch.
   */
  where?: Prisma.SessionStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionSteps to fetch.
   */
  orderBy?: Prisma.SessionStepOrderByWithRelationInput | Prisma.SessionStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SessionSteps.
   */
  cursor?: Prisma.SessionStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionSteps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SessionSteps.
   */
  distinct?: Prisma.SessionStepScalarFieldEnum | Prisma.SessionStepScalarFieldEnum[]
}

/**
 * SessionStep findFirstOrThrow
 */
export type SessionStepFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionStep
   */
  select?: Prisma.SessionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionStep
   */
  omit?: Prisma.SessionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionStepInclude<ExtArgs> | null
  /**
   * Filter, which SessionStep to fetch.
   */
  where?: Prisma.SessionStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionSteps to fetch.
   */
  orderBy?: Prisma.SessionStepOrderByWithRelationInput | Prisma.SessionStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SessionSteps.
   */
  cursor?: Prisma.SessionStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionSteps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SessionSteps.
   */
  distinct?: Prisma.SessionStepScalarFieldEnum | Prisma.SessionStepScalarFieldEnum[]
}

/**
 * SessionStep findMany
 */
export type SessionStepFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionStep
   */
  select?: Prisma.SessionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionStep
   */
  omit?: Prisma.SessionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionStepInclude<ExtArgs> | null
  /**
   * Filter, which SessionSteps to fetch.
   */
  where?: Prisma.SessionStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionSteps to fetch.
   */
  orderBy?: Prisma.SessionStepOrderByWithRelationInput | Prisma.SessionStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SessionSteps.
   */
  cursor?: Prisma.SessionStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionSteps.
   */
  skip?: number
  distinct?: Prisma.SessionStepScalarFieldEnum | Prisma.SessionStepScalarFieldEnum[]
}

/**
 * SessionStep create
 */
export type SessionStepCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionStep
   */
  select?: Prisma.SessionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionStep
   */
  omit?: Prisma.SessionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionStepInclude<ExtArgs> | null
  /**
   * The data needed to create a SessionStep.
   */
  data: Prisma.XOR<Prisma.SessionStepCreateInput, Prisma.SessionStepUncheckedCreateInput>
}

/**
 * SessionStep createMany
 */
export type SessionStepCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SessionSteps.
   */
  data: Prisma.SessionStepCreateManyInput | Prisma.SessionStepCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SessionStep createManyAndReturn
 */
export type SessionStepCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionStep
   */
  select?: Prisma.SessionStepSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SessionStep
   */
  omit?: Prisma.SessionStepOmit<ExtArgs> | null
  /**
   * The data used to create many SessionSteps.
   */
  data: Prisma.SessionStepCreateManyInput | Prisma.SessionStepCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionStepIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SessionStep update
 */
export type SessionStepUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionStep
   */
  select?: Prisma.SessionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionStep
   */
  omit?: Prisma.SessionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionStepInclude<ExtArgs> | null
  /**
   * The data needed to update a SessionStep.
   */
  data: Prisma.XOR<Prisma.SessionStepUpdateInput, Prisma.SessionStepUncheckedUpdateInput>
  /**
   * Choose, which SessionStep to update.
   */
  where: Prisma.SessionStepWhereUniqueInput
}

/**
 * SessionStep updateMany
 */
export type SessionStepUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SessionSteps.
   */
  data: Prisma.XOR<Prisma.SessionStepUpdateManyMutationInput, Prisma.SessionStepUncheckedUpdateManyInput>
  /**
   * Filter which SessionSteps to update
   */
  where?: Prisma.SessionStepWhereInput
  /**
   * Limit how many SessionSteps to update.
   */
  limit?: number
}

/**
 * SessionStep updateManyAndReturn
 */
export type SessionStepUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionStep
   */
  select?: Prisma.SessionStepSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SessionStep
   */
  omit?: Prisma.SessionStepOmit<ExtArgs> | null
  /**
   * The data used to update SessionSteps.
   */
  data: Prisma.XOR<Prisma.SessionStepUpdateManyMutationInput, Prisma.SessionStepUncheckedUpdateManyInput>
  /**
   * Filter which SessionSteps to update
   */
  where?: Prisma.SessionStepWhereInput
  /**
   * Limit how many SessionSteps to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionStepIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SessionStep upsert
 */
export type SessionStepUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionStep
   */
  select?: Prisma.SessionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionStep
   */
  omit?: Prisma.SessionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionStepInclude<ExtArgs> | null
  /**
   * The filter to search for the SessionStep to update in case it exists.
   */
  where: Prisma.SessionStepWhereUniqueInput
  /**
   * In case the SessionStep found by the `where` argument doesn't exist, create a new SessionStep with this data.
   */
  create: Prisma.XOR<Prisma.SessionStepCreateInput, Prisma.SessionStepUncheckedCreateInput>
  /**
   * In case the SessionStep was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SessionStepUpdateInput, Prisma.SessionStepUncheckedUpdateInput>
}

/**
 * SessionStep delete
 */
export type SessionStepDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionStep
   */
  select?: Prisma.SessionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionStep
   */
  omit?: Prisma.SessionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionStepInclude<ExtArgs> | null
  /**
   * Filter which SessionStep to delete.
   */
  where: Prisma.SessionStepWhereUniqueInput
}

/**
 * SessionStep deleteMany
 */
export type SessionStepDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SessionSteps to delete
   */
  where?: Prisma.SessionStepWhereInput
  /**
   * Limit how many SessionSteps to delete.
   */
  limit?: number
}

/**
 * SessionStep without action
 */
export type SessionStepDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionStep
   */
  select?: Prisma.SessionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionStep
   */
  omit?: Prisma.SessionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionStepInclude<ExtArgs> | null
}
