
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Session` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Session
 * 
 */
export type SessionModel = runtime.Types.Result.DefaultSelection<Prisma.$SessionPayload>

export type AggregateSession = {
  _count: SessionCountAggregateOutputType | null
  _avg: SessionAvgAggregateOutputType | null
  _sum: SessionSumAggregateOutputType | null
  _min: SessionMinAggregateOutputType | null
  _max: SessionMaxAggregateOutputType | null
}

export type SessionAvgAggregateOutputType = {
  id: number | null
  studyId: number | null
  stepId: number | null
  selectionId: number | null
}

export type SessionSumAggregateOutputType = {
  id: number | null
  studyId: number | null
  stepId: number | null
  selectionId: number | null
}

export type SessionMinAggregateOutputType = {
  id: number | null
  studyId: number | null
  stepId: number | null
  selectionId: number | null
  date: Date | null
  time: Date | null
  insights: string | null
  reference: string | null
}

export type SessionMaxAggregateOutputType = {
  id: number | null
  studyId: number | null
  stepId: number | null
  selectionId: number | null
  date: Date | null
  time: Date | null
  insights: string | null
  reference: string | null
}

export type SessionCountAggregateOutputType = {
  id: number
  studyId: number
  stepId: number
  selectionId: number
  date: number
  time: number
  insights: number
  reference: number
  _all: number
}


export type SessionAvgAggregateInputType = {
  id?: true
  studyId?: true
  stepId?: true
  selectionId?: true
}

export type SessionSumAggregateInputType = {
  id?: true
  studyId?: true
  stepId?: true
  selectionId?: true
}

export type SessionMinAggregateInputType = {
  id?: true
  studyId?: true
  stepId?: true
  selectionId?: true
  date?: true
  time?: true
  insights?: true
  reference?: true
}

export type SessionMaxAggregateInputType = {
  id?: true
  studyId?: true
  stepId?: true
  selectionId?: true
  date?: true
  time?: true
  insights?: true
  reference?: true
}

export type SessionCountAggregateInputType = {
  id?: true
  studyId?: true
  stepId?: true
  selectionId?: true
  date?: true
  time?: true
  insights?: true
  reference?: true
  _all?: true
}

export type SessionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Session to aggregate.
   */
  where?: Prisma.SessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sessions to fetch.
   */
  orderBy?: Prisma.SessionOrderByWithRelationInput | Prisma.SessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Sessions
  **/
  _count?: true | SessionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SessionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SessionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SessionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SessionMaxAggregateInputType
}

export type GetSessionAggregateType<T extends SessionAggregateArgs> = {
      [P in keyof T & keyof AggregateSession]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSession[P]>
    : Prisma.GetScalarType<T[P], AggregateSession[P]>
}




export type SessionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionWhereInput
  orderBy?: Prisma.SessionOrderByWithAggregationInput | Prisma.SessionOrderByWithAggregationInput[]
  by: Prisma.SessionScalarFieldEnum[] | Prisma.SessionScalarFieldEnum
  having?: Prisma.SessionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SessionCountAggregateInputType | true
  _avg?: SessionAvgAggregateInputType
  _sum?: SessionSumAggregateInputType
  _min?: SessionMinAggregateInputType
  _max?: SessionMaxAggregateInputType
}

export type SessionGroupByOutputType = {
  id: number
  studyId: number
  stepId: number | null
  selectionId: number | null
  date: Date | null
  time: Date | null
  insights: string | null
  reference: string | null
  _count: SessionCountAggregateOutputType | null
  _avg: SessionAvgAggregateOutputType | null
  _sum: SessionSumAggregateOutputType | null
  _min: SessionMinAggregateOutputType | null
  _max: SessionMaxAggregateOutputType | null
}

type GetSessionGroupByPayload<T extends SessionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SessionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SessionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SessionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SessionGroupByOutputType[P]>
      }
    >
  >



export type SessionWhereInput = {
  AND?: Prisma.SessionWhereInput | Prisma.SessionWhereInput[]
  OR?: Prisma.SessionWhereInput[]
  NOT?: Prisma.SessionWhereInput | Prisma.SessionWhereInput[]
  id?: Prisma.IntFilter<"Session"> | number
  studyId?: Prisma.IntFilter<"Session"> | number
  stepId?: Prisma.IntNullableFilter<"Session"> | number | null
  selectionId?: Prisma.IntNullableFilter<"Session"> | number | null
  date?: Prisma.DateTimeNullableFilter<"Session"> | Date | string | null
  time?: Prisma.DateTimeNullableFilter<"Session"> | Date | string | null
  insights?: Prisma.StringNullableFilter<"Session"> | string | null
  reference?: Prisma.StringNullableFilter<"Session"> | string | null
  study?: Prisma.XOR<Prisma.StudyScalarRelationFilter, Prisma.StudyWhereInput>
  guideStep?: Prisma.XOR<Prisma.GuideStepNullableScalarRelationFilter, Prisma.GuideStepWhereInput> | null
  selection?: Prisma.XOR<Prisma.SelectionNullableScalarRelationFilter, Prisma.SelectionWhereInput> | null
  sessionSteps?: Prisma.SessionStepListRelationFilter
}

export type SessionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  studyId?: Prisma.SortOrder
  stepId?: Prisma.SortOrderInput | Prisma.SortOrder
  selectionId?: Prisma.SortOrderInput | Prisma.SortOrder
  date?: Prisma.SortOrderInput | Prisma.SortOrder
  time?: Prisma.SortOrderInput | Prisma.SortOrder
  insights?: Prisma.SortOrderInput | Prisma.SortOrder
  reference?: Prisma.SortOrderInput | Prisma.SortOrder
  study?: Prisma.StudyOrderByWithRelationInput
  guideStep?: Prisma.GuideStepOrderByWithRelationInput
  selection?: Prisma.SelectionOrderByWithRelationInput
  sessionSteps?: Prisma.SessionStepOrderByRelationAggregateInput
}

export type SessionWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.SessionWhereInput | Prisma.SessionWhereInput[]
  OR?: Prisma.SessionWhereInput[]
  NOT?: Prisma.SessionWhereInput | Prisma.SessionWhereInput[]
  studyId?: Prisma.IntFilter<"Session"> | number
  stepId?: Prisma.IntNullableFilter<"Session"> | number | null
  selectionId?: Prisma.IntNullableFilter<"Session"> | number | null
  date?: Prisma.DateTimeNullableFilter<"Session"> | Date | string | null
  time?: Prisma.DateTimeNullableFilter<"Session"> | Date | string | null
  insights?: Prisma.StringNullableFilter<"Session"> | string | null
  reference?: Prisma.StringNullableFilter<"Session"> | string | null
  study?: Prisma.XOR<Prisma.StudyScalarRelationFilter, Prisma.StudyWhereInput>
  guideStep?: Prisma.XOR<Prisma.GuideStepNullableScalarRelationFilter, Prisma.GuideStepWhereInput> | null
  selection?: Prisma.XOR<Prisma.SelectionNullableScalarRelationFilter, Prisma.SelectionWhereInput> | null
  sessionSteps?: Prisma.SessionStepListRelationFilter
}, "id">

export type SessionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  studyId?: Prisma.SortOrder
  stepId?: Prisma.SortOrderInput | Prisma.SortOrder
  selectionId?: Prisma.SortOrderInput | Prisma.SortOrder
  date?: Prisma.SortOrderInput | Prisma.SortOrder
  time?: Prisma.SortOrderInput | Prisma.SortOrder
  insights?: Prisma.SortOrderInput | Prisma.SortOrder
  reference?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.SessionCountOrderByAggregateInput
  _avg?: Prisma.SessionAvgOrderByAggregateInput
  _max?: Prisma.SessionMaxOrderByAggregateInput
  _min?: Prisma.SessionMinOrderByAggregateInput
  _sum?: Prisma.SessionSumOrderByAggregateInput
}

export type SessionScalarWhereWithAggregatesInput = {
  AND?: Prisma.SessionScalarWhereWithAggregatesInput | Prisma.SessionScalarWhereWithAggregatesInput[]
  OR?: Prisma.SessionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SessionScalarWhereWithAggregatesInput | Prisma.SessionScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Session"> | number
  studyId?: Prisma.IntWithAggregatesFilter<"Session"> | number
  stepId?: Prisma.IntNullableWithAggregatesFilter<"Session"> | number | null
  selectionId?: Prisma.IntNullableWithAggregatesFilter<"Session"> | number | null
  date?: Prisma.DateTimeNullableWithAggregatesFilter<"Session"> | Date | string | null
  time?: Prisma.DateTimeNullableWithAggregatesFilter<"Session"> | Date | string | null
  insights?: Prisma.StringNullableWithAggregatesFilter<"Session"> | string | null
  reference?: Prisma.StringNullableWithAggregatesFilter<"Session"> | string | null
}

export type SessionCreateInput = {
  date?: Date | string | null
  time?: Date | string | null
  insights?: string | null
  reference?: string | null
  study: Prisma.StudyCreateNestedOneWithoutSessionsInput
  guideStep?: Prisma.GuideStepCreateNestedOneWithoutSessionsInput
  selection?: Prisma.SelectionCreateNestedOneWithoutSessionsInput
  sessionSteps?: Prisma.SessionStepCreateNestedManyWithoutSessionInput
}

export type SessionUncheckedCreateInput = {
  id?: number
  studyId: number
  stepId?: number | null
  selectionId?: number | null
  date?: Date | string | null
  time?: Date | string | null
  insights?: string | null
  reference?: string | null
  sessionSteps?: Prisma.SessionStepUncheckedCreateNestedManyWithoutSessionInput
}

export type SessionUpdateInput = {
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  study?: Prisma.StudyUpdateOneRequiredWithoutSessionsNestedInput
  guideStep?: Prisma.GuideStepUpdateOneWithoutSessionsNestedInput
  selection?: Prisma.SelectionUpdateOneWithoutSessionsNestedInput
  sessionSteps?: Prisma.SessionStepUpdateManyWithoutSessionNestedInput
}

export type SessionUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studyId?: Prisma.IntFieldUpdateOperationsInput | number
  stepId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  selectionId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sessionSteps?: Prisma.SessionStepUncheckedUpdateManyWithoutSessionNestedInput
}

export type SessionCreateManyInput = {
  id?: number
  studyId: number
  stepId?: number | null
  selectionId?: number | null
  date?: Date | string | null
  time?: Date | string | null
  insights?: string | null
  reference?: string | null
}

export type SessionUpdateManyMutationInput = {
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SessionUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studyId?: Prisma.IntFieldUpdateOperationsInput | number
  stepId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  selectionId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SessionListRelationFilter = {
  every?: Prisma.SessionWhereInput
  some?: Prisma.SessionWhereInput
  none?: Prisma.SessionWhereInput
}

export type SessionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SessionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studyId?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  selectionId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  time?: Prisma.SortOrder
  insights?: Prisma.SortOrder
  reference?: Prisma.SortOrder
}

export type SessionAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studyId?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  selectionId?: Prisma.SortOrder
}

export type SessionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studyId?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  selectionId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  time?: Prisma.SortOrder
  insights?: Prisma.SortOrder
  reference?: Prisma.SortOrder
}

export type SessionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studyId?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  selectionId?: Prisma.SortOrder
  date?: Prisma.SortOrder
  time?: Prisma.SortOrder
  insights?: Prisma.SortOrder
  reference?: Prisma.SortOrder
}

export type SessionSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  studyId?: Prisma.SortOrder
  stepId?: Prisma.SortOrder
  selectionId?: Prisma.SortOrder
}

export type SessionScalarRelationFilter = {
  is?: Prisma.SessionWhereInput
  isNot?: Prisma.SessionWhereInput
}

export type SessionCreateNestedManyWithoutStudyInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutStudyInput, Prisma.SessionUncheckedCreateWithoutStudyInput> | Prisma.SessionCreateWithoutStudyInput[] | Prisma.SessionUncheckedCreateWithoutStudyInput[]
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutStudyInput | Prisma.SessionCreateOrConnectWithoutStudyInput[]
  createMany?: Prisma.SessionCreateManyStudyInputEnvelope
  connect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
}

export type SessionUncheckedCreateNestedManyWithoutStudyInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutStudyInput, Prisma.SessionUncheckedCreateWithoutStudyInput> | Prisma.SessionCreateWithoutStudyInput[] | Prisma.SessionUncheckedCreateWithoutStudyInput[]
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutStudyInput | Prisma.SessionCreateOrConnectWithoutStudyInput[]
  createMany?: Prisma.SessionCreateManyStudyInputEnvelope
  connect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
}

export type SessionUpdateManyWithoutStudyNestedInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutStudyInput, Prisma.SessionUncheckedCreateWithoutStudyInput> | Prisma.SessionCreateWithoutStudyInput[] | Prisma.SessionUncheckedCreateWithoutStudyInput[]
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutStudyInput | Prisma.SessionCreateOrConnectWithoutStudyInput[]
  upsert?: Prisma.SessionUpsertWithWhereUniqueWithoutStudyInput | Prisma.SessionUpsertWithWhereUniqueWithoutStudyInput[]
  createMany?: Prisma.SessionCreateManyStudyInputEnvelope
  set?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  disconnect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  delete?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  connect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  update?: Prisma.SessionUpdateWithWhereUniqueWithoutStudyInput | Prisma.SessionUpdateWithWhereUniqueWithoutStudyInput[]
  updateMany?: Prisma.SessionUpdateManyWithWhereWithoutStudyInput | Prisma.SessionUpdateManyWithWhereWithoutStudyInput[]
  deleteMany?: Prisma.SessionScalarWhereInput | Prisma.SessionScalarWhereInput[]
}

export type SessionUncheckedUpdateManyWithoutStudyNestedInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutStudyInput, Prisma.SessionUncheckedCreateWithoutStudyInput> | Prisma.SessionCreateWithoutStudyInput[] | Prisma.SessionUncheckedCreateWithoutStudyInput[]
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutStudyInput | Prisma.SessionCreateOrConnectWithoutStudyInput[]
  upsert?: Prisma.SessionUpsertWithWhereUniqueWithoutStudyInput | Prisma.SessionUpsertWithWhereUniqueWithoutStudyInput[]
  createMany?: Prisma.SessionCreateManyStudyInputEnvelope
  set?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  disconnect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  delete?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  connect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  update?: Prisma.SessionUpdateWithWhereUniqueWithoutStudyInput | Prisma.SessionUpdateWithWhereUniqueWithoutStudyInput[]
  updateMany?: Prisma.SessionUpdateManyWithWhereWithoutStudyInput | Prisma.SessionUpdateManyWithWhereWithoutStudyInput[]
  deleteMany?: Prisma.SessionScalarWhereInput | Prisma.SessionScalarWhereInput[]
}

export type SessionCreateNestedManyWithoutSelectionInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutSelectionInput, Prisma.SessionUncheckedCreateWithoutSelectionInput> | Prisma.SessionCreateWithoutSelectionInput[] | Prisma.SessionUncheckedCreateWithoutSelectionInput[]
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutSelectionInput | Prisma.SessionCreateOrConnectWithoutSelectionInput[]
  createMany?: Prisma.SessionCreateManySelectionInputEnvelope
  connect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
}

export type SessionUncheckedCreateNestedManyWithoutSelectionInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutSelectionInput, Prisma.SessionUncheckedCreateWithoutSelectionInput> | Prisma.SessionCreateWithoutSelectionInput[] | Prisma.SessionUncheckedCreateWithoutSelectionInput[]
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutSelectionInput | Prisma.SessionCreateOrConnectWithoutSelectionInput[]
  createMany?: Prisma.SessionCreateManySelectionInputEnvelope
  connect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
}

export type SessionUpdateManyWithoutSelectionNestedInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutSelectionInput, Prisma.SessionUncheckedCreateWithoutSelectionInput> | Prisma.SessionCreateWithoutSelectionInput[] | Prisma.SessionUncheckedCreateWithoutSelectionInput[]
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutSelectionInput | Prisma.SessionCreateOrConnectWithoutSelectionInput[]
  upsert?: Prisma.SessionUpsertWithWhereUniqueWithoutSelectionInput | Prisma.SessionUpsertWithWhereUniqueWithoutSelectionInput[]
  createMany?: Prisma.SessionCreateManySelectionInputEnvelope
  set?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  disconnect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  delete?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  connect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  update?: Prisma.SessionUpdateWithWhereUniqueWithoutSelectionInput | Prisma.SessionUpdateWithWhereUniqueWithoutSelectionInput[]
  updateMany?: Prisma.SessionUpdateManyWithWhereWithoutSelectionInput | Prisma.SessionUpdateManyWithWhereWithoutSelectionInput[]
  deleteMany?: Prisma.SessionScalarWhereInput | Prisma.SessionScalarWhereInput[]
}

export type SessionUncheckedUpdateManyWithoutSelectionNestedInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutSelectionInput, Prisma.SessionUncheckedCreateWithoutSelectionInput> | Prisma.SessionCreateWithoutSelectionInput[] | Prisma.SessionUncheckedCreateWithoutSelectionInput[]
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutSelectionInput | Prisma.SessionCreateOrConnectWithoutSelectionInput[]
  upsert?: Prisma.SessionUpsertWithWhereUniqueWithoutSelectionInput | Prisma.SessionUpsertWithWhereUniqueWithoutSelectionInput[]
  createMany?: Prisma.SessionCreateManySelectionInputEnvelope
  set?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  disconnect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  delete?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  connect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  update?: Prisma.SessionUpdateWithWhereUniqueWithoutSelectionInput | Prisma.SessionUpdateWithWhereUniqueWithoutSelectionInput[]
  updateMany?: Prisma.SessionUpdateManyWithWhereWithoutSelectionInput | Prisma.SessionUpdateManyWithWhereWithoutSelectionInput[]
  deleteMany?: Prisma.SessionScalarWhereInput | Prisma.SessionScalarWhereInput[]
}

export type SessionCreateNestedManyWithoutGuideStepInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutGuideStepInput, Prisma.SessionUncheckedCreateWithoutGuideStepInput> | Prisma.SessionCreateWithoutGuideStepInput[] | Prisma.SessionUncheckedCreateWithoutGuideStepInput[]
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutGuideStepInput | Prisma.SessionCreateOrConnectWithoutGuideStepInput[]
  createMany?: Prisma.SessionCreateManyGuideStepInputEnvelope
  connect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
}

export type SessionUncheckedCreateNestedManyWithoutGuideStepInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutGuideStepInput, Prisma.SessionUncheckedCreateWithoutGuideStepInput> | Prisma.SessionCreateWithoutGuideStepInput[] | Prisma.SessionUncheckedCreateWithoutGuideStepInput[]
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutGuideStepInput | Prisma.SessionCreateOrConnectWithoutGuideStepInput[]
  createMany?: Prisma.SessionCreateManyGuideStepInputEnvelope
  connect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
}

export type SessionUpdateManyWithoutGuideStepNestedInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutGuideStepInput, Prisma.SessionUncheckedCreateWithoutGuideStepInput> | Prisma.SessionCreateWithoutGuideStepInput[] | Prisma.SessionUncheckedCreateWithoutGuideStepInput[]
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutGuideStepInput | Prisma.SessionCreateOrConnectWithoutGuideStepInput[]
  upsert?: Prisma.SessionUpsertWithWhereUniqueWithoutGuideStepInput | Prisma.SessionUpsertWithWhereUniqueWithoutGuideStepInput[]
  createMany?: Prisma.SessionCreateManyGuideStepInputEnvelope
  set?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  disconnect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  delete?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  connect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  update?: Prisma.SessionUpdateWithWhereUniqueWithoutGuideStepInput | Prisma.SessionUpdateWithWhereUniqueWithoutGuideStepInput[]
  updateMany?: Prisma.SessionUpdateManyWithWhereWithoutGuideStepInput | Prisma.SessionUpdateManyWithWhereWithoutGuideStepInput[]
  deleteMany?: Prisma.SessionScalarWhereInput | Prisma.SessionScalarWhereInput[]
}

export type SessionUncheckedUpdateManyWithoutGuideStepNestedInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutGuideStepInput, Prisma.SessionUncheckedCreateWithoutGuideStepInput> | Prisma.SessionCreateWithoutGuideStepInput[] | Prisma.SessionUncheckedCreateWithoutGuideStepInput[]
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutGuideStepInput | Prisma.SessionCreateOrConnectWithoutGuideStepInput[]
  upsert?: Prisma.SessionUpsertWithWhereUniqueWithoutGuideStepInput | Prisma.SessionUpsertWithWhereUniqueWithoutGuideStepInput[]
  createMany?: Prisma.SessionCreateManyGuideStepInputEnvelope
  set?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  disconnect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  delete?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  connect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  update?: Prisma.SessionUpdateWithWhereUniqueWithoutGuideStepInput | Prisma.SessionUpdateWithWhereUniqueWithoutGuideStepInput[]
  updateMany?: Prisma.SessionUpdateManyWithWhereWithoutGuideStepInput | Prisma.SessionUpdateManyWithWhereWithoutGuideStepInput[]
  deleteMany?: Prisma.SessionScalarWhereInput | Prisma.SessionScalarWhereInput[]
}

export type SessionCreateNestedOneWithoutSessionStepsInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutSessionStepsInput, Prisma.SessionUncheckedCreateWithoutSessionStepsInput>
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutSessionStepsInput
  connect?: Prisma.SessionWhereUniqueInput
}

export type SessionUpdateOneRequiredWithoutSessionStepsNestedInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutSessionStepsInput, Prisma.SessionUncheckedCreateWithoutSessionStepsInput>
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutSessionStepsInput
  upsert?: Prisma.SessionUpsertWithoutSessionStepsInput
  connect?: Prisma.SessionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SessionUpdateToOneWithWhereWithoutSessionStepsInput, Prisma.SessionUpdateWithoutSessionStepsInput>, Prisma.SessionUncheckedUpdateWithoutSessionStepsInput>
}

export type SessionCreateWithoutStudyInput = {
  date?: Date | string | null
  time?: Date | string | null
  insights?: string | null
  reference?: string | null
  guideStep?: Prisma.GuideStepCreateNestedOneWithoutSessionsInput
  selection?: Prisma.SelectionCreateNestedOneWithoutSessionsInput
  sessionSteps?: Prisma.SessionStepCreateNestedManyWithoutSessionInput
}

export type SessionUncheckedCreateWithoutStudyInput = {
  id?: number
  stepId?: number | null
  selectionId?: number | null
  date?: Date | string | null
  time?: Date | string | null
  insights?: string | null
  reference?: string | null
  sessionSteps?: Prisma.SessionStepUncheckedCreateNestedManyWithoutSessionInput
}

export type SessionCreateOrConnectWithoutStudyInput = {
  where: Prisma.SessionWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionCreateWithoutStudyInput, Prisma.SessionUncheckedCreateWithoutStudyInput>
}

export type SessionCreateManyStudyInputEnvelope = {
  data: Prisma.SessionCreateManyStudyInput | Prisma.SessionCreateManyStudyInput[]
  skipDuplicates?: boolean
}

export type SessionUpsertWithWhereUniqueWithoutStudyInput = {
  where: Prisma.SessionWhereUniqueInput
  update: Prisma.XOR<Prisma.SessionUpdateWithoutStudyInput, Prisma.SessionUncheckedUpdateWithoutStudyInput>
  create: Prisma.XOR<Prisma.SessionCreateWithoutStudyInput, Prisma.SessionUncheckedCreateWithoutStudyInput>
}

export type SessionUpdateWithWhereUniqueWithoutStudyInput = {
  where: Prisma.SessionWhereUniqueInput
  data: Prisma.XOR<Prisma.SessionUpdateWithoutStudyInput, Prisma.SessionUncheckedUpdateWithoutStudyInput>
}

export type SessionUpdateManyWithWhereWithoutStudyInput = {
  where: Prisma.SessionScalarWhereInput
  data: Prisma.XOR<Prisma.SessionUpdateManyMutationInput, Prisma.SessionUncheckedUpdateManyWithoutStudyInput>
}

export type SessionScalarWhereInput = {
  AND?: Prisma.SessionScalarWhereInput | Prisma.SessionScalarWhereInput[]
  OR?: Prisma.SessionScalarWhereInput[]
  NOT?: Prisma.SessionScalarWhereInput | Prisma.SessionScalarWhereInput[]
  id?: Prisma.IntFilter<"Session"> | number
  studyId?: Prisma.IntFilter<"Session"> | number
  stepId?: Prisma.IntNullableFilter<"Session"> | number | null
  selectionId?: Prisma.IntNullableFilter<"Session"> | number | null
  date?: Prisma.DateTimeNullableFilter<"Session"> | Date | string | null
  time?: Prisma.DateTimeNullableFilter<"Session"> | Date | string | null
  insights?: Prisma.StringNullableFilter<"Session"> | string | null
  reference?: Prisma.StringNullableFilter<"Session"> | string | null
}

export type SessionCreateWithoutSelectionInput = {
  date?: Date | string | null
  time?: Date | string | null
  insights?: string | null
  reference?: string | null
  study: Prisma.StudyCreateNestedOneWithoutSessionsInput
  guideStep?: Prisma.GuideStepCreateNestedOneWithoutSessionsInput
  sessionSteps?: Prisma.SessionStepCreateNestedManyWithoutSessionInput
}

export type SessionUncheckedCreateWithoutSelectionInput = {
  id?: number
  studyId: number
  stepId?: number | null
  date?: Date | string | null
  time?: Date | string | null
  insights?: string | null
  reference?: string | null
  sessionSteps?: Prisma.SessionStepUncheckedCreateNestedManyWithoutSessionInput
}

export type SessionCreateOrConnectWithoutSelectionInput = {
  where: Prisma.SessionWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionCreateWithoutSelectionInput, Prisma.SessionUncheckedCreateWithoutSelectionInput>
}

export type SessionCreateManySelectionInputEnvelope = {
  data: Prisma.SessionCreateManySelectionInput | Prisma.SessionCreateManySelectionInput[]
  skipDuplicates?: boolean
}

export type SessionUpsertWithWhereUniqueWithoutSelectionInput = {
  where: Prisma.SessionWhereUniqueInput
  update: Prisma.XOR<Prisma.SessionUpdateWithoutSelectionInput, Prisma.SessionUncheckedUpdateWithoutSelectionInput>
  create: Prisma.XOR<Prisma.SessionCreateWithoutSelectionInput, Prisma.SessionUncheckedCreateWithoutSelectionInput>
}

export type SessionUpdateWithWhereUniqueWithoutSelectionInput = {
  where: Prisma.SessionWhereUniqueInput
  data: Prisma.XOR<Prisma.SessionUpdateWithoutSelectionInput, Prisma.SessionUncheckedUpdateWithoutSelectionInput>
}

export type SessionUpdateManyWithWhereWithoutSelectionInput = {
  where: Prisma.SessionScalarWhereInput
  data: Prisma.XOR<Prisma.SessionUpdateManyMutationInput, Prisma.SessionUncheckedUpdateManyWithoutSelectionInput>
}

export type SessionCreateWithoutGuideStepInput = {
  date?: Date | string | null
  time?: Date | string | null
  insights?: string | null
  reference?: string | null
  study: Prisma.StudyCreateNestedOneWithoutSessionsInput
  selection?: Prisma.SelectionCreateNestedOneWithoutSessionsInput
  sessionSteps?: Prisma.SessionStepCreateNestedManyWithoutSessionInput
}

export type SessionUncheckedCreateWithoutGuideStepInput = {
  id?: number
  studyId: number
  selectionId?: number | null
  date?: Date | string | null
  time?: Date | string | null
  insights?: string | null
  reference?: string | null
  sessionSteps?: Prisma.SessionStepUncheckedCreateNestedManyWithoutSessionInput
}

export type SessionCreateOrConnectWithoutGuideStepInput = {
  where: Prisma.SessionWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionCreateWithoutGuideStepInput, Prisma.SessionUncheckedCreateWithoutGuideStepInput>
}

export type SessionCreateManyGuideStepInputEnvelope = {
  data: Prisma.SessionCreateManyGuideStepInput | Prisma.SessionCreateManyGuideStepInput[]
  skipDuplicates?: boolean
}

export type SessionUpsertWithWhereUniqueWithoutGuideStepInput = {
  where: Prisma.SessionWhereUniqueInput
  update: Prisma.XOR<Prisma.SessionUpdateWithoutGuideStepInput, Prisma.SessionUncheckedUpdateWithoutGuideStepInput>
  create: Prisma.XOR<Prisma.SessionCreateWithoutGuideStepInput, Prisma.SessionUncheckedCreateWithoutGuideStepInput>
}

export type SessionUpdateWithWhereUniqueWithoutGuideStepInput = {
  where: Prisma.SessionWhereUniqueInput
  data: Prisma.XOR<Prisma.SessionUpdateWithoutGuideStepInput, Prisma.SessionUncheckedUpdateWithoutGuideStepInput>
}

export type SessionUpdateManyWithWhereWithoutGuideStepInput = {
  where: Prisma.SessionScalarWhereInput
  data: Prisma.XOR<Prisma.SessionUpdateManyMutationInput, Prisma.SessionUncheckedUpdateManyWithoutGuideStepInput>
}

export type SessionCreateWithoutSessionStepsInput = {
  date?: Date | string | null
  time?: Date | string | null
  insights?: string | null
  reference?: string | null
  study: Prisma.StudyCreateNestedOneWithoutSessionsInput
  guideStep?: Prisma.GuideStepCreateNestedOneWithoutSessionsInput
  selection?: Prisma.SelectionCreateNestedOneWithoutSessionsInput
}

export type SessionUncheckedCreateWithoutSessionStepsInput = {
  id?: number
  studyId: number
  stepId?: number | null
  selectionId?: number | null
  date?: Date | string | null
  time?: Date | string | null
  insights?: string | null
  reference?: string | null
}

export type SessionCreateOrConnectWithoutSessionStepsInput = {
  where: Prisma.SessionWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionCreateWithoutSessionStepsInput, Prisma.SessionUncheckedCreateWithoutSessionStepsInput>
}

export type SessionUpsertWithoutSessionStepsInput = {
  update: Prisma.XOR<Prisma.SessionUpdateWithoutSessionStepsInput, Prisma.SessionUncheckedUpdateWithoutSessionStepsInput>
  create: Prisma.XOR<Prisma.SessionCreateWithoutSessionStepsInput, Prisma.SessionUncheckedCreateWithoutSessionStepsInput>
  where?: Prisma.SessionWhereInput
}

export type SessionUpdateToOneWithWhereWithoutSessionStepsInput = {
  where?: Prisma.SessionWhereInput
  data: Prisma.XOR<Prisma.SessionUpdateWithoutSessionStepsInput, Prisma.SessionUncheckedUpdateWithoutSessionStepsInput>
}

export type SessionUpdateWithoutSessionStepsInput = {
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  study?: Prisma.StudyUpdateOneRequiredWithoutSessionsNestedInput
  guideStep?: Prisma.GuideStepUpdateOneWithoutSessionsNestedInput
  selection?: Prisma.SelectionUpdateOneWithoutSessionsNestedInput
}

export type SessionUncheckedUpdateWithoutSessionStepsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studyId?: Prisma.IntFieldUpdateOperationsInput | number
  stepId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  selectionId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SessionCreateManyStudyInput = {
  id?: number
  stepId?: number | null
  selectionId?: number | null
  date?: Date | string | null
  time?: Date | string | null
  insights?: string | null
  reference?: string | null
}

export type SessionUpdateWithoutStudyInput = {
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guideStep?: Prisma.GuideStepUpdateOneWithoutSessionsNestedInput
  selection?: Prisma.SelectionUpdateOneWithoutSessionsNestedInput
  sessionSteps?: Prisma.SessionStepUpdateManyWithoutSessionNestedInput
}

export type SessionUncheckedUpdateWithoutStudyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  stepId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  selectionId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sessionSteps?: Prisma.SessionStepUncheckedUpdateManyWithoutSessionNestedInput
}

export type SessionUncheckedUpdateManyWithoutStudyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  stepId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  selectionId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SessionCreateManySelectionInput = {
  id?: number
  studyId: number
  stepId?: number | null
  date?: Date | string | null
  time?: Date | string | null
  insights?: string | null
  reference?: string | null
}

export type SessionUpdateWithoutSelectionInput = {
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  study?: Prisma.StudyUpdateOneRequiredWithoutSessionsNestedInput
  guideStep?: Prisma.GuideStepUpdateOneWithoutSessionsNestedInput
  sessionSteps?: Prisma.SessionStepUpdateManyWithoutSessionNestedInput
}

export type SessionUncheckedUpdateWithoutSelectionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studyId?: Prisma.IntFieldUpdateOperationsInput | number
  stepId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sessionSteps?: Prisma.SessionStepUncheckedUpdateManyWithoutSessionNestedInput
}

export type SessionUncheckedUpdateManyWithoutSelectionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studyId?: Prisma.IntFieldUpdateOperationsInput | number
  stepId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SessionCreateManyGuideStepInput = {
  id?: number
  studyId: number
  selectionId?: number | null
  date?: Date | string | null
  time?: Date | string | null
  insights?: string | null
  reference?: string | null
}

export type SessionUpdateWithoutGuideStepInput = {
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  study?: Prisma.StudyUpdateOneRequiredWithoutSessionsNestedInput
  selection?: Prisma.SelectionUpdateOneWithoutSessionsNestedInput
  sessionSteps?: Prisma.SessionStepUpdateManyWithoutSessionNestedInput
}

export type SessionUncheckedUpdateWithoutGuideStepInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studyId?: Prisma.IntFieldUpdateOperationsInput | number
  selectionId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sessionSteps?: Prisma.SessionStepUncheckedUpdateManyWithoutSessionNestedInput
}

export type SessionUncheckedUpdateManyWithoutGuideStepInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  studyId?: Prisma.IntFieldUpdateOperationsInput | number
  selectionId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  insights?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reference?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type SessionCountOutputType
 */

export type SessionCountOutputType = {
  sessionSteps: number
}

export type SessionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sessionSteps?: boolean | SessionCountOutputTypeCountSessionStepsArgs
}

/**
 * SessionCountOutputType without action
 */
export type SessionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionCountOutputType
   */
  select?: Prisma.SessionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SessionCountOutputType without action
 */
export type SessionCountOutputTypeCountSessionStepsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionStepWhereInput
}


export type SessionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  studyId?: boolean
  stepId?: boolean
  selectionId?: boolean
  date?: boolean
  time?: boolean
  insights?: boolean
  reference?: boolean
  study?: boolean | Prisma.StudyDefaultArgs<ExtArgs>
  guideStep?: boolean | Prisma.Session$guideStepArgs<ExtArgs>
  selection?: boolean | Prisma.Session$selectionArgs<ExtArgs>
  sessionSteps?: boolean | Prisma.Session$sessionStepsArgs<ExtArgs>
  _count?: boolean | Prisma.SessionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["session"]>

export type SessionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  studyId?: boolean
  stepId?: boolean
  selectionId?: boolean
  date?: boolean
  time?: boolean
  insights?: boolean
  reference?: boolean
  study?: boolean | Prisma.StudyDefaultArgs<ExtArgs>
  guideStep?: boolean | Prisma.Session$guideStepArgs<ExtArgs>
  selection?: boolean | Prisma.Session$selectionArgs<ExtArgs>
}, ExtArgs["result"]["session"]>

export type SessionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  studyId?: boolean
  stepId?: boolean
  selectionId?: boolean
  date?: boolean
  time?: boolean
  insights?: boolean
  reference?: boolean
  study?: boolean | Prisma.StudyDefaultArgs<ExtArgs>
  guideStep?: boolean | Prisma.Session$guideStepArgs<ExtArgs>
  selection?: boolean | Prisma.Session$selectionArgs<ExtArgs>
}, ExtArgs["result"]["session"]>

export type SessionSelectScalar = {
  id?: boolean
  studyId?: boolean
  stepId?: boolean
  selectionId?: boolean
  date?: boolean
  time?: boolean
  insights?: boolean
  reference?: boolean
}

export type SessionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "studyId" | "stepId" | "selectionId" | "date" | "time" | "insights" | "reference", ExtArgs["result"]["session"]>
export type SessionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  study?: boolean | Prisma.StudyDefaultArgs<ExtArgs>
  guideStep?: boolean | Prisma.Session$guideStepArgs<ExtArgs>
  selection?: boolean | Prisma.Session$selectionArgs<ExtArgs>
  sessionSteps?: boolean | Prisma.Session$sessionStepsArgs<ExtArgs>
  _count?: boolean | Prisma.SessionCountOutputTypeDefaultArgs<ExtArgs>
}
export type SessionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  study?: boolean | Prisma.StudyDefaultArgs<ExtArgs>
  guideStep?: boolean | Prisma.Session$guideStepArgs<ExtArgs>
  selection?: boolean | Prisma.Session$selectionArgs<ExtArgs>
}
export type SessionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  study?: boolean | Prisma.StudyDefaultArgs<ExtArgs>
  guideStep?: boolean | Prisma.Session$guideStepArgs<ExtArgs>
  selection?: boolean | Prisma.Session$selectionArgs<ExtArgs>
}

export type $SessionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Session"
  objects: {
    study: Prisma.$StudyPayload<ExtArgs>
    guideStep: Prisma.$GuideStepPayload<ExtArgs> | null
    selection: Prisma.$SelectionPayload<ExtArgs> | null
    sessionSteps: Prisma.$SessionStepPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    studyId: number
    stepId: number | null
    selectionId: number | null
    date: Date | null
    time: Date | null
    insights: string | null
    reference: string | null
  }, ExtArgs["result"]["session"]>
  composites: {}
}

export type SessionGetPayload<S extends boolean | null | undefined | SessionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SessionPayload, S>

export type SessionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SessionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SessionCountAggregateInputType | true
  }

export interface SessionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Session'], meta: { name: 'Session' } }
  /**
   * Find zero or one Session that matches the filter.
   * @param {SessionFindUniqueArgs} args - Arguments to find a Session
   * @example
   * // Get one Session
   * const session = await prisma.session.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SessionFindUniqueArgs>(args: Prisma.SelectSubset<T, SessionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Session that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SessionFindUniqueOrThrowArgs} args - Arguments to find a Session
   * @example
   * // Get one Session
   * const session = await prisma.session.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SessionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SessionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Session that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionFindFirstArgs} args - Arguments to find a Session
   * @example
   * // Get one Session
   * const session = await prisma.session.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SessionFindFirstArgs>(args?: Prisma.SelectSubset<T, SessionFindFirstArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Session that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionFindFirstOrThrowArgs} args - Arguments to find a Session
   * @example
   * // Get one Session
   * const session = await prisma.session.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SessionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SessionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Sessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Sessions
   * const sessions = await prisma.session.findMany()
   * 
   * // Get first 10 Sessions
   * const sessions = await prisma.session.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sessionWithIdOnly = await prisma.session.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SessionFindManyArgs>(args?: Prisma.SelectSubset<T, SessionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Session.
   * @param {SessionCreateArgs} args - Arguments to create a Session.
   * @example
   * // Create one Session
   * const Session = await prisma.session.create({
   *   data: {
   *     // ... data to create a Session
   *   }
   * })
   * 
   */
  create<T extends SessionCreateArgs>(args: Prisma.SelectSubset<T, SessionCreateArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Sessions.
   * @param {SessionCreateManyArgs} args - Arguments to create many Sessions.
   * @example
   * // Create many Sessions
   * const session = await prisma.session.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SessionCreateManyArgs>(args?: Prisma.SelectSubset<T, SessionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Sessions and returns the data saved in the database.
   * @param {SessionCreateManyAndReturnArgs} args - Arguments to create many Sessions.
   * @example
   * // Create many Sessions
   * const session = await prisma.session.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Sessions and only return the `id`
   * const sessionWithIdOnly = await prisma.session.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SessionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SessionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Session.
   * @param {SessionDeleteArgs} args - Arguments to delete one Session.
   * @example
   * // Delete one Session
   * const Session = await prisma.session.delete({
   *   where: {
   *     // ... filter to delete one Session
   *   }
   * })
   * 
   */
  delete<T extends SessionDeleteArgs>(args: Prisma.SelectSubset<T, SessionDeleteArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Session.
   * @param {SessionUpdateArgs} args - Arguments to update one Session.
   * @example
   * // Update one Session
   * const session = await prisma.session.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SessionUpdateArgs>(args: Prisma.SelectSubset<T, SessionUpdateArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Sessions.
   * @param {SessionDeleteManyArgs} args - Arguments to filter Sessions to delete.
   * @example
   * // Delete a few Sessions
   * const { count } = await prisma.session.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SessionDeleteManyArgs>(args?: Prisma.SelectSubset<T, SessionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Sessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Sessions
   * const session = await prisma.session.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SessionUpdateManyArgs>(args: Prisma.SelectSubset<T, SessionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Sessions and returns the data updated in the database.
   * @param {SessionUpdateManyAndReturnArgs} args - Arguments to update many Sessions.
   * @example
   * // Update many Sessions
   * const session = await prisma.session.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Sessions and only return the `id`
   * const sessionWithIdOnly = await prisma.session.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SessionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SessionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Session.
   * @param {SessionUpsertArgs} args - Arguments to update or create a Session.
   * @example
   * // Update or create a Session
   * const session = await prisma.session.upsert({
   *   create: {
   *     // ... data to create a Session
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Session we want to update
   *   }
   * })
   */
  upsert<T extends SessionUpsertArgs>(args: Prisma.SelectSubset<T, SessionUpsertArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Sessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionCountArgs} args - Arguments to filter Sessions to count.
   * @example
   * // Count the number of Sessions
   * const count = await prisma.session.count({
   *   where: {
   *     // ... the filter for the Sessions we want to count
   *   }
   * })
  **/
  count<T extends SessionCountArgs>(
    args?: Prisma.Subset<T, SessionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SessionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Session.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SessionAggregateArgs>(args: Prisma.Subset<T, SessionAggregateArgs>): Prisma.PrismaPromise<GetSessionAggregateType<T>>

  /**
   * Group by Session.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SessionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SessionGroupByArgs['orderBy'] }
      : { orderBy?: SessionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SessionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSessionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Session model
 */
readonly fields: SessionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Session.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SessionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  study<T extends Prisma.StudyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.StudyDefaultArgs<ExtArgs>>): Prisma.Prisma__StudyClient<runtime.Types.Result.GetResult<Prisma.$StudyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  guideStep<T extends Prisma.Session$guideStepArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Session$guideStepArgs<ExtArgs>>): Prisma.Prisma__GuideStepClient<runtime.Types.Result.GetResult<Prisma.$GuideStepPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  selection<T extends Prisma.Session$selectionArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Session$selectionArgs<ExtArgs>>): Prisma.Prisma__SelectionClient<runtime.Types.Result.GetResult<Prisma.$SelectionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  sessionSteps<T extends Prisma.Session$sessionStepsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Session$sessionStepsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionStepPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Session model
 */
export interface SessionFieldRefs {
  readonly id: Prisma.FieldRef<"Session", 'Int'>
  readonly studyId: Prisma.FieldRef<"Session", 'Int'>
  readonly stepId: Prisma.FieldRef<"Session", 'Int'>
  readonly selectionId: Prisma.FieldRef<"Session", 'Int'>
  readonly date: Prisma.FieldRef<"Session", 'DateTime'>
  readonly time: Prisma.FieldRef<"Session", 'DateTime'>
  readonly insights: Prisma.FieldRef<"Session", 'String'>
  readonly reference: Prisma.FieldRef<"Session", 'String'>
}
    

// Custom InputTypes
/**
 * Session findUnique
 */
export type SessionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  /**
   * Filter, which Session to fetch.
   */
  where: Prisma.SessionWhereUniqueInput
}

/**
 * Session findUniqueOrThrow
 */
export type SessionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  /**
   * Filter, which Session to fetch.
   */
  where: Prisma.SessionWhereUniqueInput
}

/**
 * Session findFirst
 */
export type SessionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  /**
   * Filter, which Session to fetch.
   */
  where?: Prisma.SessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sessions to fetch.
   */
  orderBy?: Prisma.SessionOrderByWithRelationInput | Prisma.SessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Sessions.
   */
  cursor?: Prisma.SessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Sessions.
   */
  distinct?: Prisma.SessionScalarFieldEnum | Prisma.SessionScalarFieldEnum[]
}

/**
 * Session findFirstOrThrow
 */
export type SessionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  /**
   * Filter, which Session to fetch.
   */
  where?: Prisma.SessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sessions to fetch.
   */
  orderBy?: Prisma.SessionOrderByWithRelationInput | Prisma.SessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Sessions.
   */
  cursor?: Prisma.SessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Sessions.
   */
  distinct?: Prisma.SessionScalarFieldEnum | Prisma.SessionScalarFieldEnum[]
}

/**
 * Session findMany
 */
export type SessionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  /**
   * Filter, which Sessions to fetch.
   */
  where?: Prisma.SessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sessions to fetch.
   */
  orderBy?: Prisma.SessionOrderByWithRelationInput | Prisma.SessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Sessions.
   */
  cursor?: Prisma.SessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sessions.
   */
  skip?: number
  distinct?: Prisma.SessionScalarFieldEnum | Prisma.SessionScalarFieldEnum[]
}

/**
 * Session create
 */
export type SessionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  /**
   * The data needed to create a Session.
   */
  data: Prisma.XOR<Prisma.SessionCreateInput, Prisma.SessionUncheckedCreateInput>
}

/**
 * Session createMany
 */
export type SessionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Sessions.
   */
  data: Prisma.SessionCreateManyInput | Prisma.SessionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Session createManyAndReturn
 */
export type SessionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * The data used to create many Sessions.
   */
  data: Prisma.SessionCreateManyInput | Prisma.SessionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Session update
 */
export type SessionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  /**
   * The data needed to update a Session.
   */
  data: Prisma.XOR<Prisma.SessionUpdateInput, Prisma.SessionUncheckedUpdateInput>
  /**
   * Choose, which Session to update.
   */
  where: Prisma.SessionWhereUniqueInput
}

/**
 * Session updateMany
 */
export type SessionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Sessions.
   */
  data: Prisma.XOR<Prisma.SessionUpdateManyMutationInput, Prisma.SessionUncheckedUpdateManyInput>
  /**
   * Filter which Sessions to update
   */
  where?: Prisma.SessionWhereInput
  /**
   * Limit how many Sessions to update.
   */
  limit?: number
}

/**
 * Session updateManyAndReturn
 */
export type SessionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * The data used to update Sessions.
   */
  data: Prisma.XOR<Prisma.SessionUpdateManyMutationInput, Prisma.SessionUncheckedUpdateManyInput>
  /**
   * Filter which Sessions to update
   */
  where?: Prisma.SessionWhereInput
  /**
   * Limit how many Sessions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Session upsert
 */
export type SessionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  /**
   * The filter to search for the Session to update in case it exists.
   */
  where: Prisma.SessionWhereUniqueInput
  /**
   * In case the Session found by the `where` argument doesn't exist, create a new Session with this data.
   */
  create: Prisma.XOR<Prisma.SessionCreateInput, Prisma.SessionUncheckedCreateInput>
  /**
   * In case the Session was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SessionUpdateInput, Prisma.SessionUncheckedUpdateInput>
}

/**
 * Session delete
 */
export type SessionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  /**
   * Filter which Session to delete.
   */
  where: Prisma.SessionWhereUniqueInput
}

/**
 * Session deleteMany
 */
export type SessionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Sessions to delete
   */
  where?: Prisma.SessionWhereInput
  /**
   * Limit how many Sessions to delete.
   */
  limit?: number
}

/**
 * Session.guideStep
 */
export type Session$guideStepArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideStep
   */
  select?: Prisma.GuideStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideStep
   */
  omit?: Prisma.GuideStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideStepInclude<ExtArgs> | null
  where?: Prisma.GuideStepWhereInput
}

/**
 * Session.selection
 */
export type Session$selectionArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Selection
   */
  select?: Prisma.SelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Selection
   */
  omit?: Prisma.SelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectionInclude<ExtArgs> | null
  where?: Prisma.SelectionWhereInput
}

/**
 * Session.sessionSteps
 */
export type Session$sessionStepsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionStep
   */
  select?: Prisma.SessionStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionStep
   */
  omit?: Prisma.SessionStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionStepInclude<ExtArgs> | null
  where?: Prisma.SessionStepWhereInput
  orderBy?: Prisma.SessionStepOrderByWithRelationInput | Prisma.SessionStepOrderByWithRelationInput[]
  cursor?: Prisma.SessionStepWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SessionStepScalarFieldEnum | Prisma.SessionStepScalarFieldEnum[]
}

/**
 * Session without action
 */
export type SessionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
}
