
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Verse` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Verse
 * 
 */
export type VerseModel = runtime.Types.Result.DefaultSelection<Prisma.$VersePayload>

export type AggregateVerse = {
  _count: VerseCountAggregateOutputType | null
  _avg: VerseAvgAggregateOutputType | null
  _sum: VerseSumAggregateOutputType | null
  _min: VerseMinAggregateOutputType | null
  _max: VerseMaxAggregateOutputType | null
}

export type VerseAvgAggregateOutputType = {
  id: number | null
  chapterId: number | null
  number: number | null
}

export type VerseSumAggregateOutputType = {
  id: number | null
  chapterId: number | null
  number: number | null
}

export type VerseMinAggregateOutputType = {
  id: number | null
  chapterId: number | null
  number: number | null
  text: string | null
}

export type VerseMaxAggregateOutputType = {
  id: number | null
  chapterId: number | null
  number: number | null
  text: string | null
}

export type VerseCountAggregateOutputType = {
  id: number
  chapterId: number
  number: number
  text: number
  _all: number
}


export type VerseAvgAggregateInputType = {
  id?: true
  chapterId?: true
  number?: true
}

export type VerseSumAggregateInputType = {
  id?: true
  chapterId?: true
  number?: true
}

export type VerseMinAggregateInputType = {
  id?: true
  chapterId?: true
  number?: true
  text?: true
}

export type VerseMaxAggregateInputType = {
  id?: true
  chapterId?: true
  number?: true
  text?: true
}

export type VerseCountAggregateInputType = {
  id?: true
  chapterId?: true
  number?: true
  text?: true
  _all?: true
}

export type VerseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Verse to aggregate.
   */
  where?: Prisma.VerseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Verses to fetch.
   */
  orderBy?: Prisma.VerseOrderByWithRelationInput | Prisma.VerseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VerseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Verses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Verses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Verses
  **/
  _count?: true | VerseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: VerseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: VerseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VerseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VerseMaxAggregateInputType
}

export type GetVerseAggregateType<T extends VerseAggregateArgs> = {
      [P in keyof T & keyof AggregateVerse]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVerse[P]>
    : Prisma.GetScalarType<T[P], AggregateVerse[P]>
}




export type VerseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VerseWhereInput
  orderBy?: Prisma.VerseOrderByWithAggregationInput | Prisma.VerseOrderByWithAggregationInput[]
  by: Prisma.VerseScalarFieldEnum[] | Prisma.VerseScalarFieldEnum
  having?: Prisma.VerseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VerseCountAggregateInputType | true
  _avg?: VerseAvgAggregateInputType
  _sum?: VerseSumAggregateInputType
  _min?: VerseMinAggregateInputType
  _max?: VerseMaxAggregateInputType
}

export type VerseGroupByOutputType = {
  id: number
  chapterId: number
  number: number
  text: string | null
  _count: VerseCountAggregateOutputType | null
  _avg: VerseAvgAggregateOutputType | null
  _sum: VerseSumAggregateOutputType | null
  _min: VerseMinAggregateOutputType | null
  _max: VerseMaxAggregateOutputType | null
}

type GetVerseGroupByPayload<T extends VerseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VerseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VerseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VerseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VerseGroupByOutputType[P]>
      }
    >
  >



export type VerseWhereInput = {
  AND?: Prisma.VerseWhereInput | Prisma.VerseWhereInput[]
  OR?: Prisma.VerseWhereInput[]
  NOT?: Prisma.VerseWhereInput | Prisma.VerseWhereInput[]
  id?: Prisma.IntFilter<"Verse"> | number
  chapterId?: Prisma.IntFilter<"Verse"> | number
  number?: Prisma.IntFilter<"Verse"> | number
  text?: Prisma.StringNullableFilter<"Verse"> | string | null
  chapter?: Prisma.XOR<Prisma.ChapterScalarRelationFilter, Prisma.ChapterWhereInput>
  startSelections?: Prisma.SelectionListRelationFilter
  endSelections?: Prisma.SelectionListRelationFilter
}

export type VerseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  number?: Prisma.SortOrder
  text?: Prisma.SortOrderInput | Prisma.SortOrder
  chapter?: Prisma.ChapterOrderByWithRelationInput
  startSelections?: Prisma.SelectionOrderByRelationAggregateInput
  endSelections?: Prisma.SelectionOrderByRelationAggregateInput
}

export type VerseWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  chapterId_number?: Prisma.VerseChapterIdNumberCompoundUniqueInput
  AND?: Prisma.VerseWhereInput | Prisma.VerseWhereInput[]
  OR?: Prisma.VerseWhereInput[]
  NOT?: Prisma.VerseWhereInput | Prisma.VerseWhereInput[]
  chapterId?: Prisma.IntFilter<"Verse"> | number
  number?: Prisma.IntFilter<"Verse"> | number
  text?: Prisma.StringNullableFilter<"Verse"> | string | null
  chapter?: Prisma.XOR<Prisma.ChapterScalarRelationFilter, Prisma.ChapterWhereInput>
  startSelections?: Prisma.SelectionListRelationFilter
  endSelections?: Prisma.SelectionListRelationFilter
}, "id" | "chapterId_number">

export type VerseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  number?: Prisma.SortOrder
  text?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.VerseCountOrderByAggregateInput
  _avg?: Prisma.VerseAvgOrderByAggregateInput
  _max?: Prisma.VerseMaxOrderByAggregateInput
  _min?: Prisma.VerseMinOrderByAggregateInput
  _sum?: Prisma.VerseSumOrderByAggregateInput
}

export type VerseScalarWhereWithAggregatesInput = {
  AND?: Prisma.VerseScalarWhereWithAggregatesInput | Prisma.VerseScalarWhereWithAggregatesInput[]
  OR?: Prisma.VerseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VerseScalarWhereWithAggregatesInput | Prisma.VerseScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Verse"> | number
  chapterId?: Prisma.IntWithAggregatesFilter<"Verse"> | number
  number?: Prisma.IntWithAggregatesFilter<"Verse"> | number
  text?: Prisma.StringNullableWithAggregatesFilter<"Verse"> | string | null
}

export type VerseCreateInput = {
  number: number
  text?: string | null
  chapter: Prisma.ChapterCreateNestedOneWithoutVersesInput
  startSelections?: Prisma.SelectionCreateNestedManyWithoutStartVerseInput
  endSelections?: Prisma.SelectionCreateNestedManyWithoutEndVerseInput
}

export type VerseUncheckedCreateInput = {
  id?: number
  chapterId: number
  number: number
  text?: string | null
  startSelections?: Prisma.SelectionUncheckedCreateNestedManyWithoutStartVerseInput
  endSelections?: Prisma.SelectionUncheckedCreateNestedManyWithoutEndVerseInput
}

export type VerseUpdateInput = {
  number?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chapter?: Prisma.ChapterUpdateOneRequiredWithoutVersesNestedInput
  startSelections?: Prisma.SelectionUpdateManyWithoutStartVerseNestedInput
  endSelections?: Prisma.SelectionUpdateManyWithoutEndVerseNestedInput
}

export type VerseUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  chapterId?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startSelections?: Prisma.SelectionUncheckedUpdateManyWithoutStartVerseNestedInput
  endSelections?: Prisma.SelectionUncheckedUpdateManyWithoutEndVerseNestedInput
}

export type VerseCreateManyInput = {
  id?: number
  chapterId: number
  number: number
  text?: string | null
}

export type VerseUpdateManyMutationInput = {
  number?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type VerseUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  chapterId?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type VerseListRelationFilter = {
  every?: Prisma.VerseWhereInput
  some?: Prisma.VerseWhereInput
  none?: Prisma.VerseWhereInput
}

export type VerseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type VerseChapterIdNumberCompoundUniqueInput = {
  chapterId: number
  number: number
}

export type VerseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  number?: Prisma.SortOrder
  text?: Prisma.SortOrder
}

export type VerseAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  number?: Prisma.SortOrder
}

export type VerseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  number?: Prisma.SortOrder
  text?: Prisma.SortOrder
}

export type VerseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  number?: Prisma.SortOrder
  text?: Prisma.SortOrder
}

export type VerseSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  chapterId?: Prisma.SortOrder
  number?: Prisma.SortOrder
}

export type VerseNullableScalarRelationFilter = {
  is?: Prisma.VerseWhereInput | null
  isNot?: Prisma.VerseWhereInput | null
}

export type VerseCreateNestedManyWithoutChapterInput = {
  create?: Prisma.XOR<Prisma.VerseCreateWithoutChapterInput, Prisma.VerseUncheckedCreateWithoutChapterInput> | Prisma.VerseCreateWithoutChapterInput[] | Prisma.VerseUncheckedCreateWithoutChapterInput[]
  connectOrCreate?: Prisma.VerseCreateOrConnectWithoutChapterInput | Prisma.VerseCreateOrConnectWithoutChapterInput[]
  createMany?: Prisma.VerseCreateManyChapterInputEnvelope
  connect?: Prisma.VerseWhereUniqueInput | Prisma.VerseWhereUniqueInput[]
}

export type VerseUncheckedCreateNestedManyWithoutChapterInput = {
  create?: Prisma.XOR<Prisma.VerseCreateWithoutChapterInput, Prisma.VerseUncheckedCreateWithoutChapterInput> | Prisma.VerseCreateWithoutChapterInput[] | Prisma.VerseUncheckedCreateWithoutChapterInput[]
  connectOrCreate?: Prisma.VerseCreateOrConnectWithoutChapterInput | Prisma.VerseCreateOrConnectWithoutChapterInput[]
  createMany?: Prisma.VerseCreateManyChapterInputEnvelope
  connect?: Prisma.VerseWhereUniqueInput | Prisma.VerseWhereUniqueInput[]
}

export type VerseUpdateManyWithoutChapterNestedInput = {
  create?: Prisma.XOR<Prisma.VerseCreateWithoutChapterInput, Prisma.VerseUncheckedCreateWithoutChapterInput> | Prisma.VerseCreateWithoutChapterInput[] | Prisma.VerseUncheckedCreateWithoutChapterInput[]
  connectOrCreate?: Prisma.VerseCreateOrConnectWithoutChapterInput | Prisma.VerseCreateOrConnectWithoutChapterInput[]
  upsert?: Prisma.VerseUpsertWithWhereUniqueWithoutChapterInput | Prisma.VerseUpsertWithWhereUniqueWithoutChapterInput[]
  createMany?: Prisma.VerseCreateManyChapterInputEnvelope
  set?: Prisma.VerseWhereUniqueInput | Prisma.VerseWhereUniqueInput[]
  disconnect?: Prisma.VerseWhereUniqueInput | Prisma.VerseWhereUniqueInput[]
  delete?: Prisma.VerseWhereUniqueInput | Prisma.VerseWhereUniqueInput[]
  connect?: Prisma.VerseWhereUniqueInput | Prisma.VerseWhereUniqueInput[]
  update?: Prisma.VerseUpdateWithWhereUniqueWithoutChapterInput | Prisma.VerseUpdateWithWhereUniqueWithoutChapterInput[]
  updateMany?: Prisma.VerseUpdateManyWithWhereWithoutChapterInput | Prisma.VerseUpdateManyWithWhereWithoutChapterInput[]
  deleteMany?: Prisma.VerseScalarWhereInput | Prisma.VerseScalarWhereInput[]
}

export type VerseUncheckedUpdateManyWithoutChapterNestedInput = {
  create?: Prisma.XOR<Prisma.VerseCreateWithoutChapterInput, Prisma.VerseUncheckedCreateWithoutChapterInput> | Prisma.VerseCreateWithoutChapterInput[] | Prisma.VerseUncheckedCreateWithoutChapterInput[]
  connectOrCreate?: Prisma.VerseCreateOrConnectWithoutChapterInput | Prisma.VerseCreateOrConnectWithoutChapterInput[]
  upsert?: Prisma.VerseUpsertWithWhereUniqueWithoutChapterInput | Prisma.VerseUpsertWithWhereUniqueWithoutChapterInput[]
  createMany?: Prisma.VerseCreateManyChapterInputEnvelope
  set?: Prisma.VerseWhereUniqueInput | Prisma.VerseWhereUniqueInput[]
  disconnect?: Prisma.VerseWhereUniqueInput | Prisma.VerseWhereUniqueInput[]
  delete?: Prisma.VerseWhereUniqueInput | Prisma.VerseWhereUniqueInput[]
  connect?: Prisma.VerseWhereUniqueInput | Prisma.VerseWhereUniqueInput[]
  update?: Prisma.VerseUpdateWithWhereUniqueWithoutChapterInput | Prisma.VerseUpdateWithWhereUniqueWithoutChapterInput[]
  updateMany?: Prisma.VerseUpdateManyWithWhereWithoutChapterInput | Prisma.VerseUpdateManyWithWhereWithoutChapterInput[]
  deleteMany?: Prisma.VerseScalarWhereInput | Prisma.VerseScalarWhereInput[]
}

export type VerseCreateNestedOneWithoutStartSelectionsInput = {
  create?: Prisma.XOR<Prisma.VerseCreateWithoutStartSelectionsInput, Prisma.VerseUncheckedCreateWithoutStartSelectionsInput>
  connectOrCreate?: Prisma.VerseCreateOrConnectWithoutStartSelectionsInput
  connect?: Prisma.VerseWhereUniqueInput
}

export type VerseCreateNestedOneWithoutEndSelectionsInput = {
  create?: Prisma.XOR<Prisma.VerseCreateWithoutEndSelectionsInput, Prisma.VerseUncheckedCreateWithoutEndSelectionsInput>
  connectOrCreate?: Prisma.VerseCreateOrConnectWithoutEndSelectionsInput
  connect?: Prisma.VerseWhereUniqueInput
}

export type VerseUpdateOneWithoutStartSelectionsNestedInput = {
  create?: Prisma.XOR<Prisma.VerseCreateWithoutStartSelectionsInput, Prisma.VerseUncheckedCreateWithoutStartSelectionsInput>
  connectOrCreate?: Prisma.VerseCreateOrConnectWithoutStartSelectionsInput
  upsert?: Prisma.VerseUpsertWithoutStartSelectionsInput
  disconnect?: Prisma.VerseWhereInput | boolean
  delete?: Prisma.VerseWhereInput | boolean
  connect?: Prisma.VerseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.VerseUpdateToOneWithWhereWithoutStartSelectionsInput, Prisma.VerseUpdateWithoutStartSelectionsInput>, Prisma.VerseUncheckedUpdateWithoutStartSelectionsInput>
}

export type VerseUpdateOneWithoutEndSelectionsNestedInput = {
  create?: Prisma.XOR<Prisma.VerseCreateWithoutEndSelectionsInput, Prisma.VerseUncheckedCreateWithoutEndSelectionsInput>
  connectOrCreate?: Prisma.VerseCreateOrConnectWithoutEndSelectionsInput
  upsert?: Prisma.VerseUpsertWithoutEndSelectionsInput
  disconnect?: Prisma.VerseWhereInput | boolean
  delete?: Prisma.VerseWhereInput | boolean
  connect?: Prisma.VerseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.VerseUpdateToOneWithWhereWithoutEndSelectionsInput, Prisma.VerseUpdateWithoutEndSelectionsInput>, Prisma.VerseUncheckedUpdateWithoutEndSelectionsInput>
}

export type VerseCreateWithoutChapterInput = {
  number: number
  text?: string | null
  startSelections?: Prisma.SelectionCreateNestedManyWithoutStartVerseInput
  endSelections?: Prisma.SelectionCreateNestedManyWithoutEndVerseInput
}

export type VerseUncheckedCreateWithoutChapterInput = {
  id?: number
  number: number
  text?: string | null
  startSelections?: Prisma.SelectionUncheckedCreateNestedManyWithoutStartVerseInput
  endSelections?: Prisma.SelectionUncheckedCreateNestedManyWithoutEndVerseInput
}

export type VerseCreateOrConnectWithoutChapterInput = {
  where: Prisma.VerseWhereUniqueInput
  create: Prisma.XOR<Prisma.VerseCreateWithoutChapterInput, Prisma.VerseUncheckedCreateWithoutChapterInput>
}

export type VerseCreateManyChapterInputEnvelope = {
  data: Prisma.VerseCreateManyChapterInput | Prisma.VerseCreateManyChapterInput[]
  skipDuplicates?: boolean
}

export type VerseUpsertWithWhereUniqueWithoutChapterInput = {
  where: Prisma.VerseWhereUniqueInput
  update: Prisma.XOR<Prisma.VerseUpdateWithoutChapterInput, Prisma.VerseUncheckedUpdateWithoutChapterInput>
  create: Prisma.XOR<Prisma.VerseCreateWithoutChapterInput, Prisma.VerseUncheckedCreateWithoutChapterInput>
}

export type VerseUpdateWithWhereUniqueWithoutChapterInput = {
  where: Prisma.VerseWhereUniqueInput
  data: Prisma.XOR<Prisma.VerseUpdateWithoutChapterInput, Prisma.VerseUncheckedUpdateWithoutChapterInput>
}

export type VerseUpdateManyWithWhereWithoutChapterInput = {
  where: Prisma.VerseScalarWhereInput
  data: Prisma.XOR<Prisma.VerseUpdateManyMutationInput, Prisma.VerseUncheckedUpdateManyWithoutChapterInput>
}

export type VerseScalarWhereInput = {
  AND?: Prisma.VerseScalarWhereInput | Prisma.VerseScalarWhereInput[]
  OR?: Prisma.VerseScalarWhereInput[]
  NOT?: Prisma.VerseScalarWhereInput | Prisma.VerseScalarWhereInput[]
  id?: Prisma.IntFilter<"Verse"> | number
  chapterId?: Prisma.IntFilter<"Verse"> | number
  number?: Prisma.IntFilter<"Verse"> | number
  text?: Prisma.StringNullableFilter<"Verse"> | string | null
}

export type VerseCreateWithoutStartSelectionsInput = {
  number: number
  text?: string | null
  chapter: Prisma.ChapterCreateNestedOneWithoutVersesInput
  endSelections?: Prisma.SelectionCreateNestedManyWithoutEndVerseInput
}

export type VerseUncheckedCreateWithoutStartSelectionsInput = {
  id?: number
  chapterId: number
  number: number
  text?: string | null
  endSelections?: Prisma.SelectionUncheckedCreateNestedManyWithoutEndVerseInput
}

export type VerseCreateOrConnectWithoutStartSelectionsInput = {
  where: Prisma.VerseWhereUniqueInput
  create: Prisma.XOR<Prisma.VerseCreateWithoutStartSelectionsInput, Prisma.VerseUncheckedCreateWithoutStartSelectionsInput>
}

export type VerseCreateWithoutEndSelectionsInput = {
  number: number
  text?: string | null
  chapter: Prisma.ChapterCreateNestedOneWithoutVersesInput
  startSelections?: Prisma.SelectionCreateNestedManyWithoutStartVerseInput
}

export type VerseUncheckedCreateWithoutEndSelectionsInput = {
  id?: number
  chapterId: number
  number: number
  text?: string | null
  startSelections?: Prisma.SelectionUncheckedCreateNestedManyWithoutStartVerseInput
}

export type VerseCreateOrConnectWithoutEndSelectionsInput = {
  where: Prisma.VerseWhereUniqueInput
  create: Prisma.XOR<Prisma.VerseCreateWithoutEndSelectionsInput, Prisma.VerseUncheckedCreateWithoutEndSelectionsInput>
}

export type VerseUpsertWithoutStartSelectionsInput = {
  update: Prisma.XOR<Prisma.VerseUpdateWithoutStartSelectionsInput, Prisma.VerseUncheckedUpdateWithoutStartSelectionsInput>
  create: Prisma.XOR<Prisma.VerseCreateWithoutStartSelectionsInput, Prisma.VerseUncheckedCreateWithoutStartSelectionsInput>
  where?: Prisma.VerseWhereInput
}

export type VerseUpdateToOneWithWhereWithoutStartSelectionsInput = {
  where?: Prisma.VerseWhereInput
  data: Prisma.XOR<Prisma.VerseUpdateWithoutStartSelectionsInput, Prisma.VerseUncheckedUpdateWithoutStartSelectionsInput>
}

export type VerseUpdateWithoutStartSelectionsInput = {
  number?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chapter?: Prisma.ChapterUpdateOneRequiredWithoutVersesNestedInput
  endSelections?: Prisma.SelectionUpdateManyWithoutEndVerseNestedInput
}

export type VerseUncheckedUpdateWithoutStartSelectionsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  chapterId?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  endSelections?: Prisma.SelectionUncheckedUpdateManyWithoutEndVerseNestedInput
}

export type VerseUpsertWithoutEndSelectionsInput = {
  update: Prisma.XOR<Prisma.VerseUpdateWithoutEndSelectionsInput, Prisma.VerseUncheckedUpdateWithoutEndSelectionsInput>
  create: Prisma.XOR<Prisma.VerseCreateWithoutEndSelectionsInput, Prisma.VerseUncheckedCreateWithoutEndSelectionsInput>
  where?: Prisma.VerseWhereInput
}

export type VerseUpdateToOneWithWhereWithoutEndSelectionsInput = {
  where?: Prisma.VerseWhereInput
  data: Prisma.XOR<Prisma.VerseUpdateWithoutEndSelectionsInput, Prisma.VerseUncheckedUpdateWithoutEndSelectionsInput>
}

export type VerseUpdateWithoutEndSelectionsInput = {
  number?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chapter?: Prisma.ChapterUpdateOneRequiredWithoutVersesNestedInput
  startSelections?: Prisma.SelectionUpdateManyWithoutStartVerseNestedInput
}

export type VerseUncheckedUpdateWithoutEndSelectionsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  chapterId?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startSelections?: Prisma.SelectionUncheckedUpdateManyWithoutStartVerseNestedInput
}

export type VerseCreateManyChapterInput = {
  id?: number
  number: number
  text?: string | null
}

export type VerseUpdateWithoutChapterInput = {
  number?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startSelections?: Prisma.SelectionUpdateManyWithoutStartVerseNestedInput
  endSelections?: Prisma.SelectionUpdateManyWithoutEndVerseNestedInput
}

export type VerseUncheckedUpdateWithoutChapterInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startSelections?: Prisma.SelectionUncheckedUpdateManyWithoutStartVerseNestedInput
  endSelections?: Prisma.SelectionUncheckedUpdateManyWithoutEndVerseNestedInput
}

export type VerseUncheckedUpdateManyWithoutChapterInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  number?: Prisma.IntFieldUpdateOperationsInput | number
  text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type VerseCountOutputType
 */

export type VerseCountOutputType = {
  startSelections: number
  endSelections: number
}

export type VerseCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  startSelections?: boolean | VerseCountOutputTypeCountStartSelectionsArgs
  endSelections?: boolean | VerseCountOutputTypeCountEndSelectionsArgs
}

/**
 * VerseCountOutputType without action
 */
export type VerseCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VerseCountOutputType
   */
  select?: Prisma.VerseCountOutputTypeSelect<ExtArgs> | null
}

/**
 * VerseCountOutputType without action
 */
export type VerseCountOutputTypeCountStartSelectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SelectionWhereInput
}

/**
 * VerseCountOutputType without action
 */
export type VerseCountOutputTypeCountEndSelectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SelectionWhereInput
}


export type VerseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  chapterId?: boolean
  number?: boolean
  text?: boolean
  chapter?: boolean | Prisma.ChapterDefaultArgs<ExtArgs>
  startSelections?: boolean | Prisma.Verse$startSelectionsArgs<ExtArgs>
  endSelections?: boolean | Prisma.Verse$endSelectionsArgs<ExtArgs>
  _count?: boolean | Prisma.VerseCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["verse"]>

export type VerseSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  chapterId?: boolean
  number?: boolean
  text?: boolean
  chapter?: boolean | Prisma.ChapterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["verse"]>

export type VerseSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  chapterId?: boolean
  number?: boolean
  text?: boolean
  chapter?: boolean | Prisma.ChapterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["verse"]>

export type VerseSelectScalar = {
  id?: boolean
  chapterId?: boolean
  number?: boolean
  text?: boolean
}

export type VerseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "chapterId" | "number" | "text", ExtArgs["result"]["verse"]>
export type VerseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chapter?: boolean | Prisma.ChapterDefaultArgs<ExtArgs>
  startSelections?: boolean | Prisma.Verse$startSelectionsArgs<ExtArgs>
  endSelections?: boolean | Prisma.Verse$endSelectionsArgs<ExtArgs>
  _count?: boolean | Prisma.VerseCountOutputTypeDefaultArgs<ExtArgs>
}
export type VerseIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chapter?: boolean | Prisma.ChapterDefaultArgs<ExtArgs>
}
export type VerseIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  chapter?: boolean | Prisma.ChapterDefaultArgs<ExtArgs>
}

export type $VersePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Verse"
  objects: {
    chapter: Prisma.$ChapterPayload<ExtArgs>
    startSelections: Prisma.$SelectionPayload<ExtArgs>[]
    endSelections: Prisma.$SelectionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    chapterId: number
    number: number
    text: string | null
  }, ExtArgs["result"]["verse"]>
  composites: {}
}

export type VerseGetPayload<S extends boolean | null | undefined | VerseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VersePayload, S>

export type VerseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VerseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VerseCountAggregateInputType | true
  }

export interface VerseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Verse'], meta: { name: 'Verse' } }
  /**
   * Find zero or one Verse that matches the filter.
   * @param {VerseFindUniqueArgs} args - Arguments to find a Verse
   * @example
   * // Get one Verse
   * const verse = await prisma.verse.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VerseFindUniqueArgs>(args: Prisma.SelectSubset<T, VerseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VerseClient<runtime.Types.Result.GetResult<Prisma.$VersePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Verse that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VerseFindUniqueOrThrowArgs} args - Arguments to find a Verse
   * @example
   * // Get one Verse
   * const verse = await prisma.verse.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VerseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VerseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VerseClient<runtime.Types.Result.GetResult<Prisma.$VersePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Verse that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerseFindFirstArgs} args - Arguments to find a Verse
   * @example
   * // Get one Verse
   * const verse = await prisma.verse.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VerseFindFirstArgs>(args?: Prisma.SelectSubset<T, VerseFindFirstArgs<ExtArgs>>): Prisma.Prisma__VerseClient<runtime.Types.Result.GetResult<Prisma.$VersePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Verse that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerseFindFirstOrThrowArgs} args - Arguments to find a Verse
   * @example
   * // Get one Verse
   * const verse = await prisma.verse.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VerseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VerseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VerseClient<runtime.Types.Result.GetResult<Prisma.$VersePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Verses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Verses
   * const verses = await prisma.verse.findMany()
   * 
   * // Get first 10 Verses
   * const verses = await prisma.verse.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const verseWithIdOnly = await prisma.verse.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VerseFindManyArgs>(args?: Prisma.SelectSubset<T, VerseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VersePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Verse.
   * @param {VerseCreateArgs} args - Arguments to create a Verse.
   * @example
   * // Create one Verse
   * const Verse = await prisma.verse.create({
   *   data: {
   *     // ... data to create a Verse
   *   }
   * })
   * 
   */
  create<T extends VerseCreateArgs>(args: Prisma.SelectSubset<T, VerseCreateArgs<ExtArgs>>): Prisma.Prisma__VerseClient<runtime.Types.Result.GetResult<Prisma.$VersePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Verses.
   * @param {VerseCreateManyArgs} args - Arguments to create many Verses.
   * @example
   * // Create many Verses
   * const verse = await prisma.verse.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VerseCreateManyArgs>(args?: Prisma.SelectSubset<T, VerseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Verses and returns the data saved in the database.
   * @param {VerseCreateManyAndReturnArgs} args - Arguments to create many Verses.
   * @example
   * // Create many Verses
   * const verse = await prisma.verse.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Verses and only return the `id`
   * const verseWithIdOnly = await prisma.verse.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VerseCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VerseCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VersePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Verse.
   * @param {VerseDeleteArgs} args - Arguments to delete one Verse.
   * @example
   * // Delete one Verse
   * const Verse = await prisma.verse.delete({
   *   where: {
   *     // ... filter to delete one Verse
   *   }
   * })
   * 
   */
  delete<T extends VerseDeleteArgs>(args: Prisma.SelectSubset<T, VerseDeleteArgs<ExtArgs>>): Prisma.Prisma__VerseClient<runtime.Types.Result.GetResult<Prisma.$VersePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Verse.
   * @param {VerseUpdateArgs} args - Arguments to update one Verse.
   * @example
   * // Update one Verse
   * const verse = await prisma.verse.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VerseUpdateArgs>(args: Prisma.SelectSubset<T, VerseUpdateArgs<ExtArgs>>): Prisma.Prisma__VerseClient<runtime.Types.Result.GetResult<Prisma.$VersePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Verses.
   * @param {VerseDeleteManyArgs} args - Arguments to filter Verses to delete.
   * @example
   * // Delete a few Verses
   * const { count } = await prisma.verse.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VerseDeleteManyArgs>(args?: Prisma.SelectSubset<T, VerseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Verses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Verses
   * const verse = await prisma.verse.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VerseUpdateManyArgs>(args: Prisma.SelectSubset<T, VerseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Verses and returns the data updated in the database.
   * @param {VerseUpdateManyAndReturnArgs} args - Arguments to update many Verses.
   * @example
   * // Update many Verses
   * const verse = await prisma.verse.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Verses and only return the `id`
   * const verseWithIdOnly = await prisma.verse.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VerseUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VerseUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VersePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Verse.
   * @param {VerseUpsertArgs} args - Arguments to update or create a Verse.
   * @example
   * // Update or create a Verse
   * const verse = await prisma.verse.upsert({
   *   create: {
   *     // ... data to create a Verse
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Verse we want to update
   *   }
   * })
   */
  upsert<T extends VerseUpsertArgs>(args: Prisma.SelectSubset<T, VerseUpsertArgs<ExtArgs>>): Prisma.Prisma__VerseClient<runtime.Types.Result.GetResult<Prisma.$VersePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Verses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerseCountArgs} args - Arguments to filter Verses to count.
   * @example
   * // Count the number of Verses
   * const count = await prisma.verse.count({
   *   where: {
   *     // ... the filter for the Verses we want to count
   *   }
   * })
  **/
  count<T extends VerseCountArgs>(
    args?: Prisma.Subset<T, VerseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VerseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Verse.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VerseAggregateArgs>(args: Prisma.Subset<T, VerseAggregateArgs>): Prisma.PrismaPromise<GetVerseAggregateType<T>>

  /**
   * Group by Verse.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VerseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VerseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VerseGroupByArgs['orderBy'] }
      : { orderBy?: VerseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VerseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVerseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Verse model
 */
readonly fields: VerseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Verse.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VerseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  chapter<T extends Prisma.ChapterDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChapterDefaultArgs<ExtArgs>>): Prisma.Prisma__ChapterClient<runtime.Types.Result.GetResult<Prisma.$ChapterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  startSelections<T extends Prisma.Verse$startSelectionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Verse$startSelectionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SelectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  endSelections<T extends Prisma.Verse$endSelectionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Verse$endSelectionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SelectionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Verse model
 */
export interface VerseFieldRefs {
  readonly id: Prisma.FieldRef<"Verse", 'Int'>
  readonly chapterId: Prisma.FieldRef<"Verse", 'Int'>
  readonly number: Prisma.FieldRef<"Verse", 'Int'>
  readonly text: Prisma.FieldRef<"Verse", 'String'>
}
    

// Custom InputTypes
/**
 * Verse findUnique
 */
export type VerseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verse
   */
  select?: Prisma.VerseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verse
   */
  omit?: Prisma.VerseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VerseInclude<ExtArgs> | null
  /**
   * Filter, which Verse to fetch.
   */
  where: Prisma.VerseWhereUniqueInput
}

/**
 * Verse findUniqueOrThrow
 */
export type VerseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verse
   */
  select?: Prisma.VerseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verse
   */
  omit?: Prisma.VerseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VerseInclude<ExtArgs> | null
  /**
   * Filter, which Verse to fetch.
   */
  where: Prisma.VerseWhereUniqueInput
}

/**
 * Verse findFirst
 */
export type VerseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verse
   */
  select?: Prisma.VerseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verse
   */
  omit?: Prisma.VerseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VerseInclude<ExtArgs> | null
  /**
   * Filter, which Verse to fetch.
   */
  where?: Prisma.VerseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Verses to fetch.
   */
  orderBy?: Prisma.VerseOrderByWithRelationInput | Prisma.VerseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Verses.
   */
  cursor?: Prisma.VerseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Verses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Verses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Verses.
   */
  distinct?: Prisma.VerseScalarFieldEnum | Prisma.VerseScalarFieldEnum[]
}

/**
 * Verse findFirstOrThrow
 */
export type VerseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verse
   */
  select?: Prisma.VerseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verse
   */
  omit?: Prisma.VerseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VerseInclude<ExtArgs> | null
  /**
   * Filter, which Verse to fetch.
   */
  where?: Prisma.VerseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Verses to fetch.
   */
  orderBy?: Prisma.VerseOrderByWithRelationInput | Prisma.VerseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Verses.
   */
  cursor?: Prisma.VerseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Verses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Verses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Verses.
   */
  distinct?: Prisma.VerseScalarFieldEnum | Prisma.VerseScalarFieldEnum[]
}

/**
 * Verse findMany
 */
export type VerseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verse
   */
  select?: Prisma.VerseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verse
   */
  omit?: Prisma.VerseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VerseInclude<ExtArgs> | null
  /**
   * Filter, which Verses to fetch.
   */
  where?: Prisma.VerseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Verses to fetch.
   */
  orderBy?: Prisma.VerseOrderByWithRelationInput | Prisma.VerseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Verses.
   */
  cursor?: Prisma.VerseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Verses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Verses.
   */
  skip?: number
  distinct?: Prisma.VerseScalarFieldEnum | Prisma.VerseScalarFieldEnum[]
}

/**
 * Verse create
 */
export type VerseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verse
   */
  select?: Prisma.VerseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verse
   */
  omit?: Prisma.VerseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VerseInclude<ExtArgs> | null
  /**
   * The data needed to create a Verse.
   */
  data: Prisma.XOR<Prisma.VerseCreateInput, Prisma.VerseUncheckedCreateInput>
}

/**
 * Verse createMany
 */
export type VerseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Verses.
   */
  data: Prisma.VerseCreateManyInput | Prisma.VerseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Verse createManyAndReturn
 */
export type VerseCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verse
   */
  select?: Prisma.VerseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Verse
   */
  omit?: Prisma.VerseOmit<ExtArgs> | null
  /**
   * The data used to create many Verses.
   */
  data: Prisma.VerseCreateManyInput | Prisma.VerseCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VerseIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Verse update
 */
export type VerseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verse
   */
  select?: Prisma.VerseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verse
   */
  omit?: Prisma.VerseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VerseInclude<ExtArgs> | null
  /**
   * The data needed to update a Verse.
   */
  data: Prisma.XOR<Prisma.VerseUpdateInput, Prisma.VerseUncheckedUpdateInput>
  /**
   * Choose, which Verse to update.
   */
  where: Prisma.VerseWhereUniqueInput
}

/**
 * Verse updateMany
 */
export type VerseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Verses.
   */
  data: Prisma.XOR<Prisma.VerseUpdateManyMutationInput, Prisma.VerseUncheckedUpdateManyInput>
  /**
   * Filter which Verses to update
   */
  where?: Prisma.VerseWhereInput
  /**
   * Limit how many Verses to update.
   */
  limit?: number
}

/**
 * Verse updateManyAndReturn
 */
export type VerseUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verse
   */
  select?: Prisma.VerseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Verse
   */
  omit?: Prisma.VerseOmit<ExtArgs> | null
  /**
   * The data used to update Verses.
   */
  data: Prisma.XOR<Prisma.VerseUpdateManyMutationInput, Prisma.VerseUncheckedUpdateManyInput>
  /**
   * Filter which Verses to update
   */
  where?: Prisma.VerseWhereInput
  /**
   * Limit how many Verses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VerseIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Verse upsert
 */
export type VerseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verse
   */
  select?: Prisma.VerseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verse
   */
  omit?: Prisma.VerseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VerseInclude<ExtArgs> | null
  /**
   * The filter to search for the Verse to update in case it exists.
   */
  where: Prisma.VerseWhereUniqueInput
  /**
   * In case the Verse found by the `where` argument doesn't exist, create a new Verse with this data.
   */
  create: Prisma.XOR<Prisma.VerseCreateInput, Prisma.VerseUncheckedCreateInput>
  /**
   * In case the Verse was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VerseUpdateInput, Prisma.VerseUncheckedUpdateInput>
}

/**
 * Verse delete
 */
export type VerseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verse
   */
  select?: Prisma.VerseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verse
   */
  omit?: Prisma.VerseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VerseInclude<ExtArgs> | null
  /**
   * Filter which Verse to delete.
   */
  where: Prisma.VerseWhereUniqueInput
}

/**
 * Verse deleteMany
 */
export type VerseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Verses to delete
   */
  where?: Prisma.VerseWhereInput
  /**
   * Limit how many Verses to delete.
   */
  limit?: number
}

/**
 * Verse.startSelections
 */
export type Verse$startSelectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Selection
   */
  select?: Prisma.SelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Selection
   */
  omit?: Prisma.SelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectionInclude<ExtArgs> | null
  where?: Prisma.SelectionWhereInput
  orderBy?: Prisma.SelectionOrderByWithRelationInput | Prisma.SelectionOrderByWithRelationInput[]
  cursor?: Prisma.SelectionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SelectionScalarFieldEnum | Prisma.SelectionScalarFieldEnum[]
}

/**
 * Verse.endSelections
 */
export type Verse$endSelectionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Selection
   */
  select?: Prisma.SelectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Selection
   */
  omit?: Prisma.SelectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SelectionInclude<ExtArgs> | null
  where?: Prisma.SelectionWhereInput
  orderBy?: Prisma.SelectionOrderByWithRelationInput | Prisma.SelectionOrderByWithRelationInput[]
  cursor?: Prisma.SelectionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SelectionScalarFieldEnum | Prisma.SelectionScalarFieldEnum[]
}

/**
 * Verse without action
 */
export type VerseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Verse
   */
  select?: Prisma.VerseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Verse
   */
  omit?: Prisma.VerseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VerseInclude<ExtArgs> | null
}
